.travis.yml
scripts/test-build.sh
scripts/test-codingstyle.sh

This set of patches adds continuous build and code-style tests to be run on new commits and pull requests. It utilizes Travis CI for open-source projects (https://travis-ci.org/), which runs the specified tests on an Ubuntu 14.04 VM.

Add scripts for Travis CI integration

---

.travis.yml

Travis builds seem to fail when compiling some of the tools on
gcc 4.8.
This installs gcc and g++ 5 on Travis and sets up CC and CXX
environment variables. Done according to
https://docs.travis-ci.com/user/languages/c/#GCC-on-Linux

Update Travis CI config to use gcc 5

---

.travis.yml
scripts/test-build.sh

GCC seems to require too much memory on Travis (see #16, which didn't
really fix things). This reverts the switch to GCC 5, but forces Travis
to build things sequentially to reduce memory consumption.

Remove '-j' switch on Travis make

---

ase/sw/ase_common.h
ase/sw/mem_model.c
ase/sw/protocol_backend.c
ase/sw/tstamp_ops.c

- Changed global variables in protocol_backend.c such as session_empty, glbl_session_id, f_usrclk, glbl_umsgmode, umsg_mode_msg and app_run_cmd to be local varialble or static local variables; 
- Moved global variable cfg declaration from ase_common.h to protocol_backend.c;
- Fixed a memory leak issue in variable app_run_cmd
Passed regression test on Linux VM locally

ASE: Code refactoring --changing global variables to local variables to static local variables

---

ase/scripts/generate_ase_environment.py

When an invoked command fails, explicitly warn that OPAE SDK's installed bin directory must be on PATH.

 Add an even more descriptive warning about setting PATH

---

platforms/platform_if/rtl/device_if/ccip_if_pkg.sv
platforms/scripts/afu_platform_config

Updated to the latest fields widths for interrupts.
Most of the changes are just comments (field sizes). Tested on a variety of Xeon+FPGA platforms before commit.

Update ccip_if_pkg to latest version

---

cmake/modules/compiler_config.cmake
libopae/src/event.c

Changing the order of include files in event.c causes pthreads.h to be
included with _GNU_SOURCE set (libopae/src/common_int.h), which adds
the definition of PTHREAD_MUTEX_RECURSIVE.
Drop some compiler warnings that were generating lots of errors in
system includes.

Fix pthreads compilation problem and compiler flags

---

tools/libopae++/perf_counters.cpp

nlb_stats relies on operator-() overloads for fpga_cache_counters and
fpga_fabric_counters to give it correct results for display. This
improvement checks for the case that the hardware counter has wrapped
and gives a value accounting for the counter wrap, rather than an errant
value exhibiting integer overflow.

fpgadiag: correct perf counter wrap when it occurs

---

tools/hssi/config_app.cpp
tools/hssi/config_app.h
tools/hssi/i2c.cpp
tools/hssi/i2c.h

Change i2c class:
* Change constructor to take in device address width
* This is in bytes with a default value of 1
* Add i2c::send_byte_address function that sends the byte
address over i2c and uses the byte_address_size_ member var
Note: The byte address is in big-endian format so we start
with the upper bytes of the byte address
* Change i2c::read and i2c::write to use i2c::send_byte_address
Change config_app:
* Add a --byte-address-size command line argument
and default it to 1 byte
* Instantiate an i2c device with the byte address size

hssi: add multi-byte byte address support for I2C

---

cmake/modules/compiler_config.cmake

Change the following cmake variables from CACHE'ed to uncached so that
cmake uses them to set the compiler flags:
CMAKE_C/CXX_FLAGS_DEBUG
CMAKE_C/CXX_FLAGS_RELWITHDEBUGINFO
CMAKE_C/CXX_FLAGS_RELEASE
CMAKE_C/CXX_FLAGS_MINSIZEREL
Remove set() directives that were attempting to silence certain classes
of warnings, as using them contradicts -Wall.

cmake: fix build types; remove masking of warnings

---

tools/packager/afu.py
tools/packager/schema/afu_schema_v01.json

This change is backward compatible with existing JSON and platform build scripts.
AFUs may be configured to run on multiple platforms. It makes little sense to
specify the platform's interface-uuid in a static AFU JSON file.  The schema no
longer requires "interface-uuid", making it possible to write an abstract AFU
JSON file and fill in the UUID at packaging time.
Typically, a packaging script for a particular platform sets interface-uuid.
The afu.py script is updated to provide syntax for specifying a key's full path,
making it possible to set afu-image/interface-uuid. The script is also updated
for legacy support: when just "interface-uuid" is specified it is assumed to be
"afu-image/interface-uuid".
Added "afu-image/afu-top-interface" to the schema for specifying the top-level …

Improve support for platform database in AFU JSON

---

tools/fpgadiag/mux.cpp

The command line option for specifying the mux configuration had
been previously changed to `config` from `muxfile`. This updates mux.cpp
to use the `config` key instead of `muxfile`.

fpgamux: Change `muxfile` to `config`

---

cmake/modules/compiler_config.cmake

Can we please exclude this one warning that is fired over and over by Boost code that isn't in our control? When it's on you can't see the warnings that are under our control.
It's also not the sort of syntax that is a major problem and looks bad to customers.

Don't warn on C++ unused local typedefs because of Boost warnings

---

samples/CMakeLists.txt

Change samples/CMakeLists.txt to use ${OPAE_SDK_SOURCE} in its include
path instead of ${CMAKE_SOURCE_DIR}. This allows it to build when the
OPAE repo is a subdirectory of another CMake based build.

cmake: Change CMAKE_SOURCE_DIR to OPAE_SDK_SOURCE

---

tools/fpgainfo/fpga_fmeinfo.py
tools/fpgainfo/fpgaerr.py
tools/fpgainfo/fpgatemp.py
tools/fpgainfo/sysfs.py

Refactor classes/functions is sysfs.py for better property enumeration and better
handling of dynamic properties. 
These changes also fixes an issue with errors not being accurately reflected from sysfs nodes.
Add a function called `add_static_property` that adds a class property
and uses the passed in path to
* Read and parse the sysfs file when getting
* Write to the sysfs file when setting
Add function `add_dynamic_property` that is used to add properties to
objects (rather that classes) depending on whether the relative sysfs
path exists. This should be used in the __init__ method of
sysfs_resource subclasses to add properties only if the relative path
exists.
This also changes `fme_errors` and `port_errors` to use this method.
Add new method, `enum_props` that enumerates object/class …

fpgainfo: refactor sysfs properties

---

libopae++/include/opaec++/handle.h
libopae++/include/opaec++/properties.h
libopae++/include/opaec++/pvalue.h
libopae++/include/opaec++/token.h
libopae++/src/token.cpp

Follow the convention that system headers be included first.
Use opaec++/header.h when refering to opaec++ headers.

opaec++: include cleanup

---

tools/packager/CMakeLists.txt

CMake 2.X doesn't support "\" to split a long string to multiple lines in a variable. Fix packager/CMakeLists.txt file to work with minimum CMake version.

Fix string variable line split issue for CMake 2.X

---

ase/scripts/afu_sim_setup
ase/scripts/create_ase_simbuild_env.sh

All we can count on is the relative positions of the installed
bin and share directories.

The true installation path is unknown when users install from an RPM.

---

platforms/scripts/afu_platform_config

The true installation path is unknown when users install from an RPM.
All we can count on is the relative positions of the installed
bin and share directories.
Also fixed an error in finding all the platforms and interfaces for the
--help message.
These are both needed for release/0.13.

Fix method for finding the installed share/opae directory.

---

libopae++/include/opaec++/handle.h
libopae++/include/opaec++/properties.h
libopae++/include/opaec++/token.h
libopae++/samples/simple_example.cpp

Add implicit conversion operator to the following classes:
* `properties`
* convert to `fpga_properties`
* `token`
* convert to `fpga_token`
* `handle`
* convert to `fpga_handle`
Update simple_example to account for conversion operators. More
specifically:
* replace `p->get()` with `*p` when calling OPAE C API functions.
* use the `<<` operator on the `guid` property since it overloads it

c++: Add implicit conversion operator

---

libopae/CMakeLists.txt

Not linking opae-c with pthreads placed the burden on applications to
link with the library. This change adds -lpthread to the opae-c link
line where it rightly belongs.

opae-c: link libopae-c with pthreads

---

libopae++/include/opaec++/pvalue.h

When the stream operator is called on a pvalue struct or a guid_t
struct, its copied value may not be an accurate reflection of the
property stored in its `fpga_properties*` member variable `props_`
This updates the `<<` operator to use the approprate getter function
(`get_` for `pvalue` or `fpgaPropertiesGetGUID` for `guid_t`) to get
the value from its `fpga_properties*` member, `props_`.

c++: Fix pvalue stream operator to call fpga get

---

libopae++/samples/simple_example.cpp
libopae++/src/handle.cpp

Update handle class to use implicit conversion operator for handle and
for properties::type.
Update simple_example to use handle::read and handle::write and
handle::mmio_ptr.

c++: Update API and example to use new APIs

---

libopae++/CMakeLists.txt
libopae++/include/opaec++/dma_buffer.h
libopae++/src/dma_buffer.cpp
libopae++/tests/CMakeLists.txt
libopae++/tests/unit/gtBuffer.cpp

Provides methods for fill, compare, read, write, poll, wait, and split.
Tracks the buffer owner (handle) so that it is not released before the
buffer.

opaec++: add DMA buffer support

---

libopae++/include/opaec++/properties.h
libopae++/include/opaec++/token.h
libopae++/src/properties.cpp
libopae++/src/token.cpp

Add a static variable, `properties::none` that is initialized to an empty vector of `properties`

c++: Add static variable, properties::none

---

libopae++/include/opaec++/pvalue.h

Change call to `fpgaPropertiesGetGUID` to use `data_.data()` instead of
`&data_`

c++: Change guid_t uint8_t* conversion operator

---

ase/rtl/platform.vh

- AFU MMIO timeout has been reported to be restrictive . The MMIO timeout
has been extended from 1.28us to 163.84us. For ASE, MMIO_RDRSP_TIMEOUT has
to be changed from 512 to 512*128=65536 pClk.

ASE: MMIO Read Response Timeout value changed to 65536 pClks

---

CMakeLists.txt
safe_string/CMakeLists.txt

Safe string library is built and used with OPAE.  It is also needed for some AFUs now and probably more in the future.  This PR causes the safe string library to be installed with OPAE.

Install safe string library with opae-devel

---

libopae++/include/opaec++/dma_buffer.h
libopae++/include/opaec++/handle.h
libopae++/include/opaec++/properties.h
libopae++/include/opaec++/pvalue.h
libopae++/include/opaec++/token.h
libopae++/samples/simple_example.cpp
libopae++/src/dma_buffer.cpp
libopae++/src/handle.cpp
libopae++/src/properties.cpp
libopae++/src/token.cpp
libopae++/tests/gtmain.cpp
libopae++/tests/unit/gtBuffer.cpp
libopae++/tests/unit/gtCxxProperties.cpp
libopae++/tests/unit/gtEnumerate.cpp
libopae++/tests/unit/gtOpenClose.cpp

I used clang-format to modify all .h|.cpp files in the libopae++
codebase to apply google's coding style for C++.
_NOTE:_ Because this coding style uses two-space indentation instead of
the four that had been used before, this change will touch most code.

c++: apply coding style

---

libopae++/CMakeLists.txt
libopae++/include/opaec++/except.h
libopae++/src/except.cpp
libopae++/tests/CMakeLists.txt
libopae++/tests/unit/gtBuffer.cpp
libopae++/tests/unit/gtExcept.cpp

except encapsulates a location in the source code along with an
fpga_result flag. except overrides std::exception::what() to provide an
informative message about the exception.

opaec++: add class except for runtime exceptions

---

libopae++/include/opaec++/properties.h
libopae++/include/opaec++/pvalue.h
libopae++/src/properties.cpp
libopae++/tests/unit/gtCxxProperties.cpp

* Add a constructor to `properties` class with only one parameter of type
`fpga_guid`.
This contructor is to allow implicit conversion of an fpga_guid object
to a properties object.
* Add `get` method to `guid_t` class that returns a pointer to the guid
data.
* Add unit test for this too and fix other unit test to have a more
explicit comparison (`memcmpof`)  guid objects.

c++: Enhance `guid_t` and add ctor to `properties`

---

CMakeLists.txt
cmake/config/config.h.in
libopae/CMakeLists.txt

Creates a config_int.h containing CMake variables, including version
information and the current git hash.
This is in preparation for an API that allows software to query the
current OPAE API's release.

libopae: Generate config_int.h with version info

---

tools/hssi/loopback_app.cpp

The help message was using `-p` for packet count
when it should be `-c`

hssi: fix help message for `send` command

---

ase/scripts/generate_ase_environment.py

ASE searches for verilog/SV include files in DUT_INCDIR
using relative paths (sim_afu). QuestaSim
needs absolute path for include files.
(cherry picked from commit 14ba1121473181a06e8979ade3466273127430dd)

Use absolute paths in DUT_INCDIR to keep QuestaSim happy (#261) (#264)

---

tools/fpgadiag/mb1.cpp

mb1 declares class member variable dsm_. The run() function was using
a local variable to allocate the buffer, but then attempting to use dsm_
to run the actual test. This resulted in a segfault. The fix is to both
allocate and use dsm_.

mb1: fix device status memory issue

---

.travis.yml
libopae++/CMakeLists.txt
libopae++/include/opaec++/log.h
libopae++/src/log.cpp
tests/CMakeLists.txt
tests/unit/gtCxxLog.cpp

* Add a named logger class that is used to start a logging stream
sequence with an indicated log level. This returns a `wrapped_logger`
object which is used to stream the log message and eventually emit it to
its destination by calling the log methat in libopae-c
* Add a unit test to verify the error messages are sent to stderr in the
expected format

c++: Add C++ logger class

---

libopae++/include/opaec++/log.h
libopae++/src/log.cpp
tests/unit/gtCxxLog.cpp

* Create a null_stream object that derives from wrapped_stream but does
nothing at the end of the stream
* Change `logger` methods to `const`
* Change `wrapped_stream::sstream_` member variable to
* protected
* a pointer
* Check if `wrapped_stream::sstream_` member is null in the `<<` operator overaloads
* Add `warn_if` and `error_if` functions return `null_stream` instance
when the condition argument is null

add logger `warn_if` and `error_if` functions

---

libopae++/include/opaec++/pvalue.h
tests/unit/gtCxxProperties.cpp

* Define `copy_t` as either `T` or `std::string` for `char*`
* Specialize pvalue<char*>::operator copy_t()
* To call the getter function with a char[] declared on the stack
* Assign the value of the char[] if the getter succeeds
* Add doxygen documentation to pvalue
* Add unit test for getting model

c++: add pvalue<char*> specialization plus docs

---

libopae++/include/opaec++/dma_buffer.h
libopae++/include/opaec++/properties.h
libopae++/include/opaec++/pvalue.h
libopae++/src/except.cpp
libopae++/src/properties.cpp

Adds copy c'tor and copy assignment operator to class properties.
Previously, the compiler-generated copy c'tor was errantly creating
shallow copies of properties. This resulted in multiple calls to
fpgaDestroyProperties() for the same C properties pointer. Implementing
deep copy for properties avoids this issue.

opaec++: make properties object copyable

---

samples/hello_events.c

Compiler was warning about ignoring the return value of `read`
This assigns the return value to `bytes_read` and acts on it if zero

Fix compile warning in hello_events

---

samples/hello_events.c

In hello_events.c, check `bytes_read` from calling `read` to be <= 0
and if less than zero, print out the string error of errno.
Otherwise, print out "zero bytes read"

check for negative return value from `read`

---

libopae++/include/opaec++/buffers.h
libopae++/include/opaec++/dma_buffer.h
libopae++/src/dma_buffer.cpp
tests/CMakeLists.txt
tests/unit/gtCxxBuffer.cpp

This migrates functionality that is not intended to go into the core c++
library
* Move `poll` and `wait` template functions into new file `buffers.h`
* Create a `buffer_chunk` class that can be used to split buffers
* Add gtCxxBuffers to tests

c++: Migrate dma_buffer functions to separate file

---

libopae/src/usrclk/user_clk_pgm_uclock.c

Allow primary clock frequencies down to 100 MHz.

User clock range check was wrong for userclk_low

---

libopae++/CMakeLists.txt
libopae++/include/opaec++/events.h
libopae++/src/events.cpp
scripts/test-gtapi-mock-drv.sh
tests/CMakeLists.txt
tests/unit/gtCxxEvents.cpp

Add file `opae::fpga::types::event` class that wraps basic event
functions in OPAE C API.
Add two unit tests to test basic functionality
Add starting/stopping of `fpgad` in test script

c++: Add event class and tests

---

platforms/platform_db/platform_defaults.json
platforms/platform_if/par/platform_if_addenda.qsf
platforms/platform_if/rtl/device_cfg/ccip_cfg_pkg.sv
platforms/platform_if/rtl/platform_shims/utils/BBB_ccip_async/README
platforms/platform_if/rtl/platform_shims/utils/BBB_ccip_async/platform_utils_ccip_async_shim.sv
platforms/platform_if/rtl/platform_shims/utils/platform_utils_ccip_activity_cnt.sv
platforms/platform_if/rtl/platform_shims/utils/platform_utils_ccip_async_shim.sv
platforms/platform_if/rtl/platform_shims/utils/quartus_ip/platform_utils_dc_fifo.sdc
platforms/platform_if/rtl/platform_shims/utils/quartus_ip/platform_utils_dc_fifo.sv
platforms/platform_if/sim/platform_if_addenda.txt

- Better timing, tested to 500 MHz
- Simplify DC FIFO control logic and reduce pipeline stages
- Bug fixes for almost full overrun due to long pipelines
- Restructure for better separation of Quartus IP from platform logic

Improve CCI-P clock crossing shim

---

CMakeLists.txt
ase/api/CMakeLists.txt
doc/src/install_guide/installation_guide.md
tests/CMakeLists.txt
tools/packager/CMakeLists.txt

target_compile_options() needs the cmake version to be 2.8.12
or higher

Update minimum Cmake version to 2.8.12

---

common/include/opae/cxx/buffers.h
common/include/opae/cxx/dma_buffer.h
common/include/opae/cxx/handle.h
libopae++/src/dma_buffer.cpp

Creating shallow copies of these objects must be avoided, so we prohibit
it explicitly.

opaec++: make dma_buffer and handle uncopyable

---

common/include/opae/cxx/pvalue.h

The guid_t ostream streamer was retrieving the current guid value from
the underlying properties object, but was streaming the cached local
copy of the guid. Ideally, we want to update the cached local copy of
the guid, then stream it; however, the guid_t in question is passed by
const &.

opaec++: fix guid_t streamer issue

---

common/include/opae/cxx/pvalue.h

Member variable is_set_ tracks whether the local cached copy of the
object is in sync with the last call to the underlying property get
function. Each of the non-const members in these class must be careful to
reset is_set_ to false before modifying the cached copy and then to true
only on successful completion.

opaec++: Fix guid_t and pvalue mutators

---

tools/fpgadiag/mb1.cpp

mb1 declares class member variable dsm_. The run() function was using
a local variable to allocate the buffer, but then attempting to use dsm_
to run the actual test. This resulted in a segfault. The fix is to both
allocate and use dsm_.

mb1: fix device status memory issue (#111)

---

tools/mmlink/main.cpp

Prior to this change, mmlink had the following errors in its
command-line parsing.
* The program did not respond to -h nor --help
* The names of the long options, eg --tcpport, did not match those
appearing in the help message.
* The IP address field stored in the command params did not support a
true string IP address. This meant that the IP address was required to
be input as an integer value, accounting for the correct
host/network byte ordering.
This change addresses these issues.

mmlink: fix command line options

---

libopae/src/event.c

- Use log level FPGA_MSG() when trying to detect whether
interrupts are supported in hardware. MCP does not support
interrupts, and an error message could be unnecessary noise
for the user.

Change events log level

---

doc/opae-c++/opaecxx.md

Sync the plantuml diagrams with the current code implementation of the
first layer. Provide some explanatory text for some of the first layer
interactions. Make a few misc fixes.

opaec++: update the documentation

---

tools/fpgabist/bist_common.py

Cherry pick internal:
Rework the way B,D, or F input handles hex values.
Print the information in more human readable format
using hex() function. Also handle invalid inputs better.

BDF to accept hexadecimal values. (#288)

---

common/include/safe_string/safe_string.h
safe_string/snprintf_support.c
tools/fpgad/ap_event.c
tools/fpgad/errtable.c
tools/fpgad/evt.c

In preparation for enabling the additional safe string checkers, this
change replaces instances of snprintf and strlen with the safe string
equivalents. It also illustrates adding snprintf_s_X support for new
format strings.

fpgad: correct instances of snprintf and strlen

---

libopae/src/bitstream.c
libopae/src/enum.c
libopae/src/reconf.c
libopae/src/sysfs.c
libopae/src/token_list.c
libopae/src/usrclk/user_clk_pgm_uclock.c

Changes:
- Replace strlen() with strlen_s()
- Replace snprintf () with snprintf_s_X ()

OPAE: Replace string functions with secure safe string

---

tools/mmlink/mm_debug_link_linux.cpp
tools/mmlink/mm_debug_link_linux.h

The read_mmr() function is used to obtain a pointer to a
memory-mapped IO address (void *) given an offset from the MMIO base.
In the previous implementation, callers were forced to cast the obtained pointer to a volatile type,
or else the optimization phases of the compiler produced invalid
code. This was observed as a regression test failure when the default
build type was changed to -DCMAKE_BUILD_TYPE=RelWithDebInfo.
The change converts read_mmr to a template function so that
no casting to volatile is required at the call site.

mmlink: fix read_mmr optimization issue

---

tools/mmlink/main.cpp

Changes:
- Set socket default IP address to 0.0.0.0 instead of loop back IP address 12.0.0.1

tools: MMlink set default IP address to zero

---

common/include/safe_string/safe_string.h
safe_string/snprintf_support.c
tools/mmlink/mmlink_connection.cpp
tools/mmlink/mmlink_server.cpp

These instances were identified by the new safe string checkers.

mmlink: fix instances of banned fn's

---

tools/mmlink/main.cpp

Changes:
- Set socket default IP address to 0.0.0.0 instead of loop back IP address 127.0.0.1

tools: MMlink set default IP address to zero (#180)

---

tools/fpgabist/dma/CMakeLists.txt

Cherrypick: The DMA tool in BIST needs to link against librt

Link against librt when building dma tool in BIST (#299)

---

ase/scripts/generate_ase_environment.py
platforms/platform_db/README.md
platforms/platform_db/discrete_pcie3.json
platforms/platform_db/intg_xeon.json
platforms/scripts/afu_platform_config

- Add mapping from physical platform name to ASE platforms in platform db.
- afu_platform_config writes ASE platform name to a file.
- Add the ability to set the default physical platform name in ASE using
an environment variable (OPAE_ASE_DEFAULT_PLATFORM).

Accept all Platform Interface Manager platform names in ASE configuration

---

tools/fpgainfo/fpgainfo

* fpgainfo: default log to /tmp + error handling
This changes fpgainfo to log to /tmp directory but also adds exception
handling in case the log file can't be opened. If that happens, it will
log to stderr.

fpgainfo: default log to /tmp + error handling

---

libopae/src/enum.c
libopae/src/properties.c
libopae/src/sysfs.c
libopae/src/token_list.c

Rename erroneous instances of device_id to device_instance for clarity.
The variables track an instance of the fpga device, not to be confused
with the PCIe DID field of the device.

libopae: rename local variable device_id

---

platforms/CMakeLists.txt
platforms/scripts/afu_synth_setup

- Specify hw/lib directory, not release, since there may not be a release yet.
- Remove "_std" in the name and use an environment variable to set the
hw/lib path.

Update afu_synth_setup to work with discrete build structure

---

tools/fpgabist/bist_dma.py
tools/fpgabist/bist_nlb3.py

For Fpgabist tool perform the read, write and throughput fpgadiag tests.
In addition add `__init__` function to the bist mode classes (dma & nlb3).

Add read and write fpgadiag tests to bist

---

platforms/platform_if/rtl/platform_shims/utils/quartus_ip/platform_utils_dc_fifo.sv
tools/fpgabist/fpgabist

For systems with multiple card must provide a bdf using the 'b', 'd' or 'f' flags.
When there is only one card on the system the tool will default to running on the only available fpga.

Bist behavior Run only one card

---

cmake/modules/packaging.cmake
tools/packager/CMakeLists.txt

- No longer depends on Unix shell commands
- No longer depends on zip program

Use Python to generate zipped Python executables

---

common/include/safe_string/safe_string.h
libopae/src/enum.c
libopae/src/sysfs.c
safe_string/snprintf_support.c

Fixes instances of snprintf and sscanf in libopae.

libopae: comply with new safe string checkers

---

ase/scripts/generate_ase_environment.py
platforms/platform_db/discrete_pcie3_hssi40.json
platforms/platform_if/rtl/platform_shims/utils/platform_utils_ccip_reg.sv

- Add a new stub for a platform with HSSI
- Teach ASE to find the physical platform using a mechanism identical to
Quartus builds.  The current FPGA thus matches the simulation environment.
- Update tags on RTL registers used for timing relaxation based on
experience with OpenCL.

Platform support changes:

---

ase/scripts/generate_ase_environment.py

Removing the embedded Linux command in ASE generate_ase_environment.py and replaced it with python commands. 
This change was done to make ASE porting to Windows possible.
Tested it with 01_hello_world sample.

ASE: Replacing Linux commands in ASE python script

---

ase/scripts/generate_ase_environment.py
libopae/src/reconf.c
libopae/src/usrclk/user_clk_pgm_uclock.c

Changes:
- Set to  refclk 1 when only refclk 1 is available
- Set to  refclk 0 when only refclk 0 is available
- Accept time specified by the low frequency clock when the high frequency clock isn't specified

OPAE: User PLL clock set to proper refclock  when only reference clock is is available

---

common/include/opae/cxx/.clang-format
libopae++/.clang-format

According to the clang-format documentation
clang-format will use a .clang-format file in a
file's closes parent directory (if found).
This adds two .clang-format config files that can be used to format C++ files using a style based on the
Google coding style.

opaec++: add .clang-format config file

---

tools/fpgabist/bist_common.py

When the fpgabist tries to do PR for certain systems, namely ones where the bus number contains a value a-f, fpgaconf cant take the input without the leading '0x'.
Bug fix to address this info.

Fix bus input for fpgaconf in bist

---

tests/CMakeLists.txt
tests/function/gtBuffer.cpp
tests/function/gtEnumerate.cpp
tests/function/gtEvent.cpp
tests/function/gtHostif.cpp
tests/function/gtMMIO.cpp
tests/function/gtOpenClose.cpp
tests/function/gtUmsg.cpp
tests/unit/gtEnumerate.cpp
tests/unit/gtOpen.cpp
tests/unit/gtOptionParser.cpp

Rename test case names based on the test case naming conventions.

Tests: Rename test case names

---

ase/Makefile
platforms/afu_top_ifc_db/ccip_std_afu_avalon_mm_legacy_wires.json
platforms/scripts/afu_synth_setup

- Stop building run.sh/clean.sh script wrappers in afu_synth_setup. They were a source of problems.
- Stop importing Stratix V HSSI/PCIe atoms in ASE. Not available on some platforms.

Various updates for discrete platform

---

tools/fpgabist/bist_common.py

This change was missed from internal repo.
Fpgabist input for bdf as string not int.

fpgabist input as str

---

CMakeLists.txt

/etc/ld.so.conf.d/ may have not been created yet. package include the rule "mkdir /etc/ld.so.conf.d" if directory does not exist.
so this patch fixes issue of RPM prerm script not finding opae-c.conf configuration file under /etc/ld.so.conf
JIRA ticket here:
https://jira01.devtools.intel.com/browse/OPAE-681?filter=-1

fix warning if opae.conf was not created (directory does not exist)

---

platforms/scripts/platmgr/emitcfg.py

This will make it possible to drive synthesis from the PIM decisions.  E.g., Quartus can detect
that HSSI is in use with:
[info exists platform_cfg::AFU_TOP_REQUIRES_HSSI_RAW_PR]

Emit Tcl with PIM configuration

---

platforms/platform_if/rtl/device_if/ccip_if_clock.sv
platforms/platform_if/rtl/device_if/device_if.vh
platforms/platform_if/rtl/platform_shims/platform_shim_avalon_mem_if.sv
platforms/platform_if/rtl/platform_shims/platform_shim_ccip.sv
platforms/platform_if/rtl/platform_shims/platform_shim_ccip_std_afu.sv
platforms/scripts/platmgr/emitcfg.py

- Clock can be any string that maps to an available clock.
- Export CCI-P clock with `PLATFORM_PARAM_CCI_P_CLOCK.  The previous method
using a Verilog module wasn't flexible enough to handle all the possible
clocks.
- Update the macro writing rules in afu_platform_config to deal with more
possible illegal macro characters.

Make it possible to request any clock for CCI-P & local memory

---

.github/CODEOWNERS

Add references to designated maintainers for individual components of
the OPAE SDK.
See also https://github.com/blog/2392-introducing-code-owners.

Add maintainers

---

ase/scripts/generate_ase_environment.py
platforms/scripts/afu_synth_setup

- First check BBS_LIB_PATH (BBS hw/lib)
- Next check OPAE_PLATFORM_ROOT (top-level of a release)
- Also fixed: print a sensible error on old Python

Implement hw/lib search order to which we agreed for HW releases:

---

platforms/platform_if/rtl/platform_shims/platform_shim_ccip_std_afu.sv
platforms/scripts/afu_synth_setup
platforms/scripts/rtl_src_config

- Allow IPX files in rtl_src_config.
- Generate a master components.ipx, pointing to the sub-IPX files, in the Quartus build.

Handle Qsys IPX file hierarchy

---

cmake/modules/test_config.cmake
tests/CMakeLists.txt
tests/unit/gtAnyValue.cpp
tools/c++utils/any_value.h

Add `any_value` class to replace use of boost::any.
This class was developed by looking at some online references to tips on
how to to implement the any functionality in boost.
This is a step in removing dependency on boost. If boost libraries are
needed in the future, they can be added then.

c++utils: add `any_value` class

---

CMakeLists.txt
cmake/modules/FindPythonPackage.cmake

Check for Python module, `virtualenv`, on system.
If found, call virtualenv to install a virtual Python env. in the build directory.
This is in preparation for packaging python tools as universal wheel
files and installing them in the virtual env. during the development and testing phase.

cmake: install python virtual env. in build dir.

---

CMakeLists.txt
tools/fpgabist/README
tools/fpgabist/bist/CMakeLists.txt
tools/fpgabist/bist/README
tools/fpgabist/bist/bist_afu.c
tools/fpgabist/bist_app.py
tools/fpgabist/bist_common.py
tools/fpgabist/fpgabist

The fpgabist tool will now be able to use the bist_afu as one of the modes.  
There will be additional development on the application to remove warnings.

Adding bist afu support to the fpgabist tool

---

cmake/modules/FindPythonPackage.cmake

Add find_package(PythonInter...) to the beginning of the file
(outside of the macro) so that cmake finds the Python interpreter
and uses it when checking for existence of a module.

modify FindPythonPackage to use Python found

---

tools/packager/CMakeLists.txt
tools/packager/packager.py

The existing packager.py will run as usual.  The only difference will be that when invoked from the source tree (i.e., `python ./tools/packager/packager.py version`) it prints:
`Intel OPAE FPGA Packager: version @INTEL_FPGA_API_VERSION@`
After a cmake, the installed version will print:
`Intel OPAE FPGA Packager: version 0.13.0`
I hope this satisfies all the concerns brought up in the last 2 pull requests.  Once we decide the final solution, we can change this (if necessary).
Thanks.

Add version command by cmake replacement

---

doc/src/install_guide/installation_guide.md

Update the install guide with details of how to manually extract the
driver source files from an RPM. Without Debian package support,
some users are forced to use this method on Debian-based systems.

docs: add RPM extraction to install guide

---

common/include/opae/cxx/core/handle.h
libopae++/samples/hello_fpga-1.cpp
libopae++/samples/simple_example.cpp
libopae++/src/handle.cpp
scripts/test-codingstyle.sh
scripts/test-gtapi-mock-drv.sh
tests/unit/gtCxxBuffer.cpp
tests/unit/gtCxxEvents.cpp
tests/unit/gtCxxOpenClose.cpp
tests/unit/gtCxxReset.cpp

* Rename csr read/write functions in `handle` class to read_csr<T> and
write_csr<T> to be more explicit in the operation and specify that the
functions are operating on CSRs. This is a template function where the
template argument specifies the register size (uint32_t or uint64_t for
32-bit or 64-bit respectively).
* Update samples to use updated API functions.

c++core: rename read/write to read_csr/write_csr

---

platforms/platform_db/discrete_pcie3_hssi40.json
platforms/platform_db/platform_defaults.json
platforms/platform_db/platform_defaults/defaults_ccip.json
platforms/platform_db/platform_defaults/defaults_clocks.json
platforms/platform_if/rtl/device_cfg/ccip_cfg_pkg.sv

It was configured in the wrong place (the CCI-P interface class).

Move pClk frequency setting to the clocks class.

---

tools/fpgainfo/sysfs.py

Add other sysfs nodes to the list of entries to clear when clearing
errors for fme.
To do this, the errors_feature was refactored to use a list of two
element tuples for the error nodes to clear. The first entry in the
tuple is the node to read from, the second is the node to write to for
clearing the errors.
Both fme_errors and port_errors classes were updated to specify their
respective tuples to clear.

fpgainfo: fix clear errors function

---

libopae/src/close.c
libopae/src/wsid_list.c
libopae/src/wsid_list_int.h

Parameterize wsid_cleanup() with an optional callback so that work can
be done on each mapping when the list is being destroyed. Add call to
destroy handle::mmio_root in fpgaClose().

libopae: free MMIO mappings on close

---

scripts/test-gtapi-mock-drv.sh

Enabled ctest output on test failure to assist in debugging.

Enabled ctest output on failure.

---

tests/function/gtOpenClose.cpp

Test that fpgaClose() automatically unmaps any mapped MMIO space.

test: add test for auto-release of MMIO

---

common/include/opae/cxx/core/handle.h
libopae++/src/handle.cpp

This allows relying on the lazy mapping performed by the
fpgaReadMMIOxx() and fpgaWriteMMIOxx() accessors, enabling
access to any of the supported MMIO spaces associated with
the handle. Parameterize member fn mmio_ptr() with a csr_space
argument.

libopaecxx: remove csr_space from handle::open

---

tools/fpgadiag/nlb0.cpp
tools/fpgadiag/nlb3.cpp
tools/fpgadiag/nlb7.cpp

Set the `frequency_` member variable for nlb0, nlb3, and nlb7 to the
value in the `freq` option. Without this, the frequency used for
bandwitdth calculations was always 400 MHz (ignoring user input).

fpgadiag: fix "freq" option for bw calc.

---

tests/CMakeLists.txt
tests/function/gtUmsg.cpp

The previous gtest filter defined in tests/CMakeLists.txt caused the filter to be empty so none of the tests would actually be run for the target test_open_common_mock_drv. When they were actually running, four of the tests would fail for that target. This fixes the filter, disables reconfiguration so LibopaecOpenFCommonMOCK.02 can pass, and disables the three tests (LibopaecOpenFCommonMOCK.03, LibopaecOpenFCommonMOCKHW.06, LibopaecOpenFCommonMOCK.open_drv_09) that do not work with the mock driver.

Fixed test_open_common_mock_drv test target.

---

ase/rtl/ase_pkg.sv
ase/rtl/ccip_emulator.sv
ase/rtl/outoforder_wrf_channel.sv
ase/rtl/platform.vh

- Always use outoforder_wrf_channel.
- Tweak buffer sizes to reduce the number of buffered requests, more like HW.
- Add support for interrupt requests through outoforder_wrf_channel.
- Remove Verilog preprocessor macros for read vs. write in outoforder_wrf_channel.
They were always defined, so weren't controlling anything.

Generate CCI-P almost full signals on PCIe-only systems.

---

tests/mock.c

Write an NLB0 AFU DFH and GUID to the beginning of the AFU CSR space
when the Port device file is opened in anticipation of the AFU CSR space
being mapped for MMIO test cases.

mock: write an AFU header on port open

---

tools/fpgadiag/nlb.h
tools/fpgadiag/nlb0.cpp
tools/fpgadiag/nlb3.cpp

The pClock frequency is static per device id but the getting the device
id from the properties is not implemented right now.
As a temporary workaround, the frequency will be encoded in status2
register (0x0170). Read the frequency from here and set it frequency_
member variable to that if it is non-zero.

fpgadiag: get pclock freq from nlb register

---

platforms/afu_top_ifc_db/README_AFU.md
platforms/afu_top_ifc_db/ccip_std_afu.sv.template
platforms/afu_top_ifc_db/ccip_std_afu_avalon_mm.sv.template
platforms/afu_top_ifc_db/ccip_std_afu_avalon_mm_legacy_wires.sv.template
platforms/scripts/afu_platform_config
tools/packager/afu.py
tools/packager/afu_json_mgr.py
tools/packager/schema/afu_schema_v01.json
tools/packager/schema/afu_template.json

Using "name" was a source of confusion every time I explained the PIM's AFU
JSON.  They would see "afu-top-interface:name" and think that's the module
name, which was a reasonable assumption.  It isn't.  Instead, it is the class
of the interface, defining the ports and not the module name.
For compatibility, the legacy key "name" is accepted as a synonym.

Change AFU interface type's key from "name" to "class".

---

platforms/afu_top_ifc_db/README.md
platforms/afu_top_ifc_db/README_AFU.md
platforms/platform_db/discrete_pcie3.json
platforms/platform_db/platform_defaults/defaults_ccip.json
platforms/platform_db/platform_defaults/defaults_local_memory.json
platforms/platform_if/rtl/device_cfg/ccip_cfg_pkg.sv
platforms/platform_if/rtl/platform_shims/README.md
platforms/platform_if/rtl/platform_shims/platform_shim_avalon_mem_if.sv
platforms/platform_if/rtl/platform_shims/platform_shim_ccip.sv
platforms/scripts/afu_platform_config
platforms/scripts/platmgr/emitcfg.py
platforms/scripts/platmgr/jsondb.py

It was too confusing and, we have decided, of little value.  Instead, interface
classes will have consistent register requirements across platforms.  Any extra
buffering required at the PR boundary will be handled by supplied libraries.
Renamed "add-extra-timing-reg-stages" to simply "add-timing-reg-stages", since
that's now exactly what the code does.

The PIM no longer offers auto mode for extra-timing-reg-stages.

---

tools/base/fpgad/ap_event.c

gcc 7.1.0 issues the following build failures due to
-Werror=maybe-uninitialized.
opae-sdk/tools/base/fpgad/ap_event.c: In function ‘apevent_thread’:
opae-sdk/tools/base/fpgad/ap_event.c:121:12: error: ‘apevt_socket2.pwr_last_state’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
} else if (event->pwr_last_state != 0 && pwr_state == 0) {
^
opae-sdk/tools/base/fpgad/ap_event.c:138:23: note: ‘apevt_socket2.pwr_last_state’ was declared here
struct fpga_ap_event apevt_socket2;
^~~~~~~~~~~~~
opae-sdk/tools/base/fpgad/ap_event.c:100:5: error: ‘apevt_socket2.ap2_last_event’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
if (event->ap2_last_event != 1 && ap2_event == 1) {
^
opae-sdk/tools/base/fpgad/ap_event.c:138:23: note: …

fpgad/ap_event: Fix build failure due to -Werror=maybe-uninitialized

---

CMakeLists.txt

platforms directory was inadvertanly removed from cmake processing.
This adds it back.

Add platforms directory

---

cmake/modules/packaging.cmake

When trying to configure 'packager' tool, which relies on 'bin'
directory, Python couldn't write file, because directory doesn't exist
at this time.
We need to ensure, that directory is already there, before attempting
tool configuration.

Ensure that 'bin' directory exists

---

ase/api/CMakeLists.txt
ase/api/src/version.c

Fix ASE implementation of fpgaGetOPAECBuildString and fpgaGetOPAECVersionString
Update ase/api/CMakeLists.txt
(cherry picked from commit 2d63c90e9a99007f82bf51390e13d48a630c66c9)

Add version.c to ase/api/CMakeLists.txt

---

tools/extra/fpgadiag/CMakeLists.txt

The CMakeLists.txt for fpgadiag (and cmdq3) currently doesn't use a CMake
package finder to find numa and instead only looks for the library.
If it finds the library but the development files (headers) aren't present
on the system, the build can run into issues trying to include numa.h.
The PR makes it a CMake option to turn on numa support in cmdq3.
_TODO: Use (and maybe develop) a numa package finder to check for numa.h_

make numa support in cmdq3 optional in cmake

---

common/include/opae/cxx/core/pvalue.h
libopae++/src/dma_buffer.cpp
libopae++/src/events.cpp
libopae++/src/properties.cpp
libopae++/src/token.cpp
tests/unit/gtCxxProperties.cpp

Update the following classes to use the `ASSERT_FPGA_OK` macro (which will throw exception when fpga_result code is not `FPGA_OK`):
* pvalue
* properties
* token
* dma_buffer
* events

make use of opae c++ exceptions

---

platforms/scripts/afu_synth_setup

Now that platform_db libraries may be in release hw/lib trees, afu_platform_config
must be able to find the library.  Normally it uses $OPAE_PLATFORM_ROOT.  When
the root is not defined but --lib is passed to afu_synth_setup the db search
path must be updated.

Update platform db search path when --lib is passed to afu_synth_setup

---

platforms/platform_if/par/platform_if_addenda.qsf
platforms/scripts/platmgr/emitcfg.py

Replaced with macros defined in platform_db entries.

Remove PLATFORM_NAME macro creation in PIM's Quartus script

---

tools/extra/hssi/e100.cpp

This add several workarounds for running the `clear` command from hssi_loopback.
Mainly, it needs to start the monitor as part of the clear or before running a test as this will clear some other counters not accessible from the mac cntr CSR

hssi_loopback fixes for clear/status commands

---

tools/extra/libopae++/property_map.h

The parameter is unused in the implementation of the function

remove parameter name from property_map::set

---

tools/extra/c++utils/any_value.h

Fix the assignment operator in any_value to invalidate the other `value_` member.

fix any_value

---

tools/extra/c++utils/option_parser.cpp

Add template specializations for options that are or type `float` and `double`
when parsing from command line arguments.

c++utils: add double/float support in opt parsing

---

platforms/scripts/CMakeLists.txt
platforms/scripts/afu_platform_info
platforms/scripts/afu_synth_setup
platforms/scripts/rtl_src_config

Some sources, such as Qsys-generated RTL, are specific to the FPGA family or major version of Quartus.
- Add an FPGA family property to the platform database.
- Add automatically generated environment variables to rtl_src_config that can be used in source paths.

Add mechanisms for selecting RTL sources based on FPGA family and Quartus versions

---

tools/extra/c++utils/utils.cpp

Fix `ltrim` and `rtrim` functions as they were not working as expected

c++utils: fix trim functions

---

common/include/opae/enum.h

Fix the doxygen for parameter 'filters'. The docs previously mentioned
that passing NULL for 'filters' would return all fpga objects. The
correct query-all method is to pass an initialized but empty
fpga_properties object.

libopae: fix fpgaEnumerate() doxygen bug

---

ase/rtl/ase_top.sv
platforms/platform_if/rtl/platform_shims/platform_shim_ccip_std_afu.sv
platforms/platform_if/rtl/platform_shims/utils/avalon_mem_if_async_shim.sv
platforms/platform_if/rtl/platform_shims/utils/avalon_mem_if_connect.sv
platforms/platform_if/rtl/platform_shims/utils/avalon_mem_if_reg.sv

Bank number is used only for debugging, but now that it is a wire instead of a parameter
it should be passed from instance to instance using combination assignments.

Pass the local memory bank number as a normal signal.

---

cmake/modules/test_config.cmake
common/include/opae/cxx/core/version.h
libopae++/CMakeLists.txt
libopae++/src/version.cpp
tests/CMakeLists.txt
tests/unit/gtCxxVersion.cpp

This adds three static functions in a `version` class under `opae::fpga::types`
namespace.

opaecxx: Add version API

---

tools/extra/hssi/config_app.cpp

Remove 0x38/0x39 from max retimer read/write address.
The `dump` command uses this when dumping retimer registers and was dumping too much.

hssi: set max retimer register to 0x36/0x37

---

.travis.yml
scripts/build-documentation.sh
scripts/push-documentation.sh

Right now, the decision to upload documentation to opae.github.io is based on whether the commit is tagged or not. This will not work for us since that will force an upload of documentation on any of the RC tags that we have before the actual release. Also, since the last RC tag will be an official release, there is no way to differentiate the RC tags with the final release tag and hence no way to detect when to upload the documentation automatically.
So the current approach is, Travis will run a daily build on master, that will update the latest documentation on opae.github.io. As for the release, whenever we are ready to release, I will be running the scripts locally in order to build the release tag and upload the documentation for that release in a separate directory on opae.githb.io.

Resolve issues with documentation upload

---

common/include/opae/cxx/core/dma_buffer.h
common/include/opae/cxx/core/events.h
common/include/opae/cxx/core/except.h
common/include/opae/cxx/core/handle.h
common/include/opae/cxx/core/properties.h
common/include/opae/cxx/core/token.h
common/include/opae/cxx/core/version.h
libopae++/samples/hello_fpga-1.cpp
libopae++/samples/simple_example.cpp
libopae++/src/events.cpp
libopae++/src/except.cpp
libopae++/src/properties.cpp
libopae++/src/token.cpp
libopae++/src/version.cpp
scripts/test-codingstyle.sh

This PR touches a lot of files but is only about code formatting.
I ran clang-format on the relevant source directories to make this. 
_TODO: Add coding style check to CI`_

Apply clang-format to c++ code

---

ase/scripts/generate_ase_environment.py
platforms/scripts/platmgr/emitcfg.py

This eliminates the last significant difference between the ASE configuration
provided in OPAE and the ASE configuration shipped with discrete cards.  It was
a source of confusion in documentation, since we generally advised the use of
afu_sim_setup, which invokes generate_ase_environment.py.  For AFUs with Qsys,
we suggested a different script.  All shipped AFUs can now use the same
afu_sim_setup for configuration.

 Compile Qsys when configuring ASE simulation.

---

common/include/opae/cxx/core/shared_buffer.h
libopae++/CMakeLists.txt
libopae++/samples/hello_fpga-1.cpp
libopae++/src/shared_buffer.cpp
tests/unit/gtCxxBuffer.cpp

To avoid confusion with other DMA data structures, this renames the `dma_buffer` class to `shared_buffer`

c++core: Rename `dma_buffer` to `shared_buffer`

---

common/include/opae/event.h

Change obkect to object in doxygen markup for `fpgaGetOSObjectFromEventHandle`

Fix typo in doxygen markup

---

common/include/opae/cxx/core/handle.h
libopae++/src/handle.cpp

The `fpga_handle` data stucture makes a shallow copy of the token
used when calling fpgaOpen. This change makes a clone of the token
before calling `fpgaOpen` and saves it in the C++ handle object.
This will ensure the lifetime of the token structure used to open
will be as long as the handle itself.

c++core: clone token when creating a new handle

---

doc/src/ase_userguide/ase_userguide.md

This pull request:
* Removes Unicode characters (non-UTF8 aposthrophes and hyphens, so now all source code is UTF8)
* Removes Windows line ending terminations (now it uses Unix style)
* Fixes the ..note:: Restructured Text blocks (..note:: should be placed inside ```eval_rst). This eliminates warnings about ..note:: blocks when building documentation using Sphinx.
Document content is unmodified.

Fix ASE userguide format

---

common/include/opae/cxx/core/events.h
libopae++/src/events.cpp
tests/unit/gtCxxEvents.cpp

* Add a call to `fpgaGetOSObjectFromEventHandle` in event factory fn
* Store that os object in the event object
* Return that os object when calling `os_object` fn from an event object

opaecxx: Add os_object API to event class

---

ase/rtl/ase_top.sv
ase/rtl/device_models/dcp_emif_model_advanced/emif_ddr4.v
ase/rtl/device_models/dcp_emif_model_basic/emif_ddr4.v
platforms/platform_if/rtl/device_if/avalon_mem_if.vh
platforms/scripts/platmgr/emitcfg.py

- ASE models whatever width the platform or AFU configure.
- AFU JSON may now request any local memory data or address width that is no
larger than the platform's memory interface.

Support local memory widths that aren't 512 bits

---

common/include/opae/cxx/core/handle.h
libopae++/src/handle.cpp

This add the reconfigure function to the handle class to enable reconfiguration using the C++ object model.
This will only be valid if the handle is from an enumerating/opening a token of type FPGA_ACCELERATOR.

c++core: Add reconfigure API to cxx-core

---

libopae/src/enum.c

Move the code that looks at filters passed in to `fpgaEnumerate`
to determine is reading afu_id is required.

Refactor code that examines filters

---

ase/CMakeLists.txt
ase/scripts/with_ase

with_ase loads the ASE version of libopae-c, turning software compiled for use
with hardware into a simulation run.

Add with_ase (#430)

---

ase/api/src/enum.c
ase/api/src/open.c
ase/sw/app_backend.c
ase/sw/ase_common.h
ase/sw/ase_ops.c
ase/sw/ase_strings.c
ase/sw/error_report.c
ase/sw/ipc_mgmt_ops.c
ase/sw/mem_model.c
ase/sw/protocol_backend.c

Added the safe version memset in ase_strings.c. This should fix the klocwork issues related to memset() in ASE. 
DCP regression tests passed at:
http://sw-pert.altera.com/pert/pert.php?test_run_id=2402072

ASE Klocwork fix for using safe memset() function

---

platforms/platform_db/platform_defaults/defaults_ccip.json
platforms/platform_db/platform_defaults/defaults_local_memory.json
platforms/platform_if/par/platform_if_addenda.qsf
platforms/platform_if/rtl/platform_shims/platform_shim_avalon_mem_if.sv
platforms/platform_if/rtl/platform_shims/platform_shim_ccip.sv
platforms/platform_if/rtl/platform_shims/platform_shim_ccip_std_afu.sv
platforms/platform_if/rtl/platform_shims/utils/avalon_mem_if_async_shim.sv
platforms/platform_if/rtl/platform_shims/utils/avalon_mem_if_reg_simple.sv
platforms/platform_if/rtl/platform_shims/utils/platform_utils_ccip_async_shim.sv
platforms/platform_if/rtl/platform_shims/utils/quartus_ip/README
platforms/platform_if/rtl/platform_shims/utils/quartus_ip/gen_platform_ip.sh
platforms/platform_if/rtl/platform_shims/utils/quartus_ip/platform_utils_avalon_mm_clock_crossing_bridge.v
platforms/platform_if/sim/platform_if_addenda.txt

Take advantage of the clock crossing FIFO when the PIM is inserting both a clock crossing and pipeline stages for timing on both local memory or CCI-P signals. By leaving extra space in the clock crossing FIFO, local memory's Avalon waitrequest can be turned into something closer to an almost full protocol. The FIFO can consume all in-flight requests from the pipeline without losing them.
For CCI-P, leaving extra space in the clock crossing FIFO allows for longer timing pipelines without affecting the legal count of requests following almost full in the AFU.

Optimize timing register pipelines when clock crossings are also present

---

tests/function/gtCxxBuffer.cpp

This is done so that the allocated memory is page-aligned

test: Change malloc to align_alloc

---

common/include/opae/cxx/core/properties.h
common/include/opae/cxx/core/token.h
libopae++/samples/hello_fpga-1.cpp
libopae++/src/properties.cpp
libopae++/src/token.cpp
tests/function/gtCxxBuffer.cpp
tests/function/gtCxxEvents.cpp
tests/function/gtCxxMMIO.cpp
tests/function/gtCxxOpenClose.cpp
tests/function/gtCxxProperties.cpp
tests/function/gtCxxReset.cpp

* Make the default properties contructor private and replaces construction
of a properties objtype to a factory function called `properties::get()`.
* Add overloaded `properties::get()` functions to create properties
using one property (like object type or guid).
* delete the copy contructor and assignment operator of properties class.
The goal of this change is to
* Align the the properties C++ API with the other classes in the cxx-core library.
* Elimate the need to copy properties objects by instead using a shared_ptr
* Elimate the need to wrap properties creation in the upcoming Python bindings
TODO: Add a properties::clone() function

c++core: make properties c'tor private

---

cmake/modules/FindPythonPackage.cmake

This is so that callers of this macro can check if a module is installed or not.

add cmake vars to indicate if py pkgs found

---

platforms/scripts/platmgr/emitcfg.py

This will allow us to import Quartus objects that are Quartus/platform
dependent.

Emit platform configuration for ASE is Makefile/CMake includes.

---

cmake/modules/test_config.cmake
common/include/opae/cxx/core/errors.h
common/include/opae/cxx/core/properties.h
libopae++/CMakeLists.txt
libopae++/src/errors.cpp
libopae++/src/properties.cpp
tests/CMakeLists.txt
tests/function/gtCxxErrors.cpp
tests/function/gtCxxProperties.cpp

This adds the errors class in opae::fpga::types namespace which
wraps the errors API in the OPAE C API.

cxx-core: Add error API for opae-cxx-core

---

ase/api/src/error.c
libopae/src/error.c

Add the \_\_FPGA_API\_\_ macro to make the error API functions visible when linking
with other modules.

add the default visibility to error API

---

pyopae/opae.cpp
pyopae/pyproperties.cpp
pyopae/pyproperties.h

Add a function, `pytuple_to_fpga_version`, that can be used to covert a Python
tuple object into an fpga_version object.
Use this function when setting the bbs_version property

pyopae: fix bbs_version property setter method

---

.travis.yml
scripts/coverage-gtapi-mock-drv.sh

Run mock driver tests to generate coverage.
If the reviewers can suggest possible ways to add more test to get better numbers that would be great. This PR right essentially just enables coverage reporting via coveralls.

Enable coveralls for coverage reporting

---

tools/extra/pac/fpgabist/bist_nlb3.py

Adding `B` parameter for fpgadiag, for use in fpgabist tool.
Complies with the CLI changes in PR:
**https://github.com/OPAE/opae-sdk/pull/483**

Make fix for fpgadiag CLI change in fpgabist

---

libopae/src/usrclk/user_clk_pgm_uclock.c
tests/unit/gtUsrclk.cpp

Fix bug in fpac_GetErrMsg() and associated unit test.

libopae-c: fix usrclk bug

---

.travis.yml
CMakeLists.txt
cmake/modules/FindPythonPackage.cmake
cmake/modules/create_python_dist.cmake
pyopae/CMakeLists.txt
pyopae/test_pyopae.py
scripts/build-documentation.sh
scripts/coverage-gtapi-mock-drv.sh
scripts/test-gtapi-mock-drv.sh
tests/CMakeLists.txt

Temporarily disable building with setup.py and instead build the OPAE Python
bindings directly with cmake. This is done to test building with different
flags, especially building with coverage turned on and getting test coverage
info.
Add the required Python version as a cmake variable. This can later be used for
building the Python bindings with different Python versions.
This assumes that pybind11 and nose2 Python modules are installed in order to
get include paths to pybind11 and also to execute tests.
The travis jobs have been updated to install these modules.
Add a ctest in tests/CMakeLists.txt to call nose2 with the tests.
Add a "finish" function in the coverage script and move the processing of
coverage data into this. Change the script to call finish when exiting so that
this is …

pyopae: Change build system

---

tools/extra/integrated/hssi/e100.cpp

Delay is necessary because of lack of HW synchronization

Add another delay in clear_status command

---

tools/base/fpgad/ap6.c

Changes:
-Bitsteam buffer freed twice in case of corrupted bitstream

tools:fpgad fix double free memory address

---

cmake/modules/test_config.cmake
libopae/src/event.c
tests/common_test.cpp
tests/common_test.h
tests/function/gtEvent.cpp
tests/mock.c
tests/unit/gtReconf.cpp

Fix bug in test reconf_gbs_01.
Add conditional interrupt ioctl support to mock, controlled
by mock_enable_irq().
Fix bug in send_uafu_event_request().

mock: add IRQ support

---

tools/base/fpgad/ap_event.c

Initialize local variables in poll_ap_event() so that errant event
status is no longer reported.
Fix typos in printed strings.

fpgad: fix uninitialized variable bug

---

pyopae/pyhandle.cpp
pyopae/test_pyopae.py

Because the Python API is slightly different in Python 3, the logic for
converting a file object from Python to a FILE* needs to be updated to account
for the Python 3 API (which includes `PyObject_AsFileDescriptor` function).
Also, the tests need to be modified to account for some differences in Python
functions/types in Python 3 vs Python 2.7.

pyopae: add Python3 support

---

pyopae/CMakeLists.txt
pyopae/opae.cpp
pyopae/pycontext.cpp
pyopae/pycontext.h
pyopae/pyhandle.cpp
pyopae/pyshared_buffer.cpp
pyopae/test_pyopae.py

Add a singleton class, `buffer_registry` which is designed to be called by the
context manager enter function to register a handle. It is then called again by
the shared_buffer allocate function to associate the resulting buffer with the
handle. The context manager exit function should then call the deregister
function in the buffer_registry to release buffers associated with a handle.

pyopae: Add context manager helper class

---

doc/sphinx/CMakeLists.txt
doc/src/fpga_api/fpga_python_api.rst
pyopae/opae/fpga/__init__.py

* Change calling of sphinx to include PYTHONPATH env. variable.
This is done to allow importing of the generated Python module in the build
directory
* Update the sphinx documentation page for the Python API
* Introduce `error` into the fpga package initialization ( __init__.py)

 pyopae: Update to documentation

---

CMakeLists.txt
pyopae/opae.cpp
pyopae/pyshared_buffer.cpp
pyopae/pyshared_buffer.h
pyopae/test_pyopae.py

This implements the shared_buffer __setitem__ protocol method.
NOTE: This currently only works on the argument type being of type `int`

pyopae: implement setitem in shared_buffer

---

pyopae/CMakeLists.txt
pyopae/MANIFEST.in

The MANIFEST.in template file is used by distutils as an explicit list of files
to include in the source distribution.
Without this, distutils will only include the source (.cpp) files in the source
distribution.

pyopae: Add MANIFEST.in template for setup.py

---

pyopae/setup.py

Installation from package will fail without compiling this as this file
implements functions needed for context management.

pyopae: add pycontext to setup.py

---

tools/base/fpgaconf/fpgaconf.c

Changing those options back to lowercase as they follow convention for those
options.

fpgaconf: revert -V and -N to -v and -n

---

tools/base/fpgaconf/fpgaconf.c

The previous commit that reverted the casing to these options missed the switch cases for them so the options would always return invalid cmd. This fixes it.

Fixed fpgaconf verbose and dry-run cmd options.

---

tools/extra/integrated/hssi/e100.cpp

Implment e100::assign method so that it instantiates an i2c instance in 2-byte
byte-address mode as the i2c controller used for AK uses 2 bytes for the byte
address field.
Also update the copyright text for the e100.cpp file.

hssi: override `assign` fn to cfg i2c

---

libopae/CMakeLists.txt
libopae/src/init.c
libopae/src/log_int.h
libopae/src/token_list.c
libopae/src/token_list_int.h

Move log.c to init.c.
Add fpga_init() as a generalized ctor and fpga_release() as a
generalized dtor.
Call token_cleanup() from fpga_release().
Fix list walk bug in token_cleanup().
Simplify logger implementation.

libopae-c: add generalized ctor and dtor

---

CMakeLists.txt

Currently coverage.cmake is not included in the source tarball which results in an error from ase_add_dpic.cmake which includes this file while building. This change removes coverage.cmake from the excluded files.

Include coverage.cmake in source tarball

---

pyopae/opae.cpp
pyopae/pyproperties.cpp
pyopae/pyproperties.h
pyopae/test_pyopae.py

* Add device_id property to Python API
* Reword some of the doc strings
* Add test for device_id property

pyopae: add device_id property to Python API (#562)

---

common/include/opae/properties.h
libopae/src/enum.c
libopae/src/properties.c
libopae/src/properties_int.h
libopae/src/sysfs.c
libopae/src/sysfs_int.h
libopae/src/types_int.h
tests/function/gtEnumerate.cpp
tests/unit/gtProperties_base.cpp

Add the PCI segment portion of a PCI address as a queryable property.

libopae-c: add PCI segment as a property

---

ase/sw/protocol_backend.c

* ASE: null pointer checking before dereference

ASE: Null pointer checking before dereference (#569)

---

tests/mock.c

safestr does not currently include strncat_s so this changes mock.c to
use strcat_s instead.

mock: change use of strncat_s to strcat_s

---

common/include/opae/sys.h
tests/mock.c

Add six APIs for reading and writing from/to an object in an FPGA
resource. The objects are identified by a string key.
For Linux, this is equivalent to reading/writing to sysfs
files with 'key' as a path relative to the resource directory in sysfs.
For each operation (read, write), three functions are defined.
* One for operating on a 32-bit value
* One for operating a 64-bit value
* One for operating on a sequence of bytes

Add generic APIs for reading/writing objects

---

tests/CMakeLists.txt
tests/fpgamock.c

Add fpgamock.c and build it into an executable, fpgamock.
The purpose of this is simply to test that building mock.c into an
executable will result in the functions defined in mock.c being called.
This has been tested in the debugger and I was able to step into
functions in mock.c.
The idea is that this will morph into the gtest entry point for unit tests.

mock: Add fpgamock.c (to test mock in an exe)

---

libopae/CMakeLists.txt
libopae/src/sys.c
scripts/coverage-gtapi-mock-drv.sh
scripts/test-gtapi-mock-drv.sh
tests/CMakeLists.txt
tests/gtunit-main.cpp
tests/unit/gtsys.cpp

Implment the functions for the fpgaObject API for reading/writing from
generic resource objects.
On Linux, this translates to reading/writing sysfs files relative to the
resource's sysfs path rooted at:
/sys/class/fpga/intel-fpga-dev.\d/intel-fpga-(fme|port).\d
This also adds a unit test executable that compiles in mock.c.
TODO:
* Implement the (Read|Write)Bytes functions
* Add more unit tests

Add sys.c (for generic sysfs operations)

---

tools/extra/ras/main.c

Strings were moved to other structures but the old instances remained.
New C++ compilers trigger errors on the unused strings.

Remove old RAS error strings.

---

common/include/opae/sysobject.h
libopae/src/sysfs.c
libopae/src/sysfs_int.h
libopae/src/sysobject.c
scripts/coverage-gtapi-mock-drv.sh
scripts/test-gtapi-mock-drv.sh
tests/CMakeLists.txt
tests/unit/gtsysfs.cpp

* Remote 32-bit sysfs write operations
Generic 32-bit sysfs write operations are not supported yet.
The kernel documentation for sysfs recommends reading entire
contents of a sysfs file, modifying it with the intended bytes, and then
writing back the buffer. Rather that implementing that for 32-bit
objects, this removes this operation for now.
* Rename mock unit test executable

Remove 32-bit sysfs write operations

---

ase/sw/ase_common.h
ase/sw/protocol_backend.c

Accidently enabled the debug message printing for shared memory buffers.

ASE: Disabled some debug messages in non-debug mode

---

platforms/scripts/platmgr/emitcfg.py

The value is derived from the fpga-family encoded in the platform
database and may be passed to megafunctions as "intended_device_family"
to get proper simulated semantics for a target architecture.

Add PLATFORM_INTENDED_DEVICE_FAMILY to generated platform configuration.

---

libopae/src/buffer.c
scripts/cover.sh
testing/CMakeLists.txt
testing/mock/test_system.cpp
testing/mock/test_system.h
testing/unit/munit-buffer-c.cpp
testing/unit/munit-enum-c.cpp

* Make buffer_allocate and buffer_release non-static so that they may be
called from a test if needed
* Put test_system and friends inside opae::testing namespace
* Add buffer_prepare parameterized tests (still need to add negative
tests)

Add buffer unit tests

---

testing/mock/test_system.cpp
testing/mock/test_system.h
testing/mock/test_utils.h

* Add sysclass path (/sys/class/fpga/intel-...) to c'tor
* Add device_id to c'tor
* Add accessor methods to get the values mentioned above
* Change the ioctl function to be virtual with the default
implementation throwing an exception if called
* Change the test_system::open call to figure out if the file being
opened is a driver attribute or a device file and use the appropriate
c'tor for creating the mock device
* Add a regex class in test_utils.h that wraps the POSIX.2 regex API

Update mock device object model

---

testing/mock/CMakeLists.txt
testing/mock/ioctl_handlers.cpp
testing/mock/test_system.cpp
testing/mock/test_system.h

Add `test_system::register_ioctl_handler` function which registers a
ioctl handler function using the request code.
Add `ioctl_handlers.cpp` which defines a macro to register default
handlers. These deault handlers simply validate the va_arg structure
with the type used in the macro.

Add ability to register ioctl handlers

---

testing/mock/test_system.h

The dummy IOCTL handler allows registering a templated version of the
dummy_ioctl function similar to the following:
```C++
test_system::instance()->register_ioctl_handler(
0x1234, dummy_ioctl<-1, EINVAL>);
```

Add dummy IOCTL handler template function

---

ase/CMakeLists.txt
ase/scripts/afu_sim_setup

The meaning of ASE_SHARE_DIR changed in commit 575fb262, which broke
afu_sim_setup's ability to find the installed ASE share tree.
This fixes issue #631

Fix incorrect recording of ASE installation path

---

ase/CMakeLists.txt
ase/scripts/afu_sim_setup

The meaning of ASE_SHARE_DIR changed in commit 575fb262, which broke
afu_sim_setup's ability to find the installed ASE share tree.

Fix incorrect recording of ASE installation path (#648)

---

testing/CMakeLists.txt
testing/mock/test_system.cpp
testing/mock/test_system.h
testing/xfpga/test_token_list_c.cpp

Add token_list unit tests in xfpga testing.
Implement malloc in test_system.cpp  to check for a flag for returning
null. If the flag is set to true, it will reset it to false and return
null. The expected use case is calling test_system::invalidate_malloc()
to set the flag to true before calling a function that calls malloc.
This allows for negative testing of code that handles malloc failures.

Add token_list tests, malloc override

---

testing/opae-c/test_enum_c.cpp
testing/xfpga/test_enum_c.cpp

We expect fpgaPropertiesSetNumInterrupts() to return FPGA_OK, irrespective of
whether the input num_interrupts parameter makes sense.

plugin-api: fix enumeration test cases

---

testing/xfpga/test_reset_c.cpp

Re-enable commented out tests and add negative test for invalid FPGA_PORT_RESET ioctl.

Enable negative test cases

---

libopae/api-shell.c
testing/mock/test_system.cpp
testing/opae-c/test_props_c.cpp

Used valgrind memcheck to reveal resource leaks in the
properties tests for opae-c. Fixed 3..
1) fpgaEnumerate was leaking wrapped tokens.
2) the gcov instrumentation causes test_system::opae_create_ to
return duplicate fd's somehow. This was leaking mock_object *'s.
3) A couple of the properties tests were overwriting tokens_[i],
leaking tokens.

tests: scrub opae properties tests for leaks

---

testing/mock/test_system.cpp
testing/mock/test_system.h
testing/opae-c/test_enum_c.cpp
testing/opae-c/test_open_c.cpp
testing/opae-c/test_props_c.cpp
testing/xfpga/test_buffer_c.cpp
testing/xfpga/test_common_c.cpp
testing/xfpga/test_enum_c.cpp
testing/xfpga/test_events_c.cpp
testing/xfpga/test_metadata_c.cpp
testing/xfpga/test_mmio_c.cpp
testing/xfpga/test_mock_errinj_c.cpp
testing/xfpga/test_object_c.cpp
testing/xfpga/test_open_close_c.cpp
testing/xfpga/test_properties_c.cpp
testing/xfpga/test_reconf_c.cpp
testing/xfpga/test_reset_c.cpp
testing/xfpga/test_sysfs_c.cpp
testing/xfpga/test_umsg_c.cpp
testing/xfpga/test_usrclk_c.cpp

Since test_system is extracting the mock sysfs structure in the fn
test_system::prepare_syfs, it should also remove the temporary dirctory
that it creates from that step. This change adds a function
`remove_sysfs` which simply removes the directory (with some error
checking). Because this function is called in the test_system::finalize fn,
this allows the duplicate code to be removed from all the tests.

Add test_system::remove_sysfs function

---

libopae/plugins/xfpga/sysfs.c
libopae/plugins/xfpga/sysfs_int.h
libopae/plugins/xfpga/sysobject.c
libopae/plugins/xfpga/types_int.h
testing/mock/test_system.cpp
testing/mock/test_system.h
testing/xfpga/test_object_c.cpp

* Remove "caching" of sysfs file descriptors
* Store permissions with file - determined dynamically from stat
* Add tests for object API functions
* Add test_system::register_file to dynamically register dummy files
These files get routed to /tmp instead and are used for creating dummy
files not part of the sysfs tree
I ran clang-format in the sysfs.c file so I apologize for the large diff. I've already had to undo this formatting several times in other pull request so I would just like to get this change in. 
The real diff for this starts at ~line: 787.

fixup generic object api

---

libopae/api-shell.c
libopae/props.c
libopae/props.h
testing/CMakeLists.txt
testing/mock/test_system.cpp
testing/mock/test_system.h
testing/opae-c/test_buffer_c.cpp
testing/opae-c/test_enum_c.cpp
testing/opae-c/test_error_c.cpp
testing/opae-c/test_event_c.cpp
testing/opae-c/test_hostif_c.cpp
testing/opae-c/test_mmio_c.cpp
testing/opae-c/test_props_c.cpp
testing/opae-c/test_reconf_c.cpp
testing/opae-c/test_reset_c.cpp
testing/opae-c/test_umsg_c.cpp
testing/opae-c/test_version_c.cpp

Increase coverage for fpgaGetProperties[FromHandle].
Add intercept for calloc(), modeled after malloc() intercept.
Call through the adpater to destroy the cloned parent token
if the wrapped token object allocation fails (fpgaGetProperties[FromHandle]
and fpgaUpdateProperties).

tests: Add test coverage for opae-c properties

---

libopae/pluginmgr.c
testing/mock/test_system.cpp
testing/mock/test_system.h
testing/opae-c/test_buffer_c.cpp
testing/opae-c/test_enum_c.cpp
testing/opae-c/test_error_c.cpp
testing/opae-c/test_event_c.cpp
testing/opae-c/test_hostif_c.cpp
testing/opae-c/test_mmio_c.cpp
testing/opae-c/test_open_c.cpp
testing/opae-c/test_props_c.cpp
testing/opae-c/test_reconf_c.cpp
testing/opae-c/test_reset_c.cpp
testing/opae-c/test_umsg_c.cpp
testing/xfpga/test_buffer_c.cpp
testing/xfpga/test_common_c.cpp
testing/xfpga/test_enum_c.cpp
testing/xfpga/test_events_c.cpp
testing/xfpga/test_metadata_c.cpp
testing/xfpga/test_mmio_c.cpp
testing/xfpga/test_mock_errinj_c.cpp
testing/xfpga/test_object_c.cpp
testing/xfpga/test_open_close_c.cpp
testing/xfpga/test_properties_c.cpp
testing/xfpga/test_reconf_c.cpp
testing/xfpga/test_reset_c.cpp
testing/xfpga/test_sysfs_c.cpp
testing/xfpga/test_umsg_c.cpp
testing/xfpga/test_usrclk_c.cpp

Fix memory leak related to mkdtemp
Fix other leaks from not destroying tokens in enum_c tests

fix some memory leaks

---

libopae/api-shell.c
testing/CMakeLists.txt
testing/opae-c/test_object_c.cpp

Fix bugs in fpgaObjectGetObject. Add test coverage for object
API's at opae-c level.

tests: add unit tests for sysobject API in opae-c

---

testing/opae-c/test_enum_c.cpp

Fix test memory error caught be valgrind memcheck.

tests: fix opae-c enumeration test error

---

testing/opae-c/test_event_c.cpp

Identified by valgrind memcheck.

tests: fix opae-c event test leak

---

libopae/src/common.c

The hash computation was generating aliases when about 250k pages were allocated.
Use a simple atomic counter, which is also faster, instead.

wsid's bound to shared buffers must be unique

---

libopae/src/buffer.c
libopae/src/close.c
libopae/src/mmio.c
libopae/src/open.c
libopae/src/types_int.h
libopae/src/wsid_list.c
libopae/src/wsid_list_int.h
tests/function/gtMMIO.cpp

Unique workspace IDs are assigned to each allocated shared buffer. The IDs are used
for discovering the PA of a buffer and for passing the buffer size to the kernel when a page
is deallocated.  The data structure was a list, which didn't scale.  A million allocated
pages took over 1.5 hours to free.  The new code accomplishes the same in about 4 seconds.

Use a hash to track the wsid space.

---

testing/opae-c/test_error_c.cpp

The test assumed "first_error" was the first error but that may not
always be discovered first when the error list is built.

fix errors test to not assume discovery order

---

testing/mock/ioctl_handlers.cpp
testing/mock/test_system.cpp
testing/mock/test_system.h

Using default_ioctl_handler registers a handler as a default.
ioctl handlers are cleared in the finalize routine and the default
handlers are registered in the initialize routine.
This allows for starting with the default handlers earch time a test
fixture calls test_system::initialize()

add default_ioctl_handler function in test_system

---

testing/mock/test_system.cpp
testing/mock/test_system.h
testing/xfpga/test_metadata_c.cpp

This function can assemble a simple gbs header from data encoded in the
platform db for the given platform device.

Add assemble_gbs_header fn in test_system.

---

testing/xfpga/test_umsg_c.cpp

Previous fpgaGetUmsgPtr test called an ioctl that doesn't exist, hence the failure. That test has been removed and added new tests for free_umsg_buffer.

Resolved fpgaGetUmsgPtr test and added free_umsg_buffer tests

---

libopae/plugins/xfpga/sysobject.c

Add a check for max_size being non-zero, then it calls memset_s to zero
out the memory (instead of memset32_s). Because it was using memset32_s
but using the size, this could potentially corrupt memory when size was
the same as max_size.

Use correct memset function in fpgaObjectWrite64

---

testing/mock/test_system.cpp
testing/xfpga/test_buffer_c.cpp
testing/xfpga/test_common_c.cpp
testing/xfpga/test_error_c.cpp
testing/xfpga/test_events_c.cpp
testing/xfpga/test_metadata_c.cpp
testing/xfpga/test_mmio_c.cpp
testing/xfpga/test_object_c.cpp
testing/xfpga/test_reconf_c.cpp
testing/xfpga/test_reset_c.cpp
testing/xfpga/test_sysfs_c.cpp
testing/xfpga/test_umsg_c.cpp
testing/xfpga/test_usrclk_c.cpp
testing/xfpga/test_wsid_list_c.cpp

When using gcc-6 or gcc-7 there are several warnings that are marked as errors and thus compilation cannot succeed.
Main causes:
* unused variables
* gcc also complains about dangling 'if' without 'else' unless you surround 'if' positive branch with { .. }
i think people (me) will need this to build their branches ...

Fix compilation of the tests (gcc-warnings in feature/plugin-api)

---

testing/fpgad/test_errtable_c.cpp
testing/opae-c/test_buffer_c.cpp
testing/opae-c/test_enum_c.cpp
testing/opae-c/test_error_c.cpp
testing/opae-c/test_event_c.cpp
testing/opae-c/test_hostif_c.cpp
testing/opae-c/test_mmio_c.cpp
testing/opae-c/test_object_c.cpp
testing/opae-c/test_open_c.cpp
testing/opae-c/test_props_c.cpp
testing/opae-c/test_reconf_c.cpp
testing/opae-c/test_reset_c.cpp
testing/opae-c/test_umsg_c.cpp
testing/opae-c/test_usrclk_c.cpp
testing/xfpga/test_buffer_c.cpp
testing/xfpga/test_common_c.cpp
testing/xfpga/test_enum_c.cpp
testing/xfpga/test_events_c.cpp
testing/xfpga/test_metadata_c.cpp
testing/xfpga/test_mmio_c.cpp
testing/xfpga/test_mock_errinj_c.cpp
testing/xfpga/test_object_c.cpp
testing/xfpga/test_open_close_c.cpp
testing/xfpga/test_properties_c.cpp
testing/xfpga/test_reconf_c.cpp
testing/xfpga/test_reset_c.cpp
testing/xfpga/test_sysfs_c.cpp
testing/xfpga/test_umsg_c.cpp
testing/xfpga/test_usrclk_c.cpp

Initialize the tokens_ std::array member of the fixtures
using the double brace syntax. Destroy the tokens_ in
TearDown.

tests: fix std::array syntax for token initializer

---

libopae/src/mmio.c
libopae/src/open.c

1. Dereference 'ws' which may be NULL.
2. Free tracker info when open returns.

Addressing Klocwork issues:

---

platforms/scripts/platmgr/emitcfg.py

Quartus archives need it instead of using "source".

Use set_global_assignment for loading Tcl in PIM

---

common/include/opae/sysobject.h
common/include/opae/types_enum.h
libopae/plugins/xfpga/sysobject.c
samples/hello_events.c
samples/object_api.c
testing/opae-c/test_object_c.cpp
testing/xfpga/test_object_c.cpp
tools/extra/coreidle/coreidle.c
tools/extra/ras/main.c

* Remvoe FPGA_OBJECT_TEXT flag and replace with its contrary,,
FPGA_OBJECT_RAW.
* Change the default behavior of fpgaObjectRead64 and fpgaObjectWrite64
to treat buffer read as string text and parse it.
* The FPGA_OBJECT_RAW can read in the raw bytes and store it in the
output variable or take the raw bytes and write them to the object.

object api: remove FPGA_OBJECT_TEXT flag

---

testing/opae-cxx/test_properties_cxx_core.cpp

A cxx properties test was failing an enumeration step for DCP platform due to the input guid always set to MCP. This changes it to retrieve the actual platform device afu_guid field for enumeration.

Added support for DCP platform in cxx properties test.

---

common/include/opae/sysobject.h
libopae/adapter.h
libopae/api-shell.c
libopae/plugins/xfpga/sysfs.c
libopae/plugins/xfpga/sysobject.c
libopae/plugins/xfpga/xfpga.h
samples/object_api.c
testing/fpgad/test_errtable_c.cpp
testing/opae-c/test_object_c.cpp
testing/xfpga/test_object_c.cpp

This change simplifies the fpgaObjectGetObject API by eliminating the
optional handle parameter and instead changing the behavior so that any
object created from a handle will inherit the handle.
The object api sample is updated to not use the handle and may be
updated later to allow freezing of objects.

Remove "handle" parameter from fpgaObjectGetObject

---

testing/xfpga/test_open_close_c.cpp

Removed unused variables in test code that caused warnings in gcc version 4.8.5-16. Not sure why this is not causing warnings in other versions. Even 4.8.5-11 doesn't catch it. But unused vars is a common check.

Removed unused variables in test.

---

libopae/plugins/xfpga/sysfs.c

sysfs_write_u64 was determining the number of bytes to write using
sizeof(buf). This was incorrect, because only the number of bytes
resulting from the snprintf conversion should be written.

xfpga: fix bug in sysfs_write_u64

---

scripts/cover.sh

cover.sh was previously copying each of the .gcda and .gcno files
to a directory, squashing the original directory hierarchy. This
resulted in some of the coverage data files being lost, eg both
userclk and coreidle have a main.c file. The change captures the
coverage data from the files in the directory hierarchy where they
are generated.

cover.sh: don't copy coverage files

---

common/include/opae/cxx/core/sysobject.h
libopae/plugins/xfpga/sysobject.c
libopaecxx/CMakeLists.txt
libopaecxx/src/sysobject.cpp
testing/CMakeLists.txt
testing/opae-cxx/test_object_cxx_core.cpp

* The cxx/core/sysobject wraps the Object API
* Add tests cases for cxx sysobject class
* Add some error checking in the Object API read/write routines
* Check if the object can be read/written (if it's not a dir object)

Add C++ core sysobject API

---

libopae/plugins/xfpga/sysfs.c

* Initialize the glob_t structure to reflect no matches
* Call globfree on error if glob_t structure has changed to reflect
dynamically allocated memory

Update call to glob to minimize risk of memleak

---

ase/scripts/generate_ase_environment.py
platforms/scripts/rtl_src_config

- VHDL simulation doesn't accept +define in the list of sources.
- QI:foo.tcl was treated as a filename when setting up Qsys simulation.

Fix some AFU source file list parsing:

---

testing/ras/test_main_c.cpp
testing/xfpga/test_buffer_c.cpp

Separated two of the buffer tests that used ioctl handlers to do negative tests. They will now only run on mock platforms.
Removed unused variable from ras test.

Separated buffer mock only tests.

---

pyopae/CMakeLists.txt
pyopae/opae.cpp
testing/CMakeLists.txt
testing/mock/test_system.cpp
testing/mock/test_system.h
testing/pyopae/test_properties.py
testing/pyopae/test_pyopae.cpp
testing/pyopae/test_shared_buffers.py
testing/ras/test_main_c.cpp

test_pyopae binary uses pybind11 to embed the python interpreter and to
create opae.fpga as an embedded module along with test_system,
test_platform, and test_device.
test_pyopae uses the first argument to determine if it should run unit
tests defined in an external file. If the first command line argument is
`test`, it evaluates the script identified by the next argument.
This script is assumed to contain tests compatible with the Python
unittest module.
If the first argument is not `test`, the script will be simply evaluated within the context of the embedded interpreter.
In order to embed the opae.fpga module, a preprocessor definition was
added to control how the pybind11 module is defnined (embedded or not).
It also exposes fpgaInitailize as a module method, `initialize` when it
is …

add test_pyopae binary and some tests

---

testing/xfpga/test_sysfs_c.cpp

Updated the tests to enumerate based on the current platform's device id.
Moved sysfs_get_pr_id, sysfs_get_slots, and sysfs_get_bitstream_id tests to mock only without driver due to them expecting no driver.
Separated make_sysfs and make_object_glob tests into mock only and hw only tests.

Updated xfpga sysfs tests to work on hw.

---

common/include/opae/cxx/core/sysobject.h
common/include/opae/types_enum.h
libopaecxx/src/sysobject.cpp
pyopae/CMakeLists.txt
pyopae/opae.cpp
pyopae/pysysobject.cpp
pyopae/pysysobject.h
testing/CMakeLists.txt
testing/pyopae/test_pyopae.cpp
testing/pyopae/test_sysobject.py

* Update cxx/sysobject to
* Include `size` function
* Make functions `const`
* Expose more test_system/test_platform structures to Python for
comparing against in tests
* Add pysysobject.h|cpp files that define Python bindings for
cxx/sysobject
* Add unit tests for Python versions of sysobject APIs

Add Python bindings for sysobject API

---

testing/xfpga/test_usrclk_c.cpp

Updated the tests to enumerate based on the current platform's device id.
Separated the test cases for mock vs hw.
Same changes from PR #833.

Updated xfpga userclk tests to work on HW.

---

testing/platform/CMakeLists.txt
testing/platform/fpga_hw.cpp

Previously it was impossible to run mock on hw as it would populate the platforms database with found hw on the system regardless if ENABLE_MOCK was set. Now it should determine how to populate the platforms database entirely by whether or not ENABLE_MOCK is ON or OFF, regardless of whether or not there are fpgas on the system. This allows the running of all tests on mock even on a system with fpgas, if the user chooses. Also made it print the status of mock if it is enabled, to avoid confusion.

Enabled mock tests to be run on hw with ENABLE_MOCK=ON.

---

pyopae/MANIFEST.in
pyopae/setup.py

Add pysysobject.cpp to setup.py for compilation when building the extension module

pyopae: add pysysobject.cpp to setup.py

---

ase/sw/app_backend.c
ase/sw/ase_common.h
ase/sw/ase_host_memory.c
ase/sw/ase_host_memory.h
ase/sw/protocol_backend.c

Stop using pointers and enums and align data structures to 64 bits
in messages passed between the RTL simulator and the client.

ASE read/write line message sizes were different sizes on 32 bit simulators

---

testing/xfpga/test_mock_errinj_c.cpp

When running fpgaAssignPortToInterface on hw, the test releases a port (/dev/intel-fpga-port1) and re-assigns it. However, the file permission is set to root rw only. This causes the rest of the hw tests to fail/segfaults. This PR moves that test to mock platform only.

Move valid Mock_errinj test to mock only

---

libopae/plugins/xfpga/metrics/bmc/bmc.c
libopae/plugins/xfpga/metrics/bmc/bmc_ioctl.c
libopae/plugins/xfpga/metrics/bmc/bmc_ioctl.h
libopae/plugins/xfpga/metrics/bmc/bmcdata.h

Changes:
- Remove static functions in bmc module c files
- Add functions in bmc c files

libopae: remove static functions in bmc module

---

testing/ras/test_main_c.cpp

Separated the valid test cases for ras to only run on MCP.
Separated the catastrophic and fatal error injection cases into mock only test cases.
Created a new test case for MCP hw only to run a valid test case but without catastropic and fatal error injection.

Separated ras tool tests for hw and mock platforms.

---

opae.spec.in
tools/extra/pac/fpgaflash/CMakeLists.txt
tools/extra/packager/CMakeLists.txt
tools/extra/pyfpgadiag/CMakeLists.txt

After porting fpgaflash, packager and fpgadiag to using distutils, there were errors in RPM package generation. This PR fixes that issue.

Fix issues with RPM generation after porting tools to distutils

---

cmake/modules/coverage.cmake

Added compile flags for the Coverage build type to check for warnings in the tests. Otherwise the tests could get merged with issues that would cause a build to error out during any other build type.

Added flags to Coverage build type to catch build warnings.

---

tools/base/fpgad/srv.c

When run repeatedly in our test environment, server_thread was always
accumulating client sockets onto the end of pollfds. Eventually, we
would hit the limit and fail when given a high iteration count. This
change causes server_thread to close all client sockets on exit, and
resets num_fds to 1 when the thread is started to ensure correctness.

fpgad: close client connections on exit

---

testing/xfpga/test_object_c.cpp

Renamed testnames to be consistent with other tests
Removed unused params
Added fclose to address leaks.

Address mem leaks for xfpga object tests

---

tools/extra/pyfpgadiag/opae/tools/fpgadiag/nlb.py

Change log level of log message emitted by perf_counters to DEBUG.
These messages will only be seen when loglevel of debug is chosen by the
end user.

pydiag: change log level of perf_counters msg

---

testing/mock/ioctl_handlers.cpp

I was able to reproduce the compilation issue on gcc 5.4. This should fix the warning.

Fixed unused variable warning for newer compilers.

---

tools/extra/pyfpgadiag/opae/tools/fpgadiag/diagtest.py

Check for --help and print help message.
Also add a small description + epilog indicating which mode is currently
chosen. Default mode is lpbk1.

pydiag: Restore help option in argparse usage

---

scripts/cover-py.sh
tools/extra/pyfpgadiag/test_fpgadiag.py

Mocking time.sleep to essentially a NOOP reduces execution time to 26ish
seconds.
Change cover-py.sh script to run tests from root of repo

pyfpgadiag: mock `time.sleep`, fix coverage

---

common/include/opae/cxx/core/sysobject.h
libopaecxx/src/sysobject.cpp
testing/opae-cxx/test_object_cxx_core.cpp

Change behavior of sysobject cxx find functions to return nullptr when
FPGA_NOT_FOUND is returned from the C functions (instead of throwing
exceptions)

api: change sysobject cxx to return null

---

libopae/plugins/xfpga/metrics/afu_metrics.c
libopae/plugins/xfpga/metrics/metrics.c
libopae/plugins/xfpga/metrics/metrics_utils.c
testing/xfpga/test_afu_metrics_c.cpp
testing/xfpga/test_metrics_c.cpp
testing/xfpga/test_metrics_utils_c.cpp

changes:
-returns error not found if user passes all invlaid index
to getmetricbyindex()
-returns error not found if user passes all invlaid serach
strings to getmetricbyname()

libopae: fix metric api invalid input index and name

---

scripts/cover.sh
testing/CMakeLists.txt
testing/pyopae/test_embed.cpp
testing/pyopae/test_pyopae.cpp
testing/pyopae/test_sysobject.py

* Use TRAVIS_PYTHON_VERSION env. variable when configuring the builld
* Check TRAVIS_PYTHON_VERSION in testing/CMakeLists.txt to determine if
test_pyopae + tests should be built/executed
* Update sysobject Python tests to reflect latest change in the cxx API

tests: re-enable pyopae tests

---

testing/fpgad/test_ap6_c.cpp
testing/fpgad/test_ap_event_c.cpp
testing/fpgad/test_errtable_c.cpp
testing/fpgad/test_fpgad_c.cpp
testing/hello_events/test_hello_events_c.cpp
testing/opae-c/test_event_c.cpp
testing/opae-cxx/test_events_cxx_core.cpp
testing/xfpga/test_events_c.cpp
tools/base/fpgad/config_int.h
tools/base/fpgad/fpgad.c

Deprecate --directory and --umask parameters.
Restrict --logfile and --pidfile parameters to allowing file names only.
Set directory based on the current user:
* If root, then use /var/lib/opae
* Otherwise, use ${HOME}/.opae
Set the umask based on the current user:
* If root, deny world read/write and group write.
* Otherwise, deny world write and group write.

fpgad: harden the workspace

---

testing/CMakeLists.txt

This can be removed as the default C++ flags in this build chain will
use -std=c++11

cmake: Remove CXX_STANDARD in call to try_compile

---

testing/fpgaconf/test_fpgaconf_c.cpp
tools/base/fpgaconf/fpgaconf.c

Use canonicalize_file_name when validating the input gbs file.
Add/Update unit tests for this functionality.

fpgaconf: use canonicalize_file_name

---

testing/fpgad/test_ap6_c.cpp
testing/fpgad/test_fpgad_c.cpp
tools/base/fpgad/config_int.h
tools/base/fpgad/fpgad.c
tools/base/fpgad/srv.c

Use canonicalize_file_name for checking if nullgbs argument is valid. If
it is invalid, canonicalize_file_name will return NULL and set errno
accordingly.
Add unit tests for this

fpgad: use canonicalize_file_name for nullgbs

---

testing/opae-c/test_object_c.cpp

- Add negative unit tests for fpgaHandleGetObject, fpgaTokenGetObject, and
fpgaObjectGetObject. These tests pass in a malformed name string that contains
a null byte.

Add null byte testcases for object API.

---

tools/extra/fpgadiag/perf_counters.cpp
tools/extra/fpgadiag/perf_counters.h

Because sysobject API has changed to return nullptr if/when an object
does not exist, usage of these objects had to updated in perf_counters
to check if objects are null before using. Previous logic relied on
`not_found` exception being thrown.

fpgadiag: fix logic around sysobject counters

---

tools/base/fpgad/fpgad.c

Use canonicalize_file_name to expand homedir.
If the directory does not exist, result will be null.
If it does exist, used the canonical name when checking if it's rooted
at /home.

fpgad: expand $HOME directory before validating

---

opae.spec.in

The afu_platform_info file is needed to generate AFUs.  It
is included when installing from source, but not included
in the generated rpm.

Include afu_platform_info in generated rpm

---

testing/opae-c/test_reconf_c.cpp
testing/opae-c/test_umsg_c.cpp

According to the OPAE C programming guide, Umsg and Reconfiguration API calls are not supported for Accelerator. These changes set the object type to Device in setup and variable renamed.

Fix object type in opae-c tests

---

libopae/plugins/xfpga/sysfs.c

Change PARSE_MATCH_INT macro to use goto instead of returning to avoid
not freeing the regex structure in error cases.

xfpga: fix potential memleak in regex

---

libopae/pluginmgr.c
testing/opae-c/test_enum_c.cpp

in opae_plugin_mgr_finalize_all, reset the flags member to 0 to
inidicate that the platform hasn't been detected.
This adds the call for fpgaFinalize in one test. Other tests need to be updated to call it too.

pluginmgr: add code to reset platforms detected

---

libopae/plugins/xfpga/sysfs.c
libopae/plugins/xfpga/sysfs_int.h
testing/xfpga/test_sysfs_c.cpp

* add `parse_device_vendor_id` function that reads device/vendor sysfs
attributes
* change `make_region` to call `parse_device_vendor_id` using region
path as the root, and `device/device` and `device/vendor` to get
device_id and vendor_id.
* add `sysfs_foreach_region` iterator function to  process regions
* add sysfs tests

xfpga: add device_id/vendor_id and iter fn

---

ase/scripts/generate_ase_environment.py

Check if the target path already exists in filecopy
Fixes a corner case where the source folder contains
a qsys system and subdirectories contain TCL sources.
copytree recursively copies all dirs under the src.
Later, an attempt to copy subdirectories
with TCL sources fails because files already exist.

Check if the target path already exists in filecopy

---

libopae/plugins/xfpga/CMakeLists.txt
libopae/plugins/xfpga/buffer.c
libopae/plugins/xfpga/opae_ioctl.c
libopae/plugins/xfpga/opae_ioctl.h
testing/CMakeLists.txt

opae_ioctl will contain the ioctl interface methods and defines a common
way of collaing ioctl.
NOTE: While the common ioctl function is variadic, it only unpacks one
argument. IOW, will only work for IOCTL requests that take one argument.
Also, this PR defines one ioctl operation (opae_port_map). 
Other functions will have to be defined and implemented.

xfpga: add opae_ioctl files

---

doc/src/fpga_api/prog_guide/readme.md
testing/opae-c/test_umsg_c.cpp

Update the table to reflect that the Umsg API requires a handle of type
FPGA_ACCELERATOR.

prog_guide: update Functions table for Umsg

---

tools/base/fpgaconf/fpgaconf.c

In the case that program_bitstream() failed, the token would not be destroyed. This fixes the potential leak.

Fixed potential memory leak in fpgaconf.

---

libopae/plugins/xfpga/event.c
libopae/plugins/xfpga/mmio.c
libopae/plugins/xfpga/opae_ioctl.c
libopae/plugins/xfpga/opae_ioctl.h
libopae/plugins/xfpga/umsg.c
testing/xfpga/test_events_c.cpp
testing/xfpga/test_umsg_c.cpp

add the folloing functions:
* opae_get_fme_info
* opae_get_port_info
* opae_get_port_region_info
Change code that uses the ioctl interface directly to instead use these
functions.
Because these functions call one common ioctl wrapper that returns error
codes according to errno, some tests had to be updated for to expect the
appropriate error codes.

xfpga: add functions for getting info

---

libopae/plugins/xfpga/opae_ioctl.c
libopae/plugins/xfpga/opae_ioctl.h
libopae/plugins/xfpga/umsg.c
testing/xfpga/test_umsg_c.cpp

* Also, add code in opae_ioctl to interpret ENOTSUP as FPGA_NOT_SUPPORTED
* Wrapping ioctl calls now standardizes fpga_result codes determined from errno on failed ioctl calls.
Because of this, some tests have to be updated to expect the correct fpga_result code.

xfpga: add functions for umsg ioctl operations

---

testing/fpgad/test_ap6_c.cpp
testing/platform/fpga_hw.cpp
testing/platform/fpga_hw.h

* Add an enumeration of driver types
* Change platform db query functions to use driver enum when selecting
compatible platforms
* Change discovery phase to read `driver` symlink in sysfs pci path
* Use this to determine driver bound to the device

testing: add support for driver type in fpga_hw db

---

testing/platform/fpga_hw.cpp

When running on hw, the tests would query if the specified platform was in the database. If not then it should remove it as when running on hw, the only platform in the database should be what is on the system. But the code would fail to remove the platforms that were not applicable. This should fix it.

Fixed test platform not removing invalid platforms when running on hw.

---

libopae/plugins/xfpga/opae_ioctl.c
libopae/plugins/xfpga/opae_ioctl.h
libopae/plugins/xfpga/plugin.c

* Change return type of ioctl functions to fpga_result
* Add a struct that contains function pointers to opae ioctl ops
* Add an array of two elements of this new data structure type
* The first element refers to fn ptrs related to dfl (upstream) driver
* The second element refers to fn ptrs for internal (intel) driver
* Add a static pointer to an entry in this table
* Add initialization routine for resolving this ptr
* Call opae_ioctl_initialize in plugin initialization
TODO: Look into combining sysfs format operations and ioctl operations
in one interface (perhaps opae_kernel.h|c).

xfpga: add dfl ioctl calls

---

testing/fpgaconf/test_fpgaconf_c.cpp
testing/xfpga/test_reconf_c.cpp

Fixed fpgaconf test parameter causing a buffer overflow.
Fixed xfpga reconf class not calling fpgaInitialize() by simplifying it to inherit the entire class instead.

Fixed fpgaconf test buffer overflow. Fixed xfpga reconf class inheritance.

---

testing/xfpga/test_events_c.cpp

Follow up PR #1086.
Separated send_fme_event_request and send_port_event_request tests to mcp and dcp platforms only. It will return FPGA_NOT_SUPPORTED for all mcp platforms. FPGA_OK is returned for dcp on hw only. (FPGA_NOT_SUPPORTED is returned for mock. Maybe this should be a FIX_ME?)

Resolved xfpga event tests

---

libopae/pluginmgr.c
libopae/pluginmgr.h
testing/opae-c/test_pluginmgr_c.cpp

Add logic in pluginmgr.c to look for and process plugin configuration
files.
The schema is still WIP.

opae-c: add plugin cfg parsing

---

tools/extra/fpgadiag/perf_counters.cpp

When catching 'not_found', simply return 0.
No need for processing exception variable.

remove var. name in catch statement

---

testing/xfpga/test_sysfs_c.cpp

The tests called sysfs_initialize() and sysfs_finalize() when those functions were already being called in SetUp() and TearDown().

Fixed leak in xfpga sysfs tests.

---

ase/sw/protocol_backend.c

Sometimes the select is interrupted and thus returns EINTR. According to the reference the operation can be retried.
This fixed crashed in the ASE simulation where sockets where the event socket was not working.
I wonder if the use of the gnu macro is ok, or if the same behavior should be included in the opae source. What is the coding style guide for this? 
reference:
https://www.gnu.org/software/libc/manual/html_node/Interrupted-Primitives.html

Retry socket select operation if it fails with EINTR

---

libopae/plugins/xfpga/CMakeLists.txt
libopae/plugins/xfpga/metrics/bmc/CMakeLists.txt

Attempting to apply VERSION/SOVERSION to module libraries is causing
build errors on distros with newer versions of cmake. This change
removes the code that was doing that, and it changes the library type of
libbmc.so from SHARED to MODULE (it is dynamically loaded).

opae-c: don't apply versions to modules

---

tools/extra/fpgadiag/perf_counters.cpp

When catching 'not_found', simply return 0.
No need for processing exception variable.

remove var. name in catch statement 

---

samples/object_api.c

The cleanup loop was just missing the first element in the cleanup array.

Fixed leak in sysobject api sample.

---

libopae/opae_int.h
scripts/cover.sh
testing/CMakeLists.txt
testing/opae-c/dummy_plugin.c
testing/opae-c/test_pluginmgr_c.cpp

This dummy plugin makes use of the configuration string by parsing it
and then using the values. The first two values are used to print out to
stdout which the tests verifies. The third value is the number of dummy
tokens to create which is then used for the rest of the test for
enumerating and opening/closing tokens.
This also fixes the ASSERT_NOT_NULL_MSG_RESULT macro to include a space
before "is NULL" in the mssage.

opae-c: add dummy plugin and basic test

---

libopae/pluginmgr.c

In the event that no config files are found or plugins loaded, go back
to loading native plugins as the default ones.

opae-c: add default plugins if no config file

---

testing/mock/mock_opae.h
testing/opae-c/test_buffer_c.cpp

`mock_opae_p` class is a templated class that derives from TestWithParam
and is meant to be a mock class for mock platforms.
The template argument is used to specify how many tokens to use
(if any).
This class implements the SetUp/TearDown that google test uses in the fixture
but also defines test_setup/test_teardown functions that can be overridden by
a sub-class.
This is a first step in refactoring tests to avoid code cloning.

testing: add mock_opae class

---

testing/fpgad/test_fpgad_c.cpp
testing/mock/fpgad_control.h
tools/base/fpgad/command_line.c
tools/base/fpgad/command_line.h
tools/base/fpgad/config_file.c
tools/base/fpgad/config_file.h
tools/base/fpgad/fpgad.c
tools/base/fpgad/monitor_thread.c
tools/base/fpgad/monitor_thread.h
tools/base/fpgad/monitored_device.c

Add config file search and load support by way of --config,-c.
Coming commits will complete the config file parsing and
utilization of the loaded configuration.

fpgad: start of config file support

---

tools/base/fpgad/command_line.c
tools/base/fpgad/config_file.c
tools/base/fpgad/monitored_device.c
tools/base/fpgad/monitored_device.h

Parse the given (--config,-c) configuration file, constructing a
supported devices table based on its contents. If parsing fails,
revert to a default supported devices table.

fpgad: add config file processing

---

tools/extra/pac/fpgabist/bist_app.py
tools/extra/pac/fpgabist/bist_common.py
tools/extra/pac/fpgabist/bist_dma.py
tools/extra/pac/fpgabist/bist_nlb3.py
tools/extra/pac/fpgabist/fpgabist

Python has many ways of executing shell commands. By passing 'shell=True'
we've been exposing program for malicious behavior.
To prevent from doing that use built-in solution in Python [1] which helps
with blocking from shell injection.
[1] https://docs.python.org/2/library/subprocess.html#frequently-used-arguments
Signed-off-by: Dariusz Smigiel dariusz.smigiel@intel.com

Prevent user from hurting himself

---

ase/Makefile
ase/scripts/generate_ase_environment.py

- Detect generated VHDL files and add them to the simulation.
- Detect HEX memory images and put them in the proper location.

Add support for Qsys blocks that generate VHDL.

---

ase/Makefile

I updated the rules to build the work directory but accidentially introduced
a true dependence that caused unnecessary rebuilding.

Avoid re-compilation in ASE due to work directory.

---

testing/fpgad/test_config_file_c.cpp
tools/base/fpgad/command_line.c
tools/base/fpgad/config_file.c

Plugin paths as loaded from the configuration file may not
* be absolute paths
* contain ..
* contain any component that is a symlink

fpgad: verify plugin paths from config file

---

tools/base/fpgad/plugins/fpgad-vc/fpgad-vc.c

Add config file parsing to plugin. Currently, one key "cool-down" of
type integer specifies the cool-down duration for sensor trip.

fpgad-vc: add config file parsing

---

tools/base/fpgad/command_line.c
tools/base/fpgad/command_line.h
tools/base/fpgad/config_file.c
tools/base/fpgad/fpgad.c

Use getpwuid to retrieve the non-root user's home directory.
Check for symlinks in the working directory, log file, and pid file
paths, aborting if they are found.

fpgad: tighten the attack surface

---

libopae/plugins/xfpga/enum.c
libopae/plugins/xfpga/sysfs.c
libopae/plugins/xfpga/sysfs_int.h
testing/xfpga/test_error_c.cpp
testing/xfpga/test_sysfs_c.cpp
testing/xfpga/test_token_list_c.cpp

* rename sysfs_fpga_region to sysfs_fpga_device
A device represents a pci device discovered at:
/sys/fpga/<device_pattern>
* rename sysfs_fpga_resource to sysfs_fpga_region
A region is a platform device (under the pci device) found at:
/sys/fpga/<device_pattern>/<region_pattern>
The reason for doing this is to make it easier to trace back to pci
devices vs platform devices. This will also make it easier when
refactoring syfs discover routine to allow for re-scanning devices
within the lifetime of an application and discovering added/removed
devices.

rename sysfs internal structures

---

libopae/plugins/xfpga/enum.c
libopae/plugins/xfpga/sysfs.c
libopae/plugins/xfpga/sysfs_int.h
testing/mock/mock_opae.h
testing/mock/test_system.cpp
testing/mock/test_system.h
testing/opae-c/test_enum_c.cpp
testing/xfpga/test_enum_c.cpp
testing/xfpga/test_sysfs_c.cpp

* Change xfpa_fpgaEnumerate to use sysfs_foreach_device
* Change sysfs_foreach_device to call
* sysfs_finalize and sysfs_initialize
* This in essense resets the discovered devices so that when this fn
is called, it will start from scratch (and not allow for stale
internal sysf data structures)
* This is also protected by a mutex so it will be close to a guarantee
that none of the devices discovered in one call will be stale -
there's still a small race condition if a device goes away while
this function is executing.
* Add remove_sysfs_dir to test_system
* This will recursively remove a directory under the mock sysfs tree
* Add a unit test to verify that subsequent calls for xfpga_fpgaEnumerate
will reflect devices as represented under /sys/class/fpga(_region)
* Extend mock_opae_p …

xfpga: allow enum. to account for device removal

---

testing/mock/mock_opae.h
testing/mock/test_system.cpp
testing/mock/test_system.h

* Fix the callback function for nftw to do better error handling.
* Change the signature of remove_sysfs_dir to default the path to null
* Only use the path when appending to the tmp sysfs root
* Change remove_sysfs to call remove_sysfs_dir
* This removes spawning a separate process

Fix test_system::remove_sysfs.* functions

---

libopae/plugins/xfpga/sysfs.c
libopae/plugins/xfpga/sysfs_int.h

Change sysfs discovery to not track sriov attributes because it will
fail when walking a port device on a virtual function.
Will handle sriov differently (in a new pull request)

xfpga: revert changes to track sriov attr.

---

testing/platform/fpga_hw.cpp

We currently use bitstream metadata revision 1.

tests: fix metadata version in bitstreams

---

common/include/opae/dma.h
common/include/opae/types_enum.h

Removing fields from fpga dma properties structure that are HW related and user does not care about

dma.h - remove HW related entries from fpga_dma_properties

---

libopae/plugins/xfpga/sysfs.c

This fixes a bug in re_match_device and re_match_region where it was
using (ptr-end) when calculating at what point in the string to place a
null byte in to terminate the string.
This was resulting in a negative number and the pointer being
dereferenced pointed to somewhere else in the stack of the calling
function thus corrupting it.
The fix is to swap the pointers to correctly calculate the size of the
string (end-ptr).

fix bug in re_match_(device|region)

---

libopae/plugins/xfpga/enum.c
libopae/plugins/xfpga/reconf.c
libopae/plugins/xfpga/token_list.c

Recent changes use `realpath` to get the realpath (without symlinks) to
sysfs nodes and uses that for comparing/identifying certain kinds of
nodes in the OPAE sysfs tree. According to the man page of [realpath](http://man7.org/linux/man-pages/man3/realpath.3.html),
there are bugs and it states that "it is impossible to determine a
suitable size for the output buffer".
This change assures that the buffers that are ultimately used as the
output variable to the call to realpath are of size PATH_MAX
(4096 as defined limits.h).
It has also been observed that calling realpath with a buffer smaller
than PATH_MAX can overflow the buffer even though the lengths of the
resolved paths are ~128.

fix bugs related to use of `realpath`

---

common/include/opae/cxx/core/shared_buffer.h
libopaecxx/samples/hello_fpga-1.cpp

Fix the C++ sample for hello_fpga-1.cpp to use explicit types instead of
the `auto` keyword. This is done to make it clearer as to the types of
objects being created.
Add a note in shared_buffer::c_type doxygen markup to warn developers of
the dangers of _stealing_ a raw pointer from the shared_buffer object.

fix samples and add a note to doxygen of c_type fn

---

testing/opae-c/test_pluginmgr_c.cpp

The previous fix in PR #1175 did not consider the case of building mock on HW. This PR turns dummy plugin and no cfg tests to parameter tests and address filter leak. 
Looking at the test case definition, they should be parameterized, right? @r-rojo

Fix pluginmgr test

---

libbitstream/bitstream.c

Some errant GBS's around BBS 6.4.0 timeframe were created with bitstream
metadata version set to 640. Allow 640 to serve as an alias for version
1 to enable these bitstreams.

libbitstream: metadata version 640 defaults to 1

---

common/include/opae/sysobject.h
common/include/opae/types_enum.h
libopae/plugins/xfpga/sysfs.c
libopae/plugins/xfpga/sysfs_int.h
libopae/plugins/xfpga/sysobject.c
libopae/plugins/xfpga/types_int.h
libopae/plugins/xfpga/xfpga.h
platforms/platform_if/rtl/device_cfg/ccip_cfg_pkg.sv
testing/xfpga/test_sysfs_c.cpp

* Add a new API level enumeration, fpga_sysobject_type, to indicate if
an object is a system attribute (one that can be read or written) or a
container (one that contains other objects)
* Add APIs to access the sysobject type and to get a contained object by
index
* Add opae_glob_paths internal function to help glob patterns that
yield multiple results
* Add make_sysfs_array internal function that creates a container object
of objects from a glob pattern that yields multiple results
* Add sysfs unit tests
* TODO: Add opae-c plugin implementation

opae-c: extend sysobject API, allow container

---

ase/api/src/buffer.c
ase/sw/ase_common.h
ase/sw/ase_strings.c

- When fpgaPrepareBuffer() is called in preallocated mode it should
fail when there is no page mapped at the buffer address.
- MPF's new VTP speculative mode depends on this behavior.

Improve ASE simulation of fpgaPrepareBuffer() failures.

---

libbitstream/bits_utils.c
libbitstream/metadatav1.c
testing/bitstream/test_metadatav1_c.cpp

Allow the following keys to be optional. Some GBS in current DCP
releases omit them:
"clock-frequency-high"
"clock-frequency-low"
"power"
"platform-name"

libbitstream: allow some keys to be optional

---

libbitstream/bits_utils.c
libbitstream/bits_utils.h
libbitstream/metadatav1.c
libbitstream/metadatav1.h
testing/bitstream/test_bits_utils_c.cpp
testing/bitstream/test_metadatav1_c.cpp

Change the type of the following fields to double and allow them
to appear in the JSON metadata as either int or double:
afu_image.clock_frequency_high
afu_image.clock_frequency_low
afu_image.power

libbitstream: allow fields to be int or double

---

tools/base/fpgad/plugins/fpgad-vc/fpgad-vc.c

After performing a bus rescan, the device's PCI address can change. In this case, we can't rely on the cached copy of the driver remove path.  Instead, we need to query the current PCI address attributes when performing the next driver remove operation.

fpgad-vc: fix driver remove bug

---

libbitstream/bitstream.c

Newer versions of gcc flag fall-through switch cases as warnings,
which become build errors, because we're using -Werror.

libbitstream: remove fall-through switch case

---

testing/fpgad/test_event_dispatcher_thread_c.cpp
tools/base/fpgad/command_line.c

* fpgad: fix mem leak for invalid GBS test
* Fixed uninitialized value in fpgad test.

VC: Address fpgad leaks in tests

---

cmake/modules/compiler_config.cmake
libbitstream/bitstream.c

Add cmake C compiler check (C++ TBD) for -Werror=implicit-fallthrough=3.
With this option, placing a /* FALLTHROUGH */ comment in the switch
case in question avoids what would otherwise be a warning.

libbitstream: enable fallthrough switch case

---

ase/api/src/buffer.c
ase/sw/ase_host_memory.c

This can be valuable when managing pinning automatically, such as in MPF. For
normal simulation there is no visible difference.

Make ASE memory management more like real FPGA pinned buffers.

---

tools/base/fpgad/fpgad.cfg
tools/base/fpgad/monitored_device.c
tools/base/fpgad/plugins/fpgad-vc/fpgad-vc.c

* fpgad-vc: sensor overrides in config
Allow users to override the sensor trip points using the configuration
file settings.
To do so, add..
"config-sensors-enabled": true,
"sensors": [
{
"id": 1,
"high-fatal": 100.0,
"high-warn": 90.0,
"low-warn": 10.0,
"low-fatal": 0.0
},
...
]
If config-sensors-enabled is false, then the entire sensors section
is ignored. If id is not a valid sensor id, then the entry has no
effect. Each of high-fatal, high-warn, low-fatal, and low-warn are
optional. If omitted, then the sensor value is not checked for the
corresponding limit.
* Implement cap of user limits by hw when applicable
(cherry picked from commit 2c8c1e87f1257fe65df7bf1084a48921e348c7e5)

fpgad-vc: sensor overrides in config

---

CMakeLists.txt

Cherry pick for a deb package fix from the internal vc branch.

Cherry-pick: Add fpgaflash to deb tools-extra package (#697)

---

libopae/pluginmgr.c

strlen() was being used as the size to malloc for the cfg, which would contain the config file string. Except strlen() does not count the null terminator which we are trying to copy to cfg (line 334) which causes an invalid write.

Fixed the plugin config read size to account for a null terminator.

---

libopae/plugins/xfpga/sysobject.c

Syncing an object is only applicable to objects that are backed by sysfs
files (and not directories or containers). This fix ensures that
sync_object is called only for file objects.

xfpga: fix impl. of ObjectGetSize

---

testing/ase/test_sw_c_ase.cpp
testing/opae-c/test_init_c.cpp

Fixed ASE tests cleaning up the test files in TearDown().
Fixed ASE tests uninitialized variable usage.

Fixed ASE test file cleanup and uninitialized variable usage.

---

libopae/plugins/ase/sw/ase_host_memory.c

Wrong level was passed to ASE's internal page table manager, leading
to a SEGV. Tested with MPF/VTP's random tester, which is the only
code that exercies repeated alloc/free of pinned buffers.

Fix a bug in ASE that incorrectly handled munmap of a buffer.

---

common/include/opae/cxx/core/sysobject.h
libopaecxx/src/sysobject.cpp
pyopae/pysysobject.cpp
pyopae/pysysobject.h

Add sysobject::type function that retrieves the object type enum.
Use this in the Python binding for __getitem__ to allow getting an
indexed item from a container or from an attribute.

add 'type' function to get object type

---

libopae/plugins/ase/rtl/device_models/dcp_emif_model_basic/emif_ddr4.v

The DDR simulation model's Avalon ready/enable protocol deliberately uses clock offsets, which wreak havoc even in the Qsys-supplied bridges. Adding a small delay to the simulated DDR clock passed to the AFU causes the AFU to sample signals when they are stable.

Work around a glitch in the ASE DDR model

---

libopae/plugins/ase/scripts/generate_ase_environment.py

ModelSim, by default, does not include "Memory" when matching signals by
wildcard. Even simple unpacked arrays are considered memory. The change
here, suggested by Francis O'Brien, causes ModelSim to include unpacked
arrays in data recorded during simulation. The impact on simulation speed
is minimal. As Francis noted, very large arrays are still not included
due to other filters.

 Update ModelSim ASE configuration to track unpacked arrays

---

libopae/plugins/ase/api/src/buffer.c

The preallocated page checker confirms two things: that a page is mapped
and that the size is what the user claims. It is attempting to mimic the
behavior of the kernel driver. Checking is pretty slow, which is generally
OK when using huge pages since there aren't very many. When using 4KB pages
it can be painful. The new code does two things to optimize the 4KB case:
- Use /proc/self/maps instead of /proc/self/smaps, since only the address
range has to be checked and not the page size.
- Don't check every page. The cost is too high for the value. The first
200 pages are checked, which ought to catch the majority of user code
bugs. After that, every 100th new page is checked. I thought about
testing randomly, but having the result be unpredictable seems like
a bad idea.

Improve performance of ASE fpgaPrepareBuffer checker.

---

platforms/platform_db/discrete_pcie3.json

This affects ASE simulation only in the rare case, which we documented, that users
specify a generic discrete_pcie3 platform. ASE's Makefile was changed to pass the
FPGA family to Quartus and winds up passing "UNKNOWN" when no family is defined.
Quartus doesn't appreciate that, and blows up.

Add a default FPGA family to the base discrete_pcie3 PIM family.

---

platforms/platform_db/platform_defaults/defaults_ccip.json
platforms/platform_if/rtl/device_cfg/ccip_cfg_pkg.sv
platforms/platform_if/rtl/device_if/ccip_if.vh
platforms/platform_if/rtl/device_if/ccip_if_pkg.sv

Note: this is merely a change in write request encoding. Old platforms ignore the encoding, which uses fields that were previously reserved. Actual support requires an updated platform.

Add byte write data encoding to CCI-P

---

libopae/plugins/ase/rtl/ase_sim_local_mem.sv

The bus definition doesn't have to be specific to "local_mem".
This change affects only PIM v2.

The PIM v2 interface for Avalon memory is now generic.

---

libopae/plugins/ase/sw/ase_host_memory.c
libopae/plugins/ase/sw/mqueue_ops.c

Shared buffer allocation and address translation share a lock. Buffer
allocation held the lock too long, making a deadlock possible if the
pipe between the two processes is full.

Fix a race in ASE.

---

libopae/plugins/ase/sw/app_backend.c

When running in server mode, ASE may accept a new connection after the previous
one exits. The buffer index count was not being reset for new connections.
The RTL side depends on buffer index 0 being the MMIO space, so failed to
detect MMIO on all but the first connection.

Reset ASE buffer index counter when client disconnects.

---

libopae/plugins/ase/Makefile

ASE failed to build on Ubuntu, where dash is the default shell. Replace non-POSIX
bash string substitution with variations of the "find" command.

Use POSIX-friendly commands in the ASE Makefile

---

tools/extra/fpgadiag/nlb0.cpp
tools/extra/pac/fpgabist/bist/bist_dc.c
tools/extra/pac/fpgabist/bist_app.py
tools/extra/pac/fpgabist/bist_common.py
tools/extra/pac/fpgabist/bist_def.py
tools/extra/pac/fpgabist/bist_dma.py
tools/extra/pac/fpgabist/bist_nlb0.py
tools/extra/pac/fpgabist/bist_nlb3.py
tools/extra/pac/fpgabist/dma/fpga_dma_test.c
tools/extra/pac/fpgabist/fpgabist

The Vista Creek (VC) merge left fpgabist broken when used with Darby Creek
regressions. The new VC bist code hard-wired the device ID of Rush Creek and
promoted device ID handling so that it had to match the board, even when a
full BDF was supplied.
The changes here:
- Demote --device-id so it is just one of the components in the search for a board.
The default value is None. The new algorithm looks for all available FPGAs on the
host and then filters them using the supplied BDF and device ID. The test can run
as long as the filter matches a single FPGA.
- Cherry pick a few changes from the DC branch.
- Repair the non-trivial merge of the DC and the VC changes.
- Fix nlb0 clock frequency discovery. It was reporting in correct performance.

Fix fpgabist for PAC regressions

---

cmake/modules/FindTbb.cmake
tools/extra/pac/fpgabist/CMakeLists.txt

Allow the cmake and build steps to continue in the case that the TBB
package is not found. When TBB is found, fpgabist/dma is included in
the build.

fpgabist: dma: allow configuration without TBB

---

libopaecxx/CMakeLists.txt
tools/extra/integrated/hssi/CMakeLists.txt

ASE depends on dynamically loading libopae-c-ase instead of libopae-c.
The C++ OPAE library was claiming dependence on libopae-c. Drop this
and leave it to the application writer to specify the proper OPAE SDK
library during the final link.

libopaecxx must not automatically load libopae-c or ASE breaks.

---

libopae/plugins/ase/rtl/ase_sim_local_mem.sv
libopae/plugins/ase/rtl/ase_top.sv
libopae/plugins/ase/rtl/ccip_emulator.sv
libopae/plugins/ase/rtl/device_models/dcp_emif_model_basic/emif_ddr4.v

- Previous code forced c0Rx header and data to zero when there was no message.
I've now seen a few broken AFUs that fail on HW but work in simulation because
of the default zero state.
- Eliminate an internal error in the AVMM response scheduling by managing
waitrequest in the ASE model driver. The AVMM model was delaying read responses
when waitrequest was high, which led to the model trying to schedule multiple
responses in the same cycle.
- Instantiate one AVMM bank in the lowest level module instead of two. Doing two
at once was needlessly complicated and made it hard to model systems with an odd
number of banks.

ASE RTL bug fixes

---

tools/extra/pac/fpgabist/bist_common.py

fpgaconf recently changed it's argument parsing, causing "-v" to print the
version. It fails when specified with other arguments, leading to fpgabist
failures.

Remove "-v" argument to fpgaconf in fpgabist

---

libopae/plugins/ase/rtl/ccip_emulator.sv

A nasty bug in ASE emulation of CCI-P c1Tx: when sop was set in a c1Tx
header the mdata and address were latched, even when the valid bit is
not set. Even worse, the emulator's debug logging printed correct
behavior despite the internal emulation using the wrong values.

ASE: Ignore CCI-P c1Tx sop when not valid

---

libopae/api-shell.c
samples/hello_fpga.c
testing/opae-c/test_init_c.cpp
testing/opae-c/test_version_c.cpp
testing/xfpga/test_properties_c.cpp

Relying on config.h broke the ASE regression, which peeks inside
the OPAE tree to build hello_fpga. Use the version API's instead
to query the version.

hello_fpga: don't use version macros from config.h

---

samples/object_api.c

Moved ADD_TO_CLEANUP() to after the failure check to prevent attempting to free unallocated memory.

Fix potential object_api sample segfault

---

libopae/plugins/xfpga/metrics/metrics_utils.c
tools/base/libboard/board_rc/board_rc.c

- Suspicious dereference of pointer 'pglob.gl_pathv' before NULL check
- Memory leak. Dynamic memory stored in 'bmc_object'
allocated through function 'fpgaTokenGetObject'

fix static code analysis issues

---

samples/object_api.c

- Pointer may be dereferenced after it was positively checked for NULL
- Result of function that can return NULL may be dereferenced
- Null pointer may be dereferenced

samples: fix static code scanner issues

---

libopae/plugins/xfpga/error.c

The current method to clear errors reads the value of the error and
writes it back to the clear file. Clearing ras injected errors is
different in that it must be a zero to clear (instead of the current
value). This adds a check for the error name being cleared and uses zero
if it is 'inject_error'.

libopae: fix error API clear routine

---

CMakeLists.txt
opae.spec.in

CMake CPack is complaining about the package being partially relocatable while building RPMs because some of the files for fpgad are not being installed on the “Prefix” for the packages (CMAKE_INSTALL_PREFIX). Hence the package is partially relocatable which means that if a user tried to install the package using "--prefix <dir>" to a different location, they are going to get errors since these 3 files cannot be installed in any other location apart from /etc. This usually is not the standard way of installing files since it obstructs some of the functionality that RPM offers. That being said, we really do need to install these files in /opt for fpgad to function properly. So the solution is to set CPACK_RPM_RELOCATION_PATHS to /etc and add that as a prefix for the opae-tools package.

Fix "partially relocatable" warnings on rpm package generation

---

libopae/plugins/ase/sw/ase_host_memory.c

When pinning pages on real FPGAs, the kernel keeps a reference count of
the number of times a page is pinned. Pages must be released the same number
of times before the kernel unpins them. ASE was not keeping the equivalent
count, causing translations to be lost the first time a buffer was released.
New code now uses 8 bit counters to track references.

Add reference counting to ASE's pinned buffer model.

---

libopae/plugins/xfpga/sysfs_int.h

The use of the struct _sysfs_fpga_device is equivalent to
sysfs_fpga_device for the element 'device' in the the
sysfs_fpga_region structure.
Fixes a compliler error with clang
.../opae-sdk/libopae/plugins/xfpga/sysfs_int.h:70:3: error: redefinition of typedef 'sysfs_fpga_device' is a C11 feature [-Werror,-Wtypedef-redefinition]
} sysfs_fpga_device;
^
.../fpga/opae-sdk/libopae/plugins/xfpga/sysfs_int.h:47:35: note: previous definition is here
typedef struct _sysfs_fpga_device sysfs_fpga_device;

Convert typedef of sysfs_fpga_region into a foreward declaration

---

tools/extra/pac/fpgabist/dma_vc/fpga_dma_test.c

In hwloc v1.11 the api for hwloc_set_membind_nodeset is
HWLOC_DECLSPEC int hwloc_set_membind_nodeset(hwloc_topology_t topology,
hwloc_const_nodeset_t nodeset,
hwloc_membind_policy_t policy,
int flags);
The third parameter has a type of hwloc_membind_policy_t, however
HWLOC_MEMBIND_THREAD is of type hwloc_membind_flags_t.
This mismatch causes a compile error on the latest gcc
.../opae-sdk/tools/extra/pac/fpgabist/dma_vc/fpga_dma_test.c:730:30: error: implicit conversion from ‘enum <anonymous>’ to ‘hwloc_membind_policy_t’ [-Werror=enum-conversion]
730 |     topology, obj2->nodeset, HWLOC_MEMBIND_THREAD,
|                              ^~~~~~~~~~~~~~~~~~~~
Fix by replicating the calling of hwloc_set_membind_nodeset as is done in
fpga_dma_test_utils.cpp

Fix call to hwloc_set_membind_nodeset

---

tools/extra/pac/fpgabist/dma/fpga_pattern_checker.h
tools/extra/pac/fpgabist/dma/fpga_pattern_gen.h

Without this patch, I get the following errors:
```
[233/275] Building CXX object tools/extra/pac/fpgabist/dma/CMakeFiles/fpga_dma_test.dir/fpga_pattern_checker.cpp.o
FAILED: tools/extra/pac/fpgabist/dma/CMakeFiles/fpga_dma_test.dir/fpga_pattern_checker.cpp.o
/usr/bin/c++   -I../common/include -I../libopae/src -Iinclude -std=c++14 -Wno-unused-local-typedefs -Wno-sign-compare -DHAVE_CONFIG_H -std=c++11 -DFPGA_DMA_MAX_BLOCKS=256 -DFPGA_DMA_BLOCK_SIZE=64 -g -O2 -Wall -Wextra -Werror   -std=gnu++14 -MD -MT tools/extra/pac/fpgabist/dma/CMakeFiles/fpga_dma_test.dir/fpga_pattern_checker.cpp.o -MF tools/extra/pac/fpgabist/dma/CMakeFiles/fpga_dma_test.dir/fpga_pattern_checker.cpp.o.d -o tools/extra/pac/fpgabist/dma/CMakeFiles/fpga_dma_test.dir/fpga_pattern_checker.cpp.o -c …
```

Force 32-bit struct alignment. Fixes compilation with GCC 9

---

tools/extra/pac/fpgabist/dma_vc/fpga_dma_test.c

The fedora-upstream branch in commit
e9a07045b5b51a1e4f36cdd06018c187f45a11a1
fixes issues with the hwloc on fedora 31+
This change splits out only the hwloc part and fixes its merge
conflict.

Import fix of hwloc v2.0 from fedora-upstream branch

---

tools/extra/pac/fpgabist/dma_vc/x86-sse2.S

Found with rpmlint of the tools-extra package
Reproduced standalone with
readelf -lW .../bin/fpga_dma_vc_test | grep STACK
GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RWE 0x10
The 'E' in RWE is executable
Fix with method described
https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart
Now result is
readelf -lW .../bin/fpga_dma_vc_test | grep STACK
GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RW  0x10

Fix exec stack in fpga_dma_vc_test

---

LICENSE

It is expected that any file should be read from an 80 column terminal.
Add only newlines and spaces.

Format LICENSE to 80 columns.

---

LICENSE

It is expected that any file should be read from an 80 column terminal.
Add only newlines and spaces.

CP Format LICENSE to 80 columns

---

libopae/CMakeLists.txt
libopae/plugins/xfpga/CMakeLists.txt
libopaecxx/CMakeLists.txt

Most of the shared objects are of the form <name>.so.<INTEL_API_VERSION>
In this case <name>.so.1.4.0 with standard symlinks <name>.so.1 and
<name>.so.  For those that do not, provide the versioning to make them
consistent.

Add INTEL_FPGA_API_VERSION version to shared objects.

---

opae-libs/cmake/modules/OPAECompiler.cmake

clang-9: error: argument unused during compilation: '-pie' [-Werror,-Wunused-command-line-argument]
clang-9: error: argument unused during compilation: '-pie' [-Werror,-Wunused-command-line-argument]

fix clang issue -argument unused during compilation: '-pie'

---

opae.spec
scripts/create-rpms.sh

rpmbuild will fetch the source tarball from its upstream location
if it is not found locally.  So improve the Source0 value to point
to that location.  Change the create-rpm script to use the new
tarball name.
Fixes the error with fedora-review
WARNING: Cannot download url: https://github.com/OPAE/opae/opae.tar.gz
INFO: No upstream for (Source0): opae.tar.gz

Set the source0 value in the opae.spec to the upstream source.

---

tools/fpgainfo/bmcdata.c

Fixes a segfault when test_fpgainfo_c is run as not root
Signed-off-by: Tom Rix <trix@redhat.com>

When fpgaOpen fails do not close the handle

---

python/opae.admin/opae/admin/fpga.py
python/opae.admin/opae/admin/sysfs.py

* add 'class_filter' processing in generic sysfs.enum method
* this, if defined in a class, can do some prefiltering when
enumerating devices
* rename fpga class to fpga_base
* add fpga_region that can enumerate dfl driver resources
* define a 'class_filter' method that ignores extra fpga_region links
in sysfs (/sys/class)

opae.admin: add dfl enumeration support

---

platforms/scripts/afu_platform_config
platforms/scripts/platmgr/emitcfg.py
platforms/scripts/rtl_src_config

afu_synth_setup and rtl_src_config were generating paths relative to what
the scripts expected the Quartus working directory to be. Since the working
directory may change, instead generate paths relative to the directories of
the generated QSF scripts.

Generate QSF script paths relative to the current directory.

---

tests/fpgaconf/test_fpgaconf_c.cpp
tools/fpgaconf/fpgaconf.c

Controls setting the new FPGA_RECONF_SKIP_USRCLK flag to
fpgaReconfigureSlot().

fpgaconf: add option --skip-usrclk

---

python/opae.admin/opae/admin/tools/bitstream_info.py
python/opae.admin/opae/admin/tools/fpgasupdate.py
python/opae.admin/opae/admin/utils/process.py
python/opae.admin/opae/admin/utils/progress.py
python/opae.admin/tests/test_progress.py

Change the hard-coded dependency on 'utf-8' to use the value
returned by sys.getdefaultencoding() instead.

opae.admin: use default character encoding

---

python/opae.admin/opae/admin/fpga.py

The glob to find the location of the spi path in sysfs has changed
to dfl-fme.*.*/subdev_spi_altera.*.auto/... Update opae.admin to use
the new glob pattern for dfl drivers.

opae.admin: update spi path for dfl drivers

---

python/opae.admin/opae/admin/tools/fpgasupdate.py

The driver flow was changed such that reading the "error" sysfs
node in other than the "idle" state results in EBUSY. To fix, rather
than polling "error" periodically, only check it on state transition
and only after having verified the "idle" status.

fpgasupdate: update per new driver flow

---

.github/workflows/python-static-analysis.yml

Sets up GitHub Actions YML CI file to perform non-gating linting (w/ flake8)
and gating security scans (w/ bandit) of python scripts in opae-sdk.
Signed-off-by: Asgard Marroquin <asgard.marroquin@intel.com>

ci: add python static analysis

---

.github/workflows/python-static-analysis.yml

Adding path to the 'on' field will make it so this workflow is triggered
only when changed files are in the list of paths specified.

ci: add paths to python ci job

---

packaging/opae.admin/deb/control
packaging/opae.admin/deb/rules

The source is no longer compatible with python2. Under Ubuntu 20.04,
the .deb build was failing because python-all was mentioned in control
and --with python2 was mentioned in rules.

packaging: remove python2 support from packaging

---

python/opae.admin/opae/admin/fpga.py
python/opae.admin/opae/admin/tools/fpgasupdate.py

Reverse VALID_GBS_GUID, because the portion of the script which
performs the comparison relies on it being in that order.
The DFL driver moves pr/interface_id to compat_id at a deeper
nesting in the sysfs tree.

fpgasupdate: fixes for Partial Reconfiguration

---

samples/dummy_afu/test_afu.h

* Removed unused variable (max_)
* Add call to reset a handle before the start of each test run

dummy_afu: fix unused var, add reset

---

samples/dummy_afu/CMakeLists.txt
tests/dummy_afu/CMakeLists.txt

A header file in spdlog has an unused result,
add -Wno-unused-result option in dummy_afu.

dummy_afu: workaround for spdlog compile error

---

tools/extra/fpgabist/dma_N3000/fpga_dma_test.c

clang static analysis reports
fpga_dma_test.c:662:2: warning: Value stored to 'res'
is never read
res = find_fpga(guid, &afc_token, &num_matches);
^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Because num_matches is initialized to 1, when find_fpga
fails and does not set num_matches, the initial value
will be incorrect.  This will lead to other errors.
Intialize num_matches to 0 and depend on the side
effect of setting num_matches > 0 to indicate success.
Signed-off-by: Tom Rix <trix@redhat.com>

improve finding the fpga

---

python/opae.admin/opae/admin/fpga.py
python/opae.admin/opae/admin/tools/rsu.py

The sysfs paths to the secure device mananger sysfs nodes
changed from m10bmc-secure.*.auto for both D5005 and N3000
to d5005bmc-secure.*.auto and n3000bmc-secure.*.auto,
respectively. The affected tools are fpgasupdate and rsu.
Update the RSU mechanism to observe the new sysfs layout.
The secure manager driver implements two sysfs entries for
RSU: available_images and image_load. available_images contains
a null-terminated string describing the available modes.
$ cat available_images
bmc_factory bmc_user retimer_fw
Writing the desired string to image_load causes the driver
to perform the associated RSU operation.

opae.admin: refactor secure device sysfs paths

---

samples/dummy_afu/lpbk.h

Hold a reference to the shared buffer pointers so that they are
not freed before afu reset is asserted.

dummy_afu: retain loopback buffers through reset

---

python/opae.admin/opae/admin/fpga.py

in order to support the drivers while they are in transition to
the new format.

opae.admin: re-inject legacy path to ifpga_sec..

---

python/opae.admin/opae/admin/fpga.py
python/opae.admin/opae/admin/sysfs.py

Before doing RSU operation, unbind drivers from all endpoints except for
the management endpoint with the RSU interface.

rsu: add logic to unbind ep drivers

---

samples/dummy_afu/dummy_afu.h

After a test (in dummy_afu) runs, call handle_->reset again.

dummy_afu: add explicit reset after run

---

samples/hssi/hssi_cmd.h

Empirical evidence suggests that a brief pause is necessary after
$ ethtool --features <ifc> loopback on
Without the pause, it was observed that the number of rx packets
(serial test) can be 0 when num_packets (100) was expected.

hssi: add pause after loopback enable

---

python/opae.admin/opae/admin/sysfs.py

Do not try to unbind devices that have not driver bound.

rsu: fix driver unbind

---

CMakeLists.txt
external/CMakeLists.txt
samples/dummy_afu/CMakeLists.txt
samples/hssi/CMakeLists.txt

During development, both dummy_afu and hssi were loading CLI11
and spdlog. Move those macro invocations to a single location
(external CMakeLists.txt) and process external/ prior to the
samples so that the variables are available.

build: consolidate inclusion of externals

---

tools/extra/fpgadiag/CMakeLists.txt
tools/extra/fpgadiag/test_vfio.c

Adds test_vfio.c as a try_compile to guard building eth_group.cpp.
test_vfio.c checks that the minimum structure definitions are found
in linux/vfio.h.

eth_group: add a try_compile to guard eth_group

---

samples/hssi/hssi.cpp
samples/hssi/hssi_afu.h

and add printouts for mbox exceptions before throwing them.

hssi: increase the mbox timeout to 1 second..
