- opae.spec.in
add pybind11_ROOT to include path for calling setup.py
> rpm: fix build eth_tools setup.py

- tools/extra/fpgabist/CMakeLists.txt
dma_N3000/ is similar to dma/ it depends on TBB
So similarly, disable when TBB is not found.
Signed-off-by: Tom Rix <trix@redhat.com>
> Disable building of dma_N3000 if not TBB_FOUND

- CMakeLists.txt
- opae-libs/CMakeLists.txt
- opae-libs/include/opae/cxx/core/pvalue.h
Also pull in `opae-libs` `release/2.0.0` changes to capture new external target changes regarding `opae-sim` and `opae-test`.
> Use `set` for defining legacy branch target 

- CMakeLists.txt
- afu-test/CMakeLists.txt
- afu-test/afu_test.h
- samples/dummy_afu/CMakeLists.txt
- samples/dummy_afu/ddr.h
- samples/dummy_afu/dummy_afu.cpp
- samples/dummy_afu/dummy_afu.h
- samples/dummy_afu/lpbk.h
- samples/hssi/CMakeLists.txt
- samples/hssi/hssi_100g_cmd.h
- samples/hssi/hssi_10g_cmd.h
- samples/hssi/hssi_afu.h
- samples/hssi/hssi_cmd.h
- tests/dummy_afu/CMakeLists.txt
- tests/dummy_afu/test_dummy_afu.cpp
* move test_afu.h from samples/dummy_afu to afu_test
* make afu_test an interface library in CMakeLists.txt
* rename namespace and classes in afu_test
* namespace opae::app -> opae::afu_test
* class test_afu -> afu
* class test_command -> command
* make necessary changes in dummy_afu and hssi for new afu_test
> afu_test: migrate test_afu to afu_test

- CMakeLists.txt
- opae-libs/CMakeLists.txt
Update the following opae dependencies for opae-sdk `release/2.0.1-1` so that said dependencies point to a snapshot release branch/tag, and not to continue tracking `master`.
- `opae-libs`
- Subtree has been updated to handle `opae-test` and `opae-sim`
- `opae-legacy`
This commit should not be pulled back into `master`, as the `master` branch should naturally track the latest HEAD of each opae dependency. Rather, this commit will be the tag target for release `2.0.1-1`.
> release: update opae release branch targets

- opae-libs/cmake/modules/OPAEPackaging.cmake
Branch/PR pulls in commit https://github.com/OPAE/opae-libs/commit/fca219520bbe7041acd44e6eebcbf7d9c476694c into `opae-sdk` `master` via `subtree`.
> opae-libs: use CMake PYTHON_EXECUTABLE in packager

- tools/extra/mmlink/remote_dbg/streaming/CMakeLists.txt
- tools/extra/mmlink/remote_dbg/streaming/common.c
- tools/extra/mmlink/remote_dbg/streaming/packet.c
- tools/extra/mmlink/remote_dbg/streaming/server.c
- tools/extra/mmlink/remote_dbg/streaming/sockets.c
- tools/extra/mmlink/remote_dbg/streaming/st_dbg_ip_driver.c
In order to build on el7 (which have older cmake/gcc versions), this commit adds
the following changes:
- Adds Wno-strict-aliasing C exception flag for mmlink streaming.
- Separates declaration and definition of `for`-loop counter variables in mmlink streaming
related functions.
Signed-off-by: Marroquin, Asgard <asgard.marroquin@intel.com>
> mmlink: address el7 compile issues

- tools/extra/mmlink/remote_dbg/legacy/CMakeLists.txt
- tools/extra/mmlink/remote_dbg/streaming/CMakeLists.txt
- tools/extra/mmlink/remote_dbg/streaming/common.c
* set c standard to c99 for mml-stream
* set library versions (VERSION/SOVERSION) for mml-srv and mml-stream
* set compiler attribute for allowing aliasing in streaming/common.c
> mmlink: fix mmlink build

- tools/extra/mmlink/main.cpp
The revision bits are 12-15. This fixes the masking so that only these
bits are set when masking with (0xF000) before shifting.
> mmlink: fix revcheck

- docker/centos7.6/Dockerfile
Change docker file to:
* install elrepo and import its gpg key
* install kernel-ml-headers (mainline)
> docker: install kernel headers from elrepo

- docker/centos7.6/Dockerfile
- tools/fpgainfo/errors.c
With Intel OFS, the definition of the port error bits have
changed to reflect the transition from CCI-P to AXI-S TLP.
The fpgainfo command now checks the revision sysfs entry
to use the correct port error bit definitions.
> fpgainfo: add support for revision 2 of port errors

- .github/workflows/update-repo.yml
pull should be used after the subtree has been added.
Because this is a new clone/checkout of master, doing 'add' should work
just as expected.
> ci: fix subtree command to add instead of pull

- .github/workflows/python-static-analysis.yml
- .travis.yml
Travis CI installed linting libraries with default `pip` module, which may be
linking to `python2` on the default Ubuntu 16.04 VM. Install explicitly with
`python3 -m pip`.
Also, add pylint steps in `.github/worksflows/python-static-analysis.yml`, as
well as simply python fileglob detection for the CI push trigger.
Signed-off-by: Marroquin, Asgard <asgard.marroquin@intel.com>
> ci: update python lint jobs

- python/opae.admin/opae/admin/tools/regmap_debugfs.py
- python/opae.admin/setup.py
Add a tool to help access the debugfs interface to regmaps
created in the linux kernel.
> opae.admin: added regmap_debugfs.py

- python/opae.admin/opae/admin/dfl.py
- python/opae.admin/opae/admin/fpga.py
- python/opae.admin/opae/admin/sysfs.py
* refactor class_node to sysfs_device
* a sysfs_device object is meant to be something that an be enumerated
in a bus (physical or logical) or a class.
* modify fpga Python classes to derive from a sysfs_device
* add 'name' property to sysfs_node
* name returns the basename (or stem) of the path
* add dfl.py with dfl class
* dfl class derives from sysfs_device and is meant to look for devices
in /sys/bus/dfl/devices
* add 'feature_id' property to dfl class
> opae.admin: add support for dfl bus

- CMakeLists.txt
- opae-libs/CMakeLists.txt
As development actively occurs on the master branch, pull the next RC from the HEAD of master instead of from the "snapshotted" 2.0.1 release branches.
Updates opae-libs via subtree, as well as the top level CMake opae-legacy target, to `2.0.1-2`.
This is change 2 referenced in comments in https://github.com/OPAE/opae-sdk/pull/1755.
~~This change must wait merge until MR bumping RC 1 to 2 to `master` is completed first (see https://github.com/OPAE/opae-sdk/pull/1757)~~ - Done
> 2.0.1: update opae targets to RC 2

- tools/extra/mmlink/main.cpp
remove declaration of remote_dbg *srv variable from run_mmlink function
as it shadows the static variable that is referenced in the signal
handler to shutdown.
> mmlink: fix shadowed variable

- tools/fpgainfo/errors.c
The table of port error messages was missing a message
for Tx Ch1 overflow.
> tools: fpgainfo: fix table of port error messages

- CMakeLists.txt
- opae.spec.in
- tools/CMakeLists.txt
- tools/libopaevfio/opaevfio.c
- tools/memalloc/CMakeLists.txt
- tools/memalloc/mem_alloc.c
- tools/memalloc/memtest.c
Add management of the IOVA space for DMA buffers.
> libopaevfio: manage IOVA space with allocator

- python/opae.admin/opae/admin/sysfs.py
- python/opae.admin/opae/admin/tools/pci_device.py
- python/opae.admin/setup.py
* Modify pci_node.tree function to add driver name
* Add pci_device.py tool
This is a helper script to manage pci devices.
To use this tool, call run:
```console
pci_device <pci address> <action> [--other-endpoints]
```
This initial implementation supports four actions:
* unbind
This action will unbind any bound drivers
* remove
This action will remove the pci device
* rescan
This action will trigger a bus rescan from the root port
* topology
This action will print out the pcie tree topology.
This will print out the line showing the target device (as identified by the first position command line argument) as green
and other endpoints as cyan.
NOTE: If `--other-endpoints` argument is present, actions like remove or
unbind will operate on the ohter endpoints in the pcie topology.
> opae.admin: add pci_driver tool

- doc/src/install_guide/installation_guide.md
Update installation guide to
* include more up to date information
* libedit-devel and kernel-devel packages
* use of -DOPAE_BUILD_EXTRA_TOOLS_FPGABIST=ON cmake flag
* remove packages installed because they are dependencies
Example: libuuid is a dependency of libuuid-devel and will be
installed by nature of the default behavior of the package manager
dependency resolution process.
> doc: update install guide

- opae.spec.in
- samples/host_exerciser/CMakeLists.txt
- samples/host_exerciser/host_exerciser.cpp
- samples/host_exerciser/host_exerciser.h
- samples/host_exerciser/host_exerciser_cmd.h
- samples/host_exerciser/host_exerciser_lpbk.h
- samples/host_exerciser/host_exerciser_mem.h
-host exerciser used test afu lpbk in different modes
-host exerciser used test afu memory/ddr in different modes
This application has two subcommands, to run different host exerciser tests
Subcommand Lpbk:
AFU copies source buffer content to destination buffer  via AFU
Example: host exerciser lpbk
Subcommand  mem:
AFU copies source buffer content   to DDR ( local FPGA memory) , DDR ( local FPGA memory)  to  destination buffer (host)
Example:  host exerciser mem
host exerciser command line options  
-mode:  
Configures test mode Loop-back, Read, Write and Throughput
-continuousmode
Selects test rollover or test termination
-delay 
Enables random delay insertion between requests
LPBK and MEM   AFU CRS are same , only different in AFU GUID
AFU CSR definitions and CSR offset  are in file …
> add host exerciser sample

- plugins/vfio/opae_vfio.c
- plugins/vfio/opae_vfio.h
- plugins/vfio/plugin.c
* Refactor enumeration in vfio plugin to match PCIe attributes (BDF, socket id)
* Add functions, pci_matches_filters and pci_matches_filter that are called first during enumeration.
* If the filters are empty or the the pci attributes in the filters match the device, it is considered for the rest of enumeration
* Otherwise, it is skipped
* Move token lists from a static token list into the static list of pci_device_t structures.
* This helps prevent reading of CSR space by filtering on specific PCIe attributes read from sysfs
IOW, given a specific PCIe address (segment, bus, device, function), the mmio space will be read only when the PCIe address is 
set in the filter and it matches a device.
* Fix use of open_vfio_pair so that it is called only when a VF has a PF
physfn _AND_ that …
> vfio-plugin: refactor and fix bugs in enumeration

- plugins/vfio/opae_vfio.c
* Remove `features_discover` function because it operates on all
pci_device_t structures in the static list. Now that tokens are
discovered/added to pci_device_t structures during first enumeration,
`features_discover` is no longer necessary.
* Rename `walk` to `vfio_walk`
* Replace call to `features_discover` to `vfio_walk` in `fpgaEnumerate`
implmentation.
> vfio-plugin: fix token discovery

- opae.spec.in
- scripts/test-rpms.sh
* Write names of installed files into specific package name files for
* tools-extra
* devel
* Remove use of python/* glob in %files directive for tools-extra
* Replace with use `%files -f tools-extra-files.txt`
* Add opae.io in test-rpms.sh file
> rpm: add opae.io to legacy rpm spec file

- tests/argsfilter/test_argsfilter_c.cpp
- tools/argsfilter/argsfilter.c
In addition to allowing -S, -B, -D, -F, refactor
set_properties_from_args() so that it also recognizes the PCIe
address forms ssss:bb:dd.f and bb:dd.f. The address forms
are given precedence over the options.
eg fpgainfo fme -B 0xff -D 0xff -F 7 12:34.5
will set the properties as
segment  == 0
bus      == 0x12
device   == 0x34
function == 5
> argsfilter: refactor to accept PCIe address

- CMakeLists.txt
- opae.spec.in
- udpate opae-legacy release tag 2.0.0-2
- fix  release patch in spec file
> opae-sdk: udpate opae-legacy release tag and fix spec file

- tools/fpgainfo/board.c
- tools/fpgainfo/errors.c
- add support 0xaf00 deviceid to fpgainfo board enumeration  list
- iofs release1 bitstream can program on D5005 card
> tools: support fpgainfo for iofs bitstream deviceid

- CMakeLists.txt
- afu-test/CMakeLists.txt
- external/CMakeLists.txt
- opae.spec.in
- platforms/scripts/CMakeLists.txt
- python/CMakeLists.txt
- python/opae.admin/CMakeLists.txt
- scripts/cover.sh
- tests/CMakeLists.txt
- tools/extra/packager/CMakeLists.txt
* set cmake minimum version to 3.10
* change afu-test to an interface (header-only) library where client libraries/applications inherit compiler/linker options when linking with afu-test.
> cmake: set minimum version to 3.10

- opae.spec.in
- samples/CMakeLists.txt
> cmake, rpm spec: fix straggling BUILD_ASE usage

- cmake/modules/Findspdlog.cmake
Refactor/fix the macro to find spdlog.
* Use pkg-config `--cflags-only-I` to get include paths to use as hints
when finding the .h file.
* Use pkg-config `--cflags-only-other` to get compile definitions
required by the distro, for example:
* fedora >=32 needs -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL
(SPDLOG_FMT_EXTERNAL is used when fmt library needs to be linked
* ubuntu 20.04 needs only -DSPDLOG_COMPILED_LIB
* Use cmake variables set by pkg-config for libraries needed to link
with
* pkgcfg_lib_PC_SPDLOG_spdlog will be path to libspdlog.so
* pkgcfg_lib_PC_SPDLOG_fmt will be path to libfmt.so (if used)
> cmake: fix Findspdlog.cmake

- tests/userclk/CMakeLists.txt
- tests/userclk/test_userclk_c.cpp
- tools/extra/userclk/CMakeLists.txt
- tools/extra/userclk/main.c
Removes the -S,--socket-id parameter.
> userclk: integrate argsfilter.

- python/pacsign/PACSign.md
- python/pacsign/pacsign/pacsign.py
- python/pacsign/pacsign/reader.py
Change -S,--SHA256 to -S,--SHA384. ie, the default is 256-bit
signatures. 384-bit signatures are enabled only by specifying
the flags -S or --SHA384.
> PACSign: change default hash size to 256

- tools/extra/fpgadiag/opae/diag/fpgadiag.py
now that fpgadiag is installed as a Python package, the fpgadiag
entrypoint calls the fpgadiag module which in turns calls the underlying
executable. Because the fpgadiag module is installed in the Python
site-pacakges area, we can't rely on using dirname of __file__ anymore.
We should instead use sys.argv[0] to determine the entrypoint and then
get its directory.
> fpgadiag: fix finding of entrypoint dir

- opae.spec.in
- python/opae.io/CMakeLists.txt
- tools/extra/opae.io/CMakeLists.txt
* Replace regular cmake install directive with opae_python_install
* Remove install step in legacy RPM spec file template (opae.spec.in)
* Cleanup whitespace...
> opae.io: use opae_python_install in cmake

- doc/sphinx/conf.py.in
- doc/sphinx/index.rst.in
The opaeuio script is no longer needed, as the driver has switched
to hard-coding the UIO device IDs in the source code.
> docs: remove opaeuio doc

- tests/hello_fpga/test_hello_fpga_c.cpp
- tools/libboard/board_n3000/board_n3000.c
Use OPAE_MSG and OPAE_ERR instead.
> logging: deprecate FPGA_MSG and FPGA_ERR macros

- CMakeLists.txt
- cmake/modules/OFS.cmake
- scripts/ofs_parse.py
- tests/ofs_driver/CMakeLists.txt
- tests/ofs_driver/ofs_test.c
- tests/ofs_driver/ofs_test.yml
- tests/ofs_driver/test_ofs_driver.cpp
ofs umd (user mode driver) is a framework to take driver specs in yml
format and turn it into C data structure, and function
prototypes/implementations.
This commit adds:
* ofs_parse.py script that parses an ofs umd spec in .yml format and
generates a header file for the given driver.
* ofs_add_driver CMake macro that, given the .yml, driver name, and list
of sources it will:
* call ofs_parse.py to generate the .h
* create a cmake library named after the driver name and use given
source to compile.
* sample unit tests in tests/ofs_driver that exercise:
* The cmake macro
* The functions generated by ofs_parse.py
TODO:
ofs_parse.py is mostly prototype-leve code and will need to be
refactored and cleaned up.
> ofs umd: add ofs umd framework

- samples/hssi/hssi_10g_cmd.h
Add a parameter to enable/disable loopback in the Hardware
Exerciser as opposed to serial loopback in the phy.
> samples: hssi: add loopback control of Hardware Exerciser

- CMakeLists.txt
- ofs/CMakeLists.txt
- ofs/apps/CMakeLists.txt
- ofs/apps/cpeng/CMakeLists.txt
- ofs/apps/cpeng/hps.cpp
- ofs/umd/CMakeLists.txt
- ofs/umd/cpeng/CMakeLists.txt
- ofs/umd/cpeng/ofs_cpeng.c
- ofs/umd/cpeng/ofs_cpeng.yml
- tests/ofs_cpeng/CMakeLists.txt
- tests/ofs_cpeng/test_ofs_cpeng.cpp
* Add ofs/umd/cpeng
This contains ofs_cpeng.yml which contains register map and APIs
* Add ofs/apps/hps
* This uses afu_test framework to reuse command line parsing to locate
an AFU and give it to a command.
* Add cpeng command that uses the ofs_cpeng driver to copy an image
from a file.
* Add unit tests for ofs_cpeng driver
> ofs: add umd driver and hps app

- tools/extra/opae.io/main.cpp
The globals the_device and the_region are initialized to
nullptr at program start. Attempting to set Python attributes
to nullptr proves problematic for some combinations of Python
and PyBind11. Removing the initial update of these attr's
solved the observed exception/abort.
> opae.io: don't set attrs to nullptr

- python/pacsign/pacsign/pacsign.py
Also remove related optional args, and the call to the
reader module.
> PACSign: remove "print" subparser..

- tools/extra/qpafilter/n5010_bmc_sensors.yml
- tools/extra/qpafilter/qpafilter.py
Add class two_way_map - given a dictionary mapping strings
to integer IDs, create the inverse mapping and store for later use
with member get(). When given a str, get() returns the integer ID
corresponding to the given string. When given an int, get() returns
the string corresponding to the given ID.
Load the sensors data as command argument -s, --sensor-file.
> qpafilter: add sensors map file

- afu-test/afu_test.h
- ofs/apps/cpeng/hps.cpp
- samples/dummy_afu/dummy_afu.h
- samples/dummy_afu/mmio.h
- samples/host_exerciser/host_exerciser.h
- samples/hssi/hssi_100g_cmd.h
- samples/hssi/hssi_10g_cmd.h
- tests/dummy_afu/test_dummy_afu.cpp
Use default_str instead of default_val to be compatible with older
versions of CLI11.
CLI11::Option::default_str is documented as affecting only how the
default is presented but does not actually set the variable bounded to
the option to that value.
Most of our uses of default_val have the bounded
variable defaulted but some do not.
This change does one of the
following:
* Uses the bounded valriable as the input to default_str
* Uses default_val with a string input
> afu_test: use CLI11 default_str

- tools/extra/qpafilter/qpafilter.md
- tools/extra/qpafilter/qpafilter.py
The parameter to --output should not be optional, but required,
as it is invalid to run qpafilter as
$ qpafilter dump --output
Add qpafilter.md documentation.
> qpafilter: fix --output, add doc

- tools/fpgainfo/errors.c
fpga-upstream-dev branch has removed the revision sysfs node.
if we check the revision is not present, we use the default value.
Signed-off-by: Tianfei zhang <tianfei.zhang@intel.com>
> fix the revision sysfs entry not present

- .github/workflows/python-static-analysis.yml
> ci: remove python 2.7,3.5 from ci checks

- afu-test/CMakeLists.txt
- external/CMakeLists.txt
Some distros include spdlog that uses format operations from an external
fmt library. When this is the case, finding spdlog will set
-DSPDLOG_FMT_EXTERNAL in its definitions.
This change checks for this when it finds the spdlog package that comes
as part of the distro. If it detects fmt is external, it will set
FMT_LIBRARIES to "fmt::fmt" which is the link interface used when
find_package(fmt) finds fmt on the system. When linking afu_test with
spdlog, it will check if FMT_LIBRARIES is defined and call
find_package(fmt) again from its directory so that it will import the
link target, "fmt::fmt"
> cmake: link with fmt if spdlog is found

- python/pacsign/pacsign/hsm_managers/openssl/key_manager.py
- python/pacsign/tests/test_key_manager.py
Change the verification step after the signing process to verify
with the public key. Apparently, the API will take either the public
or the private key, but the public key is the correct choice.
> PACSign: OpenSSL: verify with public key

- tools/extra/opae.io/pymain.h
FileHandler is part of logging module and not in logging.handlers.
> opae.io: fix opae.io

- tools/extra/qpafilter/qpafilter.py
When any of the input fatal temperature values is less than the
minimum of 90C, set that fatal value to 90C.
> qpafilter: use min temperature for invalid fatal

- tools/extra/qpafilter/n5010_bmc_sensors.yml
- tools/extra/qpafilter/qpafilter.py
Changes the format of the input yaml file to allow for specifying
multiple integer IDs for label value and an additional adjustment
value for the upper fatal temperature threshold. The file continues
to be indexed by the string label, however the item contained at each
label is a dictionary with two keys: "id" contains a list of integer
IDs and "adjustment" contains a float that is applied to the upper
fatal threshold. Class qpamap is added to contain the in-memory data
from the yaml input.
Also adds handling for the Virtual Temperature Sensor 0, which is
constructed from the --virt-fatal-temp and --virt-warn-temp command
options.
> qpafilter: updates per request from stakeholders

- tools/extra/qpafilter/n5010_bmc_sensors.yml
- tools/extra/qpafilter/qpafilter.md
- tools/extra/qpafilter/qpafilter.py
Updates the format of the input senors map file so that each
sensor ID may specify an adjustment value, for example:
Sensor0:
- id: 2
- id: 3
adjustment: -1.5
- id: 4
Previously, only one adjustment value could be specified per sensor
label. Now, there is an adjustment value per sensor integer ID.
> qpafilter: update input sensors map file

- python/opae.admin/opae/admin/fpga.py
Recent driver changes have removed one layer from the secure
device path for D5005 devices. The remaining devices retain the
original pattern. Add the new path pattern for D5005.
> opae.admin: update path to secure device for D5005

- tools/libboard/board_d5005/board_d5005.c
- tools/libboard/board_n3000/board_n3000.c
- change in fpga max10 dirver sysfs path
current path: subdev_spi_altera.6.auto/spi_master/spi6/spi6.0
new path : /spi_master/spi6/spi6.0
Max10 sysfs path  dfl*/**/*spi*/*spi*/bmcfw_version
> tools: update recursive  bmc and max10 version sysfs path

- tools/extra/hssi/ethernet/hssicommon.py
- tools/extra/hssi/ethernet/hssistats.py
- set bit 31 to 1 to read HSSI Stats  LSB
- set bit 31 to 0 to read HSSI Stats  MSB
- fix HSSI read / write date CSR  offset
- fix bit fields
> opae-tools: fix hssi Ethernet tools integration bugs

- tools/libboard/board_common/board_common.c
-max10/bmc sysfs path are different  for n3000 and d5005 cards
d5005 sysfspath  dfl*/*spi*/spi_master/spi*/spi*/**/security/
n3000 sysfspath  dfl*/*spi*/spi_master/spi*/**/security/
recursive search path *dfl*/*spi*/*spi*/*spi*/**/security/
> tools: fix fpgainfo security key sysfs path

- python/opae.admin/opae/admin/fpga.py
- python/opae.admin/opae/admin/tools/rsu.py
- tools/fpgainfo/board.c
Add support for the officially reservered PCI device id
for OFS devices.
> add support for PCI device id bcce

- samples/fpgaperf_counter/fpgaperf_counter.c
Modified the source to access the sysfs path for formats and events
using glob instead of udev library.
With udev library in Centos8 machine not able to get events and format attributes for dfl fme.  
Signed-off-by: ramyavv <ramyax.venkatesha@intel.com>
> Samples:Host Exerciser Enhancement

- tools/fpgainfo/errors.c
When dfl-port.X/errors is empty, silence the errors from
'fpgainfo errors all'.
> fpgainfo: silence errors from port

- ofs/apps/cpeng/hps.cpp
- ofs/umd/cpeng/ofs_cpeng.yml
* Add/update registers based on latest spec.
* Add wait_for_verify function to wait for
* ssbl
* kernel
* Add API functions for
* fifo1 status
* fifo2 status
* kernel verify
* ssbl verify
* soft reset
* Among the new APIs, add soft reset and a command line flag to perform
only a soft reset.
> cpeng: update register and api

- samples/host_exerciser/host_exerciser_cmd.h
The host was receiving the interrupt before the final data
writes were complete.  Therefore the resulting buffer compare
failed.  Fix involves reading the DSM, which acts as a fence,
before performing the compare.
> host_exerciser: fix erroneous buffer commpare

- tools/extra/hssi/ethernet/hssiloopback.py
- add port number command line argument   to Enable/Disable loopback per port
Example:
hssiloopback  --pcie-address 0000:0d:00.0 --loopback enable --port 1
> Tools: add port number command line argument  to hssi loopback

- .github/workflows/ccpp-tests.yml
- docker/docs/Dockerfile
* change github workflow job to build the docker image from the
Dockerfile instead of pulling it
* fix the docs/Dockerfile to
* use "-y"
* include package for libudev and libcap
> docs: build docker image instead of pulling

- ofs/apps/cpeng/hps.cpp
Add try/catch around allocate call and if an exception is caught, then
compare the byte size requested to the syttem page size. If the amount
is bigger than system page size, print more info about maybe requiring
hugepages reserved.
> cpeng: check for hugepages

- ofs/apps/cpeng/hps.cpp
* Change destination offset to the correct offset in memory where the
HPS boot will look for the image at
* Change to timeout to a smaller value
* Use std::chrono types to be more readable
* Change default image name to kernel.itb
> cpeng: change default CLI arg values

- ofs/umd/cpeng/ofs_cpeng.yml
Fix the following API functions to reference the shadow
registers/fields:
* hps_kernel_verify()
* hps_ssbl_verify()
> cpeng: fix API functions to use correct registers

- samples/hssi/hssi_10g_cmd.h
For some platforms, we cannot even manually specify an ethernet
interface name. In those cases, don't attempt to enable loopback
nor show the ethernet stats.
> hssi: add safeguard when no eth ifc is found

- ofs/apps/cpeng/hps.cpp
- ofs/umd/cpeng/ofs_cpeng.yml
Data request limit is dependent on PCIe read request.
Setting it to 512 is safer for PCIe cores that don't support reads
higher than 512.
> cpeng: add api to set data req. limit

- ofs/apps/cpeng/hps.cpp
* set default timeout to 1 sec
* check that chunk size is cacheline aligned and error out if not
* Add skip_ssbl_verify and skip_kernel_verify flags to tell the program to
not wait for either ssbl or kernel verify.
* Abstracted the wait_for_verify function:
* Take in the stage name (ssbl, kernel)  
* Take in the cpeng driver API function to call
> cpeng: cleanup

- opae.spec.in
Setting the capability for host_exerciser binary,
while installing the rpm time only.
Signed-off-by: ramyavv <ramyax.venkatesha@intel.com>
> Samples:Host_exerciser enhancement

- ofs/apps/cpeng/hps.cpp
- ofs/umd/cpeng/ofs_cpeng.yml
Add 'heartbeat' command to hps program.
This command reads the value of the hps2host_rsp register once a second
and verifies that it's incrementing in value. It will log if it detects
a heartbeat or not.
This also adds 'hps2host_rsp' API function in the umd spec.
> cpeng: add heartbeat command

- ofs/apps/cpeng/hps.cpp
data request limit is the PCIe transfer width that the copy engine IP
will use. It can be 64, 128, 512, or 1024 bytes.
This change ensures that chunk sizes are aligned with data request
limit.
> cpeng: change alignment to xfer limit

- python/pacsign/PACSign.md
- python/pacsign/pacsign/reader.py
- python/pacsign/setup.py
Bit swizzling should be enabled for SR, FACTORY, and SR_TEST.
> PACSign: swizzle all appropriate image types

- tools/fpgainfo/fmeinfo.c
> opae-sdk: disable fpga image info in fpgainfo

- opae-libs/libopae-c/pluginmgr.c
3da7d91d opae-c: fix plugin table (#236)
34aa6892 add bcce/bccf device ids to pluginmgr (#166)
git-subtree-split: 3da7d91def01afd4bd0dde8682d4300319be0a5a
> Squashed 'opae-libs/' changes from 5273ee74..3da7d91d

- python/opae.admin/opae/admin/fpga.py
Change the logic to always remove/disable AER on the root port.
When 'fpga' type is chosen, the flow will remove/disable AER on the
endpoints (including the target endpoint). Because the PCIe topology is
part of the 'fpga', then we should remove the root port no matter what.
> opae.admin: fix 'rsu fpga' command

- opae.spec.in
- samples/host_exerciser/CMakeLists.txt
- samples/host_exerciser/host_exerciser.h
- samples/host_exerciser/host_exerciser_cmd.h
-OFS release doesn’t support any global perf counters, so removed global perf counters code from Host Exerciser.
-Host Exerciser  reads Performance Counter  from DSM Status buffer.
DSM Status fromat:
Field Name	Range	Width	Description
Reserved	[511:288]	224	Reserved
Ab_error_info	[287:256]	32	Arbiter error info field
Reserved	[255:232]	24	Reserved
Penalty_end	[231:224]	8	Test end overhead in # clks
Reserved	[223:208]	16	Reserved
Penalty_start	[207:192]	16	Test start overhead in # clks
Num_writes	[191:160]	32	Total number of Writes sent / Total Num CX sent
Num_reads	[159:128]	32	Total number of Reads sent
Reserved	[127:104]	24	Reserved
Num_ticks	[103:64]	40	Number of clocks
ErrorVector	[63:32]	32	Errors detected
Reserved	[31:16]	16	Reserved
Dsm_number	[15:1]	15	Unique id for each dsm …
> Tools: Update Host Exerciser sample with DSM  performance counter.

- opae.spec.in
- samples/host_exerciser/CMakeLists.txt
- samples/host_exerciser/host_exerciser.h
- samples/host_exerciser/host_exerciser_cmd.h
-OFS release doesn’t support any global perf counters, so removed global perf counters code from Host Exerciser.
-Host Exerciser reads Performance Counter from DSM Status buffer.
DSM Status fromat:
Field Name Range Width Description
Reserved [511:288] 224 Reserved
Ab_error_info [287:256] 32 Arbiter error info field
Reserved [255:232] 24 Reserved
Penalty_end [231:224] 8 Test end overhead in # clks
Reserved [223:208] 16 Reserved
Penalty_start [207:192] 16 Test start overhead in # clks
Num_writes [191:160] 32 Total number of Writes sent / Total Num CX sent
Num_reads [159:128] 32 Total number of Reads sent
Reserved [127:104] 24 Reserved
Num_ticks [103:64] 40 Number of clocks
ErrorVector [63:32] 32 Errors detected
Reserved [31:16] 16 Reserved
Dsm_number [15:1] 15 Unique id for each dsm status …
> Tools: CP Host Exerciser sample with DSM performance counter

- tests/hello_fpga/test_hello_fpga_c.cpp
> tests: skip find_fpga0 for devices with no AFU

- tools/extra/opae.io/opae/io/utils.py
- tools/extra/opae.io/pymain.h
* refactor 'opae_register' class, 'read_guid' and 'dfh_walk' functions
* parameterize region
* remove reference to opae.io builtins
* use region read64|write64
* add 'walk' function to opae.io.utils
* walk the dfl and print out offset, value, uuid
* change 'walk_action' in pymain.h
* use 'walk' function in opae.io.utils
* default region argument to 0
> opae.io: make 'walk' interpreter independent

- tools/extra/opae.io/main.cpp
- tools/extra/opae.io/main.h
- tools/extra/opae.io/opae/io/utils.py
- tools/extra/opae.io/pymain.h
- tools/extra/opae.io/setup.py
- tools/extra/opae.io/vfiobindings.cpp
* update copyright date to include 2021
* remove unnecessary import in utils.py
* 
> opae.io: update copyright date to include 2021

- python/pacsign/setup.py
> PACSign: update version to 1.0.5 (openssl 1.1.1l)

- python/pacsign/PACSign.md
Add a table describing the required key naming conventions for
each image type.
> PACSign doc: add description of key naming

- tools/extra/hssi/ethernet/hssicommon.py
- tools/extra/hssi/ethernet/hssiloopback.py
- tools/extra/hssi/ethernet/hssimac.py
- tools/extra/hssi/ethernet/hssistats.py
- Fix  HSSI tool without any command line parameters.
- Accept an uppercase or lower case bdf
- Gracefully exit HSSI tools in non-privilege mode
- Fix Bogus HSSI read stats
**fix HSSI tool without any command line parameters:**
hssistats
usage: hssistats.py [-h] [--pcie-address PCIE_ADDRESS]
optional arguments:
-h, --help            show this help message and exit
--pcie-address PCIE_ADDRESS, -P PCIE_ADDRESS
sbdf of device to program (e.g. 0000:04:00.0).
Optional when one device in system.
**Accept an uppercase or lower case bdf:**
hssistats.py  -P  0000:B1:00.0
Namespace(pcie_address='0000:B1:00.0')
pcie_address: 0000:B1:00.0
sbdf: 0000:b1:00.0
FPGA dev: {'segment': 0, 'bus': 177, 'dev': 0, 'func': 0, 'path': '/sys/class/fpga_region/region0', 'pcie_address': '0000:b1:00.0'}
devs[0] …
> tools: HSSI tools command line argument validation

- tools/extra/qpafilter/qpafilter.py
Avoids anomalies due to the imprecise nature of floating-point
calculations.
> qpafilter: log floats with precision .2f

- python/pacsign/pacsign-tests.sh
- python/pacsign/pacsign/hsm_managers/openssl/key_manager.py
Image type FACTORY previously required _fim2_ to appear in the
image name. This update allows the string _factory_ to also
denote the FACTORY image type.
> (cherry-pick) PACSign: allow _fim2_ or _factory_ in image name (#2230)

- opae-libs/plugins/xfpga/sysfs.c
5117a9b8 plugins: xfpga: support sysfs file size 0 (#242)
git-subtree-split: 5117a9b813ac4800897ee457c5931f6fe3c8486f
> (cherry-pick) Squashed 'opae-libs/' changes from 3098f92e..5117a9b8

- python/pacsign/PACSign.md
Add a table describing the required key naming conventions for
each image type.
> (cherry-pick) PACSign doc: add description of key naming (#2234)

- tools/extra/qpafilter/qpafilter.py
- tools/fpgainfo/fpgainfo.c
- fpgainfo prints GUID 2 times
[root@PG16WVAW0272_SuperMicro_14 ALPHA]# fpgainfo port
//****** PORT ******//
Object Id                        : 0xEE00000
//****** PORT ******//
Object Id                        : 0x20B1000000000000
PCIe s:b:d.f                     : 0000:B1:00.1
Socket Id                        : 0x01
Accelerator Id                   : 1aae155c-acc5-4210-b9ab-efbd90b970c4
Accelerator GUID                 : 1aae155c-acc5-4210-b9ab-efbd90b970c4
> tools: remove second print Accelerator id

- opae-libs/libopaevfio/opaevfio.c
- opae-libs/plugins/vfio/opae_vfio.c
77c076bf VFIO: silence errors in prealloc mmap path (#249)
git-subtree-split: 77c076bfc0e61aade41dbd5e8ce0439f4bab2400
> Squashed 'opae-libs/' changes from 525b0e75..77c076bf

- tools/extra/qpafilter/qpafilter.py
Avoids anomalies due to the imprecise nature of floating-point
calculations.
> qpafilter: log floats with precision .2f (#2237)

- opae-libs/libopaevfio/opaevfio.c
- opae-libs/plugins/vfio/opae_vfio.h
83a4312d libopaevfio: fix coding style (#252)
3bc7308b libopaevfio: silence error output by default (#250)
git-subtree-split: 83a4312df38adc8aeaad96a7cdbf8791c254be21
> (cherry-pick) Squashed 'opae-libs/' changes from 77c076bf..83a4312d

- tools/extra/hssi/ethernet/hssicommon.py
- tools/extra/hssi/ethernet/hssiloopback.py
- tools/extra/hssi/ethernet/hssimac.py
- tools/extra/hssi/ethernet/hssistats.py
* tools: HSSI tools command line argument validation
- Fix  HSSI tool without any command line parameters.
- Accept an uppercase or lower case bdf
- Gracefully exit HSSI tools in non-privilege mode
- Fix Bogus HSSI read stats
> tools:(cherry-pcik) HSSI tools command line argument validation

- tools/fpgainfo/fpgainfo.c
* tools: remove second print Accelerator id
- fpgainfo prints GUID 2 times
[root@PG16WVAW0272_SuperMicro_14 ALPHA]# fpgainfo port
//****** PORT ******//
Object Id                        : 0xEE00000
//****** PORT ******//
Object Id                        : 0x20B1000000000000
PCIe s:b:d.f                     : 0000:B1:00.1
Socket Id                        : 0x01
Accelerator Id                   : 1aae155c-acc5-4210-b9ab-efbd90b970c4
Accelerator GUID                 : 1aae155c-acc5-4210-b9ab-efbd90b970c4
* tools: fix fpgainfo build error
> tools: (Cherry-pick)remove second print Accelerator id

- tools/fpgainfo/fpgainfo.c
* tools: remove second print Accelerator id
- fpgainfo prints GUID 2 times
[root@PG16WVAW0272_SuperMicro_14 ALPHA]# fpgainfo port
//****** PORT ******//
Object Id                        : 0xEE00000
//****** PORT ******//
Object Id                        : 0x20B1000000000000
PCIe s:b:d.f                     : 0000:B1:00.1
Socket Id                        : 0x01
Accelerator Id                   : 1aae155c-acc5-4210-b9ab-efbd90b970c4
Accelerator GUID                 : 1aae155c-acc5-4210-b9ab-efbd90b970c4
> CP tools: remove second print Accelerator id

- python/opae.admin/opae/admin/fpga.py
Change the logic to always remove/disable AER on the root port.
When 'fpga' type is chosen, the flow will remove/disable AER on the
endpoints (including the target endpoint). Because the PCIe topology is
part of the 'fpga', then we should remove the root port no matter what.
> Cherry-pick opae.admin: fix 'rsu fpga' command 

- python/opae.admin/opae/admin/tools/rsu.py
> (cherry-pick) rsu: fix bug when run with no args. (#2266)

- python/opae.admin/opae/admin/tools/pci_device.py
Original code referenced a typo of the argparse namespace variable
called 'devices'. Upon further review, the value in this variable is a
list because the 'type' function (pci_deivce) returns a list.
Instead of using this, use argv[1] as the filter is the first
positional argument.
This is a fix for #2278 
> opae.admin: fix msg when no devices found

- opae-libs/cmake/modules/OPAEGit.cmake
https://github.com/OPAE/opae-sdk/pull/2051 errantly changed this
opae-libs file in the opae-sdk tree. Bringing the two back into
sync..
The change in 2051 broke our application --version output. This
change corrects it.
> cmake: fix OPAEGit.cmake

- python/opae.admin/opae/admin/tools/rsu.py
Convert the sbdf to lowercase when comparing the two values
to allow both uppercase and lowercase.
> rsu: allow uppercase ssss:bb:dd.f

- python/opae.admin/opae/admin/fpga.py
- python/opae.admin/opae/admin/tools/rsu.py
The previous driver implementation provided
fpga_sec_mgr/fpga_secX/update/available_images and
fpga_sec_mgr/fpga_secX/update/image_load.
The new implementation uses
control/available_images and
control/image_load
Add support for both flavors.
Fix bug in rsu.py: os.EX_NOTFOUND not defined.
> (cherry pick) rsu: support old and new sysfs paths

- tools/extra/hssi/ethernet/hssicommon.py
- tools/extra/hssi/ethernet/hssiloopback.py
- tools/extra/hssi/ethernet/hssistats.py
- read_reg function returns error False if fails to read SAL command or returns True
- Change  poll time out to 100 microseconds
- remove  dead code in hssicommon.py
- fix python indentation
- fix hssiloopback  enable and disable output
> Tools: fix hssi  read register  function return error

- tools/fpgainfo/bmcdata.c
- tools/libboard/board_n6000/board_n6000.c
- fpgainfo reads SDM provision status and  prints values
- change bmc and security  output space format
> Tools: add SDM provision status info to  fpgainfo security

- tools/fpgainfo/bmcdata.c
- tools/libboard/board_n6000/board_n6000.c
- fpgainfo reads SDM provision status and  prints values
- change bmc and security  output space format
> Tools: CP add SDM provision status info to  fpgainfo security 

- python/pacsign/pacsign/reader.py
Updates the key checking logic to relax the requirement on key naming
for SR/SR_TEST/SR_CERT and PR/PR_TEST.
Previously, the strings '_fim_'/'_sr_test_'/'_sr_cert_' were required to appear in
the key names for SR/SR_TEST/SR_CERT. This change relaxes the restriction so
that a key with '_fim_' can also be used for SR_TEST/SR_CERT and vice-versa.
Likewise, the strings '_pr_'/'_pr_test_' were required to appear in
the key names for PR/PR_TEST. This change relaxes the restriction so
that a key with '_pr_' can also be used for PR_TEST and vice-versa.
> PACSign: allow SR/PR keys to apply to *_TEST

- python/pacsign/pacsign/reader.py
Updates the key checking logic to relax the requirement on key naming
for SR/SR_TEST and PR/PR_TEST.
Previously, the strings '_fim_'/'_sr_test_' were required to appear in
the key names for SR/SR_TEST. This change relaxes the restriction so
that a key with '_fim_' can also be used for SR_TEST and vice-versa.
Likewise, the strings '_pr_'/'_pr_test_' were required to appear in
the key names for PR/PR_TEST. This change relaxes the restriction so
that a key with '_pr_' can also be used for PR_TEST and vice-versa.
> (cherry-pick) PACSign: allow SR/PR keys to apply to *_TEST (#2344)

- tools/fpgainfo/board.c
- tools/libboard/board_common/board_common.c
- add fpgaDestroyProperties to free Properties object
Co-authored-by: Tim Whisonant <tim.whisonant@intel.com>
> Tools: (Cherry-Pick) fix fpgainfo memory leak 

- samples/host_exerciser/host_exerciser.h
- samples/host_exerciser/host_exerciser_cmd.h
- Read the AFU frequency from a new CSR.
- Add tests for PCIe atomic functions, including validating that each function
is performed properly.
- Fill the source buffer with random data instead of the same pattern over
and over so that read errors are more likely to be found.
- Make the log level work. Dump a few lines of the buffers in some modes.
> host_exerciser updates

- python/opae.admin/opae/admin/tools/fpgasupdate.py
- python/opae.admin/opae/admin/utils/progress.py
Format each time display to limit the precision to 2 digits
(hundredths of a second). This includes the standard logging
package output.
Use datetime.now() for timestamps in progress.py to correct an
accuracy error caused by using time.time() with datetime.timedelta.
> (cherry-pick) fpgasupdate: format time display / fix bug (#2346)

- samples/fpgaperf_counter/fpgaperf_counter.c
-  Width is not specified for 's' conversion specifier.
This can result in an overflow of the buffer provided in argument 3 of a call to 'fscanf'
> tools: fix static code analysis  overflow of the buffer

- samples/host_exerciser/host_exerciser.h
- samples/host_exerciser/host_exerciser_cmd.h
host_exerciser updates
- Read the AFU frequency from a new CSR.
- Add tests for PCIe atomic functions, including validating that each function
is performed properly.
- Fill the source buffer with random data instead of the same pattern over
and over so that read errors are more likely to be found.
- Make the log level work. Dump a few lines of the buffers in some modes.
> tools: CP host_exerciser updates 

- tools/libboard/board_n6000/board_n6000.c
- Array 'bom_info' of size 16384 may use index value(s) 16384..INT_MAX
- bom_info terminate with null character '\0'
> tools:  fix n6000 static code analysis issue -Buffer Overflow

- samples/fpgaperf_counter/fpgaperf_counter.c
-  Width is not specified for 's' conversion specifier.
This can result in an overflow of the buffer provided in argument 3 of a call to 'fscanf'
> tools: CP fix static code analysis  overflow of the buffer

- tools/libboard/board_n6000/board_n6000.c
- Array 'bom_info' of size 16384 may use index value(s) 16384..INT_MAX
- bom_info terminate with null character '\0'
> tools: CP fix n6000 static code analysis issue -Buffer Overflow

- afu-test/afu_test.h
- samples/host_exerciser/host_exerciser.h
- samples/host_exerciser/host_exerciser_cmd.h
- Add a new testall switch that runs through a series of tests.
- New encoding option selects dynamically between DM and PU encoding (or both).
- New continuous mode test can inject atomic requests as a small fraction of requests.
- New API version stored in hardware controls what tests are available.
- Setting the logging level now works.
> Lots of host_exerciser changes

- afu-test/afu_test.h
- samples/host_exerciser/host_exerciser.h
- samples/host_exerciser/host_exerciser_cmd.h
- Add a new testall switch that runs through a series of tests.
- New encoding option selects dynamically between DM and PU encoding (or both).
- New continuous mode test can inject atomic requests as a small fraction of requests.
- New API version stored in hardware controls what tests are available.
- Setting the logging level now works.
> tools: CP Lots of host_exerciser changes (#2368)

- tools/fpgainfo/errors.c
-fpgainfo errors  all output reformatting, remove duplicate output Object Id, PCIe s:b:d.f, Device Id, Socket Id. Ports Num, Bitstream Id, Bitstream Version, Pr Interface Id
After Reformat:
sudo ./bin/fpgainfo  errors all
//****** FME ******//
Object Id                        : 0xEF00000
Bitstream Id                     : 0x501020283CF60D7
Bitstream Version                : 5.0.1
Pr Interface Id                  : 43c10034-ed73-5816-8ed9-67944c5b53c0
//****** FME ERRORS ******//
PCIe0 Errors                     : 0x0
PCIe1 Errors                     : 0x0
Catfatal Errors                  : 0x0
Inject Errors …
> Tools: fpgainfo errors  all output reformat

- tools/libboard/board_n6000/board_n6000.c
- add fpga Ethernet ports link status
HSSI Link status CSR offset 0x818:
reserved (63:48) -- Reserved
rxpcsready (47:32) -- bit0 for port0
txlanestable (31:16) -- bit0 for port0
txplllocked (15:00) – bit0 for port0
if TX PLL locked, RX PCS ready and TX lanes are set   means links Status UP
if TX PLL locked, RX PCS ready and TX lanes are not set   means links Status DOWN
sudo ./bin/fpgainfo  phy
Intel N6000 Acceleration Development Platform
Board Management Controller, MAX10 NIOS FW version: 1.4.0
Board Management Controller, MAX10 Build version: 1.4.0
//****** PHY ******//
Object Id                        : 0xEF00000 …
> Tools: add fpgainfo phy  link status up/down

- tools/libboard/board_n6000/board_n6000.c
* Tools: add fpgainfo phy  link status up/down
- add fpga Ethernet ports link status
HSSI Link status CSR offset 0x818:
reserved (63:48) -- Reserved
rxpcsready (47:32) -- bit0 for port0
txlanestable (31:16) -- bit0 for port0
txplllocked (15:00) – bit0 for port0
if TX PLL locked, RX PCS ready and TX lanes are set   means links Status UP
if TX PLL locked, RX PCS ready and TX lanes are not set   means links Status DOWN
> Tools: CP add fpgainfo phy  link status up/down

- samples/host_exerciser/host_exerciser_cmd.h
Assign bitfields to a temporary variable before logging in order
to appease spdlog.
> host_exerciser: fix build on g++ 11.2.1

- samples/hssi/hssi_10g_cmd.h
When --he-loopback=on is given, keep the process alive by entering
a busy/wait loop. Break out of the loop on Ctrl+C. This is to avoid
any register reset (FLR) that may occur when the process exits.
> hssi: loop when --he-loopback=on

- tools/fpgainfo/errors.c
-fpgainfo errors  all output reformatting, remove duplicate output Object Id, PCIe s:b:d.f, Device Id, Socket Id. Ports Num, Bitstream Id, Bitstream Version, Pr Interface Id
After Reformat:
sudo ./bin/fpgainfo  errors all
//****** FME ******//
Object Id                        : 0xEF00000
Bitstream Id                     : 0x501020283CF60D7
Bitstream Version                : 5.0.1
Pr Interface Id                  : 43c10034-ed73-5816-8ed9-67944c5b53c0
//****** FME ERRORS ******//
PCIe0 Errors                     : 0x0
PCIe1 Errors                     : 0x0
Catfatal Errors                  : 0x0
Inject Errors …
> Tools: CP fpgainfo errors  all output reformat

- tools/libboard/board_n6000/board_event_log.c
Update fpgainfo events to latest register specs.
The failing check does not seem to have anything to do with my code. It complains about missing doxygen, kernel headers not installed, etc.
Co-authored-by: Esa Leskinen <ele@silicom.dk>
> tools: CP Update fpgainfo events to latest register specs 

- tests/board/test_board_n6000.cpp
- tools/libboard/board_n6000/board_n6000.c
* Add 2 new BOM Critical Components unit test cases
* Improved robustness of BOM info reformatting
Co-authored-by: Esa Leskinen <ele@silicom.dk>
> tools: CP N6000 BOM info reformatting & add test cases

- tools/fpgainfo/errors.c
- fpgainfo errors -c port returns errno 70 if one or more functions are bound to vfio-pci, Errors are supported by DFL driver port, so set fpgaPropertiesSetInterface to FPGA_IFC_DFL.
> tools: fix fpgainfo errors port command return error code

- tools/extra/opae.io/opae/io/utils.py
- tools/extra/opae.io/pymain.h
'dump' command can dump register values either in hex or binary and can
start at a given offset and end after a given count is reached.
When dumping to in hex, the offset is included.
> opae.io: add 'dump' command

- tools/extra/hssi/ethernet/hssistats.py
hissistats  tool  prints N/A if READ REG fails
removed hssistats  READ REG counter boundary checking, example  value_lsb >= 0xfffffff1   and value_msb >= 0xfffffff1
> tools: remove  hssistats  count max value checking

- tools/extra/hssi/ethernet/hssistats.py
hissistats  tool  prints N/A if READ REG fails
removed hissistats  READ REG counter boundary checking, example  value_lsb >= 0xfffffff1   and value_msb >= 0xfffffff1
> tools: CP remove  hissistats  count max value checking (#2418)

- doc/src/fpga_tools/opaevfio/opaevfio.md
- python/opae.admin/opae/admin/tools/opaevfio.py
On N6000, the VFs do not bind to dfl-pci by default; so, by default,
do not try to rebind them to dfl-pci on release.
> opaevfio: don't rebind on release by default

- python/opae.admin/opae/admin/tools/fpgasupdate.py
L255 calls fpgaconf.
L259 prepends fpgaconf's stdout to "\nPartial Reconfiguration failed".
However, fpgaconf uses stderr for readable error messages (see https://github.com/OPAE/opae-sdk/blob/5ebcb4cfc0602fdc68dbe509fcd8dbefc907083c/tools/fpgaconf/fpgaconf.c#L92)
> fpgasupdate: display error messages from fpgaconf

- samples/hssi/hssi_100g_cmd.h
* Loop on (new) PKT_TX_COUNT CSR before ending test.
* Display new BlockID CSR in dump.
* Implement controls for PKG_GEN_CTRL register.
> hssi: 100G test updates

- python/pacsign/pacsign/reader.py
Add SDM and SDM_TEST to the list of collateral types that need to
have the bits swizzled in the output image.
> pacsign: swizzle SDM and SDM_TEST

- python/pacsign/pacsign/reader.py
Add SDM and SDM_TEST to the list of collateral types that need to
have the bits swizzled in the output image.
> (cherry pick) pacsign: swizzle SDM and SDM_TEST (#2433)

- tools/extra/vabtool/vabtool
Appended error messages to SDM_SR_PROVISION_STATUS
8'h10 :  'SDM Provisioning Image configuration Failed; Shell image configured'
8'h11 :  'SR Key Hash provision ignored because SR Key Hash not programmed to BMC '
8'h12 :  'SDM Response mismatch during SDM Provisioning Image CONFIG_STATUS Check'
8'h13 :  'SDM Response mismatch during PUBKEY_PROGRAM command to SDM'
8'h14 :  'SR Key Hash provision request ignored because BMC is busy'
> Tools:  append new error messages to vabtool

- tools/extra/vabtool/vabtool
Appended error messages to SDM_SR_PROVISION_STATUS
8'h10 :  'SDM Provisioning Image configuration Failed; Shell image configured'
8'h11 :  'SR Key Hash provision ignored because SR Key Hash not programmed to BMC '
8'h12 :  'SDM Response mismatch during SDM Provisioning Image CONFIG_STATUS Check'
8'h13 :  'SDM Response mismatch during PUBKEY_PROGRAM command to SDM'
8'h14 :  'SR Key Hash provision request ignored because BMC is busy'
> Tools:  append new error messages to vabtool (#2437)

- tools/extra/vabtool/vabtool
Fix error in SDM status array definition. The previous change
caused two error messages to be concatenated instead of occupying
two unique indexes.
> vabtool: fix status array definition

- tools/extra/vabtool/vabtool
Fix error in SDM status array definition. The previous change
caused two error messages to be concatenated instead of occupying
two unique indexes.
> (cherry pick) vabtool: fix status array definition (#2445)

- samples/hssi/hssi_100g_cmd.h
Add the rx_count register to the list of registers printed out
at the end of the program.  Wait until the packets have been sent
before printing the register contents.
> samples: hssi: print rx_count

- tests/board/test_board_n6000.cpp
- tools/libboard/board_n6000/board_n6000.c
Device id & vendor id is same for Intel fpga N6000 & N6100 cards
Make generic name for fpga bmc version  and fpga card
Example:
Intel Acceleration Development Platform
Board Management Controller NIOS FW version: 1.0.4
Board Management Controller Build version: 1.0.6
> opae-sdk: generic name for fpgainfo bmc   and fpga card

- python/opae.admin/opae/admin/fpga.py
The pmci_bus attribute returns a path that is rooted at
'*-sec*.*.auto', so there is no need to search further.
Searching further within that directory yields no result, causing
the script to error out.
> opae.admin: rsu: fix secure_update for pmci

- opae.spec.rhel
> rhel rpm: add missing hssi files

- tests/board/test_board_n5010.cpp
- tools/libboard/board_common/board_common.c
- tools/libboard/board_common/board_common.h
- tools/libboard/board_n5010/board_n5010.c
- tools/libboard/board_n5010/board_n5010.h
- tools/libboard/board_n6000/board_n6000.c
Example:
Number of MACs                   : 2
MAC address 0                    : 00:E0:ED:5C:72:E0
MAC address 1                    : 00:E0:ED:5C:72:E1
> tools: align fpgainfo mac for N5010 with N6000

- tools/extra/hssi/ethernet/hssimac.py
HSSI subsystem doesn’t  support set mtu command
> Tools:  remove hssimac mtu command

- tools/extra/opae.io/opae/io/utils.py
Convert register values to bytes when dumping to binary format.
> opae.io: fix dump for binary format

- opae.spec.fedora
rpmlint opae-2.0.9-1.fc33.x86_64.rpm
opae.x86_64: E: explicit-lib-dependency libcap
opae.x86_64: E: explicit-lib-dependency libedit
opae.x86_64: E: non-executable-script /usr/lib/python3.9/site-packages/opae/admin/tools/fpgareg.py 644 /usr/bin/env python3
opae.x86_64: E: postin-without-ldconfig /usr/lib64/libbitstream.so.2.0.10
opae.x86_64: E: postin-without-ldconfig /usr/lib64/libfpgad-api.so.2.0.10
opae.x86_64: E: postin-without-ldconfig /usr/lib64/libmml-srv.so.2.0.10
opae.x86_64: E: postin-without-ldconfig /usr/lib64/libmml-stream.so.2.0.10
opae.x86_64: E: postin-without-ldconfig /usr/lib64/libofs.so.2.0.10
opae.x86_64: E: postin-without-ldconfig /usr/lib64/libopae-c++-nlb.so.2.0.10
opae.x86_64: E: postin-without-ldconfig /usr/lib64/libopae-c++-utils.so.2.0.10
opae.x86_64: E: …
> opae-sdk: fix fedora rpmlint errors

- python/opae.admin/opae/admin/utils/verifier.py
When printing the Bitstream Version field, the slice specifier
was chopping off the last valid byte. Increment it by one to fix.
> bitstreaminfo: fix one-off error

- tests/framework/mock/test_fpgad/monitor_thread.c
> test_fpgad: use sched_yield instead of pthread_yield

- binaries/fpgad/plugins/fpgad-vc/fpgad-vc.c
> fpgad: fix error in sysfs path to match N5010

- binaries/fpgad/monitored_device.c
N6100 bitstreams doesn’t support PR interface id , fpgad exits with error message “Failed to get PR interface id”
Fpgad monitor sensors in case of not supported support PR interface id
> Tools:  fpgad monitor sensors for  No PR interface id  bitstreams.

- external/CMakeLists.txt
The PRESERVE_REPOS option for opae_external_project_add was not
specifying that OPAE_PRESERVE_REPOS be honored. This was resulting
in a weird error caused by double-cloning of pybind11 when trying
to create RPMs.
> pybind11: honor OPAE_PRESERVE_REPOS

- python/opae.admin/opae/admin/tools/opaevfio.py
Catch any OSError exception that occurs when attempting to write
the new_id sysfs node. Print the exception and exit if it is not EEXIST,
else continue.
Catch exception generated when writing to drivers/dfl-pci/bind. If
the driver enumeration does not claim the device, this will result in
an OSError exception.
> opaevfio.py: catch write to new_id exception

- binaries/opae.io/opae/io/utils.py
- python/opae.admin/opae/admin/tools/opaevfio.py
On recent kernels, eg >= 5.15, writing to new_id on the first attempt
after creating the VFs successfully binds the VF to vfio-pci. However,
after the VF is released, trying to bind it again without an explicit
write to vfio-pci's bind sysfs node fails. Handle EBUSY in the case
that the driver bind is attempted after the first write to new_id.
On subsequent writes to new_id, explicit binding is required.
> opaevfio, opae.io: explicitly bind to vfio-pci

- binaries/fpgad/plugins/fpgad-vc/fpgad-vc.c
dfl-fme.X/errors/errors changed to dfl-fme.X/errors/fme_errors
during driver upstreaming. Support both names when detecting SEU.
> fpgad: search errors/fme_errors for SEU

- binaries/opae.io/opae/io/utils.py
* Add 32-bit register support by modifying opae_register class
* Change the `define` class member to take a width parameter
* Create a width attribute in the dynamicaly created type
* Use the `width` attribute in the constructor of the register class
to determine which read/write method to use for reading/writing from
the region.
* Made several spacing fixes to fix Python code style
* Changed the __str__ method to use format string (f'')
> opae.io: add 32 bit support

- cmake/modules/OFS.cmake
- libraries/scripts/ofs/ofs_parse.py
This modifies ofs_parse to support dumping a register spec into binary
format. To support this:
* a dump and its parser were added
* schema and use-local-refs CLI args were moved to the main parser
* lo, hi, width methods were added to register structure
* bitfield64 method was added to create a union of bitfields dynamically
> dfh: add support for dumping registers in binary

- libraries/pyopae/CMakeLists.txt
- libraries/pyopae/setup.py
- opae.spec.fedora
- packaging/opae/rpm/create
Some of the Python projects in the tree were not being invoked
(the "setup.py install" was not being done), notably the OPAE
Python bindings. This change ensures that each of the projects'
setup.py's are being called and packaged.
> packaging: add missing packages to Fedora RPM

- opae.spec.fedora
- opae.spec.rhel
Keep the opae.rpm and opae-devel.rpm contents the same between
RHEL and Fedora. Place additional collateral that is not
available in RHEL into a new 3rd Fedora RPM opae-extra-tools.rpm.
> packaging: create opae-extra-tools RPM for Fedora

- doc/src/fpga_tools/rsu/rsu.md
- python/opae.admin/opae/admin/fpga.py
- python/opae.admin/opae/admin/sysfs.py
- python/opae.admin/opae/admin/tools/rsu.py
* add `supports_ecap` method to pci_node class
* currently hard coded to support DPC and AER
* uses setpci to read the base register given by extended capability
(ECAP). If non-zero is returned then the pci device does not support
the given capability.
* refactor `safe_rsu_boot` to check for support of DPC and AER prior to
performing the actual rsu routine.
* Move the rsu routine (with removing, rescanning, etc.) to
`rsu_routine` method.
* If DPC is supported (or if `force` is True in the **kwargs) then
perform the rsu routine
* If AER is supported then disable AER using the context manager
`disable_aer`
* modiufy rsu.py to add a '--force' CLI argument and use this in the
subparser functions when calling `device_rsu`
* Update rsu.md doc to call out --force CLI argument and explain how it …
> opae.admin: handle DPC and AER capabilities

- python/opae.admin/opae/admin/tools/opaevfio.py
- tools/extra/opae.io/opae/io/utils.py
On recent kernels, eg >= 5.15, writing to new_id on the first attempt
after creating the VFs successfully binds the VF to vfio-pci. However,
after the VF is released, trying to bind it again without an explicit
write to vfio-pci's bind sysfs node fails. Handle EBUSY in the case
that the driver bind is attempted after the first write to new_id.
On subsequent writes to new_id, explicit binding is required.
> (cherry pick) opaevfio, opae.io: explicitly bind to vfio-pci (#2485)

- opae.spec.fedora
- opae.spec.rhel
- packaging/opae/rpm/create
Create new opae-ase.rpm, following the packaging method from
the cmake-based RPM creation.
> (cherry-pick) packaging: add ASE to packaging/opae/rpm/create (#2501)

- python/opae.admin/opae/admin/fpga.py
- python/opae.admin/opae/admin/sysfs.py
- python/opae.admin/opae/admin/tools/rsu.py
* opae.admin: add error checking to supports_ecap
Put the call to the subprocess in a try/except block and return False if
it fails.
`device_rsu` wasn't passing the **kwargs to `safe_rsu_boot` which meant
that --force was not being honored. This fixes it by passing in
**kwarrgs to `safe_rsu_boot`.
improve err handling in rsu
In fpga.py:
* Add log messages for
* debug level when DPC is suported
* warn level when force is being used
* raise an IOError when DPC and AER aren't supported
In rsu.py:
* Catch IOError as err and use it when logging
> opae.admin: (cherry-pcik)add error checking to supports_ecap (#2499)

- samples/mem_tg/tg_test.h
cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
> opae-sdk: fix clang build errors

- CMakeLists.txt
- external/CMakeLists.txt
- libraries/libopae-c/CMakeLists.txt
- opae.spec.in
- samples/CMakeLists.txt
- scripts/cover.sh
- scripts/unit-tests.sh
> opae-sdk: remove ase sim build flag

- binaries/opae.io/CMakeLists.txt
- cmake/modules/Findlibedit.cmake
- opae.spec.fedora
- opae.spec.rhel
Resolves the following warning:
The package name passed to `find_package_handle_standard_args` (libedit)
does not match the name of the calling package (edit).  This can lead to
problems in calling code that expects `find_package` result variables
(e.g., `_FOUND`) to follow a certain pattern.
> cmake: Findedit.cmake -> Findlibedit.cmake

- python/opae.admin/opae/admin/sysfs.py
When AER or DCP is supported `setpci` prints value to stdout. That is noise.
There is no need for full path for `setpci` it is already used without.
This was introduced in (#2495) commit de1e57abd.
> opae.admin: remove unintended print from setpci in `supports_ecap`

- cmake/modules/Findspdlog.cmake
CMake Warning (dev) at cmake/modules/Findspdlog.cmake:75 (set):
implicitly converting 'PATHS' to 'STRING' type.
> cmake: fix warning in Findspdlog.cmake

- libraries/pyopae/opae/fpga/__init__.py
Add IFC_DFL, IFC_VFIO, and IFC_SIM to exports.
> pyopae: fix extension module import statements

- libraries/pyopae/opae/fpga/__init__.py
Add IFC_DFL, IFC_VFIO, and IFC_SIM to exports.
> (cherry-pick) pyopae: fix extension module import statements (#2541)

- binaries/hssi/ethernet/hssicommon.py
- binaries/hssi/ethernet/hssiloopback.py
- binaries/hssi/ethernet/hssimac.py
- binaries/hssi/ethernet/hssistats.py
- HSSI tools support both dffv0 and dfhv0.5 versions
- HSSI CSR offset changed in dfhv0.5, HSSI tools verifies DFH version and sets offset
- Added new HSSI debug and TSE control registers.
> opae-sdk: add  dfhv0.5 support to hssi tools

- include/opae/cxx/core/properties.h
- libraries/libopaecxx/src/properties.cpp
- tests/opae-cxx/test_properties_cxx_core.cpp
> c++ bindings: add subsystem_vendor/device IDs.

- libraries/plugins/vfio/dfl.c
- libraries/plugins/vfio/dfl.h
* Add typedefs for pointers to structures that represent mmio space in
the dfl
* Whenever those structure pointers are used for mmio, replace the
declaration with the typedef
> vfio-plugin: use volatile pointers for mmio

- binaries/fpgaconf/CMakeLists.txt
- cmake/modules/OPAECompiler.cmake
- libraries/libbitstream/CMakeLists.txt
- libraries/libofs/CMakeLists.txt
- libraries/libopae-c/CMakeLists.txt
- libraries/libopaecxx/CMakeLists.txt
- libraries/libopaemem/CMakeLists.txt
- libraries/libopaeuio/CMakeLists.txt
- libraries/libopaevfio/CMakeLists.txt
Realizing that not all targets should be imported by external CMake
projects, I've narrowed down the list of targets to the following:
* opae-c
* opae-cxx-core
* opaemem
* ofs
* opaeuio
* opaevfio
* bitstream
* fpgaconf
For this, I've modified the opae_add_executable and
opae_add_shared_library functions to take in an optional one-value
argument to indicate the export name. I've modified the CMakeLists.txt
that are used for building the targets listing above to add the EXPORT
argument in the add target directive.
> build: reduce targets that are exported

- libraries/libopae-c/CMakeLists.txt
Install adapter.h so to facilitate the development of a project
implemeting a plugin.
> build: export adapter.h into include/opae/plugin

- opae.spec.fedora
- opae.spec.rhel
- packaging/opae/deb/create
- packaging/opae/deb/opae-devel.dirs
* Modify RPM spec files to include cmake configuration directory installed
in <prefix>/lib/opae-<version>
* Modify debian build scripts/input files to account for cmake
configuration directory inside the "dev" package
> packaging: export cmake config files

- CMakeLists.txt
- cmake/pkg/opae-config.cmake.in
- libraries/libopae-c/CMakeLists.txt
- libraries/libopae-c/plugin.h
* add plugin.h for plugin development
* Add plugin.h that includes headers that can be used in plugins
* Install new plugin.h as well as adapter.h, opae_int.h, and props.h
* export OPAEGit.cmake
* Install OPAEGit.cmake into <prefix>/lib/opae-<version>/modules 
* Add the modules path to CMAKE_MODULE_PATH so that developers can
include OPAE cmake modules
Currently only OPAEGit.cmake is being installed into this module path
(as opposed to the modules being installed in RPM packages).
Eventually, we need to only install modules that make sense for
developers. Also, we need to structure modules so that they can be
consumed by other software that is importing opae cmake configuration.
For now OPAEGit.cmake is potentially installed in two places.
> build: add plugin.h, export OPAEGit.cmake

- opae.spec.fedora
- opae.spec.rhel
- packaging/opae/deb/opae-devel.install
include opae/plugin/*.h in spec files for fedora and rhel
> packaging: include 'include/opae/plugin' in specs

- binaries/opae.io/opae/io/utils.py
Change pci_address parser function to always return pci address in lower
case becasue sysfs operates in lower case hex.
> opae.io: return pci_address in lower case

- samples/host_exerciser/host_exerciser.h
specifies how many requests to interleave when TestMode = 3'b011
Ex. 3'b000 - Rd,Wr,Rd,Wr
Ex. 3'b001 - Rd, Rd, Wr, Wr
Ex. 3'b010 - Rd, Rd, Rd, Rd, Wr, Wr, Wr, Wr
Not used when TestMode != 3'b011
host exerciser interleave range from 0 to 2
> opae-sdk: add range check to host exerciser cmd line input  interleave

- binaries/fpgametrics/fpgametrics.c
- libraries/libopae-c/adapter.h
- libraries/libopae-c/pluginmgr.c
This adds a prototype in adapter.h and implements it in pluginmgr.c
This function is meant to register a plugin given only the plugin module
name. This allows client code to register a plugin and not have to rely
on built-in plugin loading and configuration.
> pluginmgr: add API to register a plugin

- cmake/modules/OPAECompiler.cmake
- libraries/libopae-c/CMakeLists.txt
* Modify opae_add_static_library to accept EXPORT argument and export
use cmake install with EXPORT when present.
* Modify CMakeLists.txt in libopae-c to also generate a static library
of libopae-c.
> build: add 'EXPORT' got opae_add_static_library

- libraries/plugins/xfpga/error.c
- tests/opae-c/test_error_c.cpp
Older versions of the driver exported inject_error. The most recent
driver creates inject_errors. Support both versions.
> errors API: add "inject_errors" as clearable

- CMakeLists.txt
- cmake/modules/OPAEPlugin.cmake
- opae.spec.fedora
- opae.spec.rhel
* define cmake function called opae_add_shared_plugin that creates a
shared library that registers a plugin as defined by its PLUGIN
argument. To make the shared library it:
* writes a file with C code implementing a library constructor that
registers a plugin
* adds any source files as listed after the SOURCE keyword
* links this to opae-c-archive
The end result is a shared library that implements the OPAE API but has
the named plugin registered when the library loads.
> build: add OPAEPlugin.cmake

- libraries/plugins/xfpga/sysfs.c
An issue was identified with a sysfs file that contained a single 0.
In that case, the obj->max_size value was being set to 2, which caused
a subsequent fpgaObjectWrite64() call (with size > 2) to fail. Setting
the default size large enough to accomodate most sysfs entries prevents
this issue from occurring.
> xfpga: sysobject: use minimum sysfs file size

- binaries/opae.io/opae/io/utils.py
- binaries/opae.io/pymain.h
* Add --access-mode CLI argument
* Setting access mode sets utils.ACCESS_MODE accordingly
* Modify opae.io actions to read/write registers in 32 bit mode
> opae.io: add 32-bit support for actions

- binaries/opae.io/pymain.h
access_mode is not an attribute of the namespace object passed into
actions (like peek/poke). This PR changes the peek/poke action to
reference utils.ACCESS_MODE instead of args.access_mode.
> opae.io: fix reference to access_mode

- cmake/modules/OPAEPlugin.cmake
- libraries/libopae-c/init.c
* Set the priority for libopae-c constructor to 1000.
* Extend cmake function opae_add_shared_plugin to take in PRIORITY
argument but default to 1100. This allows setting the priority in
cmake so that the constructor generated includes the priority in the
constructor attribute.
> plugin: add priority to c'tors

- doc/src/fpga_api/quick_start/readme.md
- Fix typos.
- Fix grammar (missing articles, missing verbs, and general construction of sentences).
- Filter personal account information from examples.
- Fix BKM for Markdown (no closing headers, careful use of blank lines and indentation,...).
- Fix directives for Sphinx (using native fences, with appropriate nesting where needed).
> Typos, grammar, Markdown, Sphinx directives

- tests/framework/mock/opae_fixtures.h
- tests/xfpga/test_afu_metrics_c.cpp
- tests/xfpga/test_bmc_c.cpp
- tests/xfpga/test_buffer_c.cpp
- tests/xfpga/test_common_c.cpp
- tests/xfpga/test_enum_c.cpp
- tests/xfpga/test_error_c.cpp
- tests/xfpga/test_events_c.cpp
- tests/xfpga/test_metadata_c.cpp
- tests/xfpga/test_metrics_c.cpp
- tests/xfpga/test_metrics_max10_c.cpp
- tests/xfpga/test_metrics_utils_c.cpp
- tests/xfpga/test_metrics_vector_c.cpp
- tests/xfpga/test_mmio_c.cpp
- tests/xfpga/test_mock_errinj_c.cpp
- tests/xfpga/test_object_c.cpp
- tests/xfpga/test_open_close_c.cpp
- tests/xfpga/test_plugin_c.cpp
- tests/xfpga/test_properties_c.cpp
- tests/xfpga/test_reconf_c.cpp
- tests/xfpga/test_sysfs_c.cpp
- tests/xfpga/test_threshold_c.cpp
- tests/xfpga/test_umsg_c.cpp
- tests/xfpga/test_usrclk_c.cpp
- tests/xfpga/test_version_c.cpp
- tests/xfpga/test_wsid_list_c.cpp
Also, add specific device identification in
opae_base_p<>::device_filter() so that the tests will run on multi-card
systems.
> tests: refactor xfpga tests to new fixtures.

- opae.spec.rhel
> packaging: rhel: add missing file opae/io/pci.py

- binaries/opae.io/opae/io/pci.py
- binaries/opae.io/opae/io/utils.py
Older versions of Python 3 don't comprehend `default` named parameter.
This wraps creating a pci_id object with a make_id function that
defaults subsystem_vendor/subsystem_device to 0.
> opae.io: fix pci_id for older Python versions

- binaries/opae.io/opae/io/utils.py
Add dfh1 register struct and change the `dfh_walk` routine to:
* default `header` parameter to None
* parse the header as a dfhv1, then change it to:
* `header` class passed in as an argument
* dfh0 if version is 0
> opae.io: add support for dfh v1

- binaries/opae.io/pymain.h
Setting nargs to ? indicates it's optional allowing it to use the
default 'root:root' when omitted in the command line.
> opae.io: fix init action to use default user/group

- cmake/modules/OPAETest.cmake
- libraries/plugins/xfpga/CMakeLists.txt
- libraries/plugins/xfpga/bitstream.c
- libraries/plugins/xfpga/close.c
- libraries/plugins/xfpga/enum.c
- libraries/plugins/xfpga/error.c
- libraries/plugins/xfpga/event.c
- libraries/plugins/xfpga/metrics/bmc/CMakeLists.txt
- libraries/plugins/xfpga/metrics/bmc/bmc.c
- libraries/plugins/xfpga/metrics/bmc/bmc_ioctl.c
- libraries/plugins/xfpga/metrics/metrics_max10.c
- libraries/plugins/xfpga/metrics/metrics_utils.c
- libraries/plugins/xfpga/metrics/threshold.c
- libraries/plugins/xfpga/metrics/vector.c
- libraries/plugins/xfpga/opae_drv.c
- libraries/plugins/xfpga/open.c
- libraries/plugins/xfpga/properties.c
- libraries/plugins/xfpga/sysfs.c
- libraries/plugins/xfpga/sysobject.c
- libraries/plugins/xfpga/usrclk/fpga_user_clk.c
- libraries/plugins/xfpga/wsid_list.c
- tests/framework/mock/opae_std.c
- tests/framework/mock/opae_std.h
- tests/framework/mock/test_system.cpp
- tests/framework/mock/test_system.h
eg, instead of calling malloc() directly, call opae_malloc().
> test framework: replace std C calls with opae_X 

- python/pacsign/pacsign/hsm_managers/openssl/openssl.py
Allow the version check to perform exact match or match based on
regex pattern.
> pacsign: enable on CentOS 8 Stream / fix bug

- samples/mem_tg/mem_tg.h
- samples/mem_tg/tg_test.h
Adding `pattern` parameter to the `mem_tg` application:
default set to `fixed` 
Supported values are
- `fixed`
- `prbs7`
- `prbs15`
- `prbs31`
- `rot1` (rotating 1)
also added first data error report to application
Sample run
```
$ mem_tg --loops 0x1 -r 10 -w 10 --bls 64 --stride 64 -m 0 --data fixed tg_test 
[2022-05-19 13:40:57.034] [tg_test] [info] starting test run, count of 1
Memory channel clock frequency unknown. Assuming 300 MHz.
TG PASS
Mem Clock Cycles: 1411
freq (MHz): 300time (ticks): 1411
Write BW: 8.70872 GB/s
Read BW: 8.70872 GB/s
[2022-05-19 13:40:57.035] [tg_test] [info] Test tg_test(1): PASS
$ mem_tg --loops 0x1 -r 10 -w 0 --bls 64 --stride 64 -m 0 --data prbs31 tg_test     
[2022-05-19 13:41:15.266] [tg_test] [info] starting test run, count of 1
Memory channel clock …
```
> add data pattern config to mem_tg test

- opae.spec.fedora
Set __cmake_builddir conditionally to enable full builds on RHEL8.2.
> packaging: Fedora: update for RHEL8.2

- binaries/fpgadiag/opae/__init__.py
- binaries/fpgadiag/opae/diag/__init__.py
- binaries/fpgadiag/setup.py
- binaries/opae.io/opae/__init__.py
- binaries/opae.io/opae/io/__init__.py
- binaries/opae.io/setup.py
- docker/centos7.6/Dockerfile
- libraries/pyopae/CMakeLists.txt
- libraries/pyopae/opae/__init__.py
- libraries/pyopae/opae/fpga/__init__.py
- libraries/pyopae/setup.py
- opae.spec.fedora
- opae.spec.rhel
- packaging/opae/deb/opae.install
- python/opae.admin/opae/__init__.py
- python/opae.admin/opae/admin/__init__.py
- python/opae.admin/opae/admin/tools/__init__.py
- python/opae.admin/opae/admin/utils/__init__.py
- python/opae.admin/setup.py
Since we no longer need to support Python 2, this change makes it so
that all Python namespace packages follow PEP 420 for native namespace
packages per the packaging user guide:
https://packaging.python.org/en/latest/guides/packaging-namespace-packages
> python: fix python namespace packages

- samples/hssi/hssi_100g_cmd.h
Fix hssi port changes to make backward compatible
with old CLI11 versions
Signed-off-by: Nikhil Rane <nikhil.rane@intel.com>
> hssi: Fix RHEL_8.2 build issue

- libraries/libboard/board_c6100/board_c6100.c
> opae-sdk:  fix  fpaginfo image info typo

- binaries/opae.io/main.cpp
- binaries/opae.io/opae/io/utils.py
- binaries/opae.io/vfiobindings.cpp
1) When run without arguments, the code calls into
opae/io/utils.py::find_device() with the device parameter
equal to None. The for loop in find_device() was flawed
and caused an exception. The utils.py change fixes that
error.
2) The lifetime management of the global variables the_device and
the_region were incorrect. The previous code assumed that pybind11
had full ownership (the default) of these objects such that they
would be tracked in a std::unique_ptr and destroyed. However, the
main.cpp code is also able to destroy and replace these objects.
Removing the unique_ptr designation and adding
py::return_value_policy::reference to the definition of open()
function tells pybind11 that it should be hands off with the
return values of this function.
Signed-off-by: Tim Whisonant …
> opae.io: fix two issues

- binaries/fpgainfo/board.c
The existing N5010/N5011 board images have subvendor id = 0.
As checking subvendor and subdevice id has been added, the table must match.
> fpgainfo: fix N5010 subvendor id to allow board plugin to be loaded

- external/CMakeLists.txt
Fedora 37 python version 3.11 and compatible pybind 11 version 2.9.2
> opae-sdk: fix pybind build error on Fedora 37

- binaries/fpgainfo/board.c
There are some old n6000 cards with a 0 subdevice id.
To be handled by libboard_n6000.so, this entry is needed.
fpgainfo fme
before:
//****** FME ******//
Object Id                        : 0xEB00000
PCIe s:b:d.f                     : 0000:0D:00.0
Vendor Id                        : 0x8086
SubVendor Id                     : 0x8086
SubDevice Id                     : 0x0000
Bitstream Id                     : 0x5010602FE05BDA1
Bitstream Version                : 5.0.1
Pr Interface Id                  : d43642b4-c298-5631-823a-6735bb92b21f
after:
Intel Open FPGA Stack Platform
Board Management Controller NIOS FW version: 65.5.0
Board Management Controller Build version: 65.5.0 …
> n6000: handle a 0 subdevice

- binaries/opae.io/opae/io/utils.py
It was erroneously set to 0x138e. It should be 0x138d.
> opae.io: fix subsystem device ID for d5005

- binaries/fpgainfo/board.c
There are some old n6000 cards with a 0 subdevice id.
To be handled by libboard_n6000.so, this entry is needed.
fpgainfo fme
before:
//****** FME ******//
Object Id                        : 0xEB00000
PCIe s:b:d.f                     : 0000:0D:00.0
Vendor Id                        : 0x8086
SubVendor Id                     : 0x8086
SubDevice Id                     : 0x0000
Bitstream Id                     : 0x5010602FE05BDA1
Bitstream Version                : 5.0.1
Pr Interface Id                  : d43642b4-c298-5631-823a-6735bb92b21f
after:
Intel Open FPGA Stack Platform
Board Management Controller NIOS FW version: 65.5.0
Board Management Controller Build version: 65.5.0 …
> n6000: (Cherry-pick) handle a 0 subdevice (#2675)

- binaries/opae.io/opae/io/utils.py
- binaries/opae.io/pymain.h
Verifies that the next offset field when walking the DFL is aligned
per the active ACCESS_MODE. If it is not properly aligned, raise
an exception without dereferencing the offset.
> opae.io: (Cherry-pick) add --safe option to walk command (#2667)

- doc/src/fpga_tools/rsu/rsu.md
- python/opae.admin/opae/admin/tools/rsu.py
Add types 'sr', 'pr', 'sr_cancel', 'pr_cancel' to the sdm option,
as specified by the --type option.
eg, $ rsu sdm --type=sr_cancel <PCI_ADDRESS>
> rsu: (Cherry-pick) add --types to 'sdm' command (#2670)

- packaging/opae/rpm/create
It was reported that the wildcard doesn't work with Fedora 37. Move
to an explicit check on the name instead.
Add libedit-devel and systemd-devel to the list of prerequisites for
the full package build.
> packaging: (Cherry-pick) remove python3*-devel wildcard (#2656)

- doc/src/fpga_tools/rsu/rsu.md
- python/opae.admin/opae/admin/tools/rsu.py
It was determined that these are no longer needed.
> rsu: (Cherry-pick) remove sr_cancel, pr_cancel from sdm command (#2677)

- python/opae.admin/opae/admin/fpga.py
- python/opae.admin/opae/admin/sysfs.py
- python/opae.admin/opae/admin/tools/fpgasupdate.py
- python/opae.admin/opae/admin/version.py
The secure device manager changed back to a sysfs-driven mechanism;
but instead of writing the firmware file name to a sysfs node, the
mechanism is to write '1' to "loading", followed by writing the binary
file to "data", followed by writing '0' to "loading". Implement this
new method alongside the existing sysfs method to preserve backwards
compatibility.
> fpgasupdate: changes related to new SDM driver

- python/opae.admin/opae/admin/tools/rsu.py
Add --wait command line parameter to control the amount of time
to wait after a Remote System Update has been triggered before
rescanning the PCI bus.
> rsu: add --wait command line parameter

- doc/src/fpga_tools/rsu/rsu.md
- python/opae.admin/opae/admin/tools/rsu.py
This reverts commit 0d22d0941672e8caae8fdae1c0b0706d9efdab73.
It has been determined that these options are, in fact, required.
Signed-off-by: Russ Weight <russell.h.weight@intel.com>
> Revert "rsu: remove sr_cancel, pr_cancel from sdm command (#2677)"

- doc/src/fpga_tools/rsu/rsu.md
- python/opae.admin/opae/admin/tools/rsu.py
This reverts commit 0d22d0941672e8caae8fdae1c0b0706d9efdab73.
It has been determined that these options are, in fact, required.
Signed-off-by: Russ Weight <russell.h.weight@intel.com>
> Revert  (Cherry-pick) "rsu: remove sr_cancel, pr_cancel from sdm command (#2677)"

- python/opae.admin/opae/admin/tools/rsu.py
Add --wait command line parameter to control the amount of time
to wait after a Remote System Update has been triggered before
rescanning the PCI bus.
> rsu: (cherry-pick) add --wait command line parameter

- python/opae.admin/opae/admin/fpga.py
- python/opae.admin/opae/admin/sysfs.py
- python/opae.admin/opae/admin/tools/fpgasupdate.py
- python/opae.admin/opae/admin/version.py
The secure device manager changed back to a sysfs-driven mechanism;
but instead of writing the firmware file name to a sysfs node, the
mechanism is to write '1' to "loading", followed by writing the binary
file to "data", followed by writing '0' to "loading". Implement this
new method alongside the existing sysfs method to preserve backwards
compatibility.
> fpgasupdate: (Cherry-pick) changes related to new SDM driver

- doc/src/fpga_tools/hssi_ethernet/hssimac.md
- remove mtu command from hssismac documentation
> opae-sdk: (cherry-pick) fix  hssismac documentation (remove mtu command) (#2696)

- samples/host_exerciser/host_exerciser.h
- samples/host_exerciser/host_exerciser_cmd.h
Remains backward compatible with older systems. Unfortunately, this means
assuming that older machines do work with atomics. On future OFS systems,
"host_exerciser --testall true" will skip atomic tests if unsupported.
> Add a CSR field indicating PCIe atomics support to avoid problems on older machines

- platforms/scripts/afu_synth_setup
This API was apparently undocumented, and it was removed altogether in
the 3.7 timeframe: https://bugs.python.org/issue33666
> Don't use the deprecated and removed os.errno

- platforms/scripts/afu_synth_setup
This API was apparently undocumented, and it was removed altogether in
the 3.7 timeframe: https://bugs.python.org/issue33666
> (Cherry-pick) Don't use the deprecated and removed os.errno

- binaries/vabtool/vabtool
Recent additions to the vabtool and the usage message left the usage
message in a bad state (a missing end-brace at the end of the parameter
list).  This change replaces the final comma with "} ..."
Signed-off-by: Russ Weight <russell.h.weight@intel.com>
> vabtool: Fix the format of the usage message

- binaries/vabtool/vabtool
Recent additions to the vabtool and the usage message left the usage
message in a bad state (a missing end-brace at the end of the parameter
list).  This change replaces the final comma with "} ..."
Signed-off-by: Russ Weight <russell.h.weight@intel.com>
Signed-off-by: Russ Weight <russell.h.weight@intel.com>
> vabtool:  (Cherry-pick) Fix the format of the usage message (#2714)

- binaries/fpgainfo/CMakeLists.txt
- binaries/fpgainfo/board.c
- binaries/fpgainfo/board.h
- binaries/fpgainfo/main.c
- tests/fpgainfo/test_board_c.cpp
- tests/fpgainfo/test_fpgainfo_c.cpp
Refactor fpgainfo so that it acquires its platform_data_table
via the common config file parsing code.
> fpgainfo: one config file integration

- binaries/opae.io/main.cpp
- binaries/opae.io/opae/io/config.py
- binaries/opae.io/opae/io/pci.py
- binaries/opae.io/opae/io/utils.py
- binaries/opae.io/setup.py
- opae.cfg
- python/opae.admin/opae/admin/version.py
- tests/opae.io/test_config.py
Implement new module opae.io.config to parse and create internal
config data for opae.io. Integrate that new module with opae.io's
ls command.
> opae.io: one config file integration

- scripts/opae-clean.sh
Change the previous clean option from -c to -d. The new -c option searches for OPAE configuration files in the supported paths.
> opae-clean.sh: add config file scrubbing

- libraries/libopae-c/cfg-file.c
Query the value of $HOME and search in the home config file locations relative to that path before trying the password database's version of the home directory. This should more closely match the use of pathlib in the Python search code.
> opae-c: config file: search in $HOME for home dirs

- opae.cfg
Some of the "rsu" entries in the config file had "configuration" instead of "fpga_default_sequences". Change them to "fpga_default_sequences" to match the parsing code.
> config: use fpga_default_sequences key in rsu

- binaries/vabtool/vabtool
Based on feedback, it is unnecessary/undesirable to require the PR_AUTH_CERT during SR programming.
> vabtool: remove PR_AUTH_CERT from SR provisioning

- tests/opae-c/test_sdl_c.cpp
These test cases were erroneously calling functions without a prior call to opae_ioctl_initialize(). This resulted in a NULL check failure and a subsequent FPGA_EXCEPTION.
> unit tests: address nightly unit test failures

- libraries/libopae-c/cfg-file.c
- opae.cfg
- python/opae.admin/opae/admin/config.py
The previous implementation erroneously treated 1001 as the n5010 VF. Also, removes default fpga boot sequence treatment from n5010 (and 5011), based on feedback from Silicom.
> (cherry-pick) config: change 1c2c:1001 to N5011 PF (#2742)

- libraries/libopae-c/pluginmgr.c
(re)-enables ASE as of the new config file format. Hook to allow enumerating the ASE device when WITH_ASE is set in the environment.
> ase: add hook to enable ASE with new config format

- libraries/libopae-c/pluginmgr.c
(re)-enables ASE as of the new config file format. Hook to allow enumerating the ASE device when WITH_ASE is set in the environment.
> (cherry-pick) ase: add hook to enable ASE with new config format (#2747)

- tests/opae-c/test_pluginmgr_c.cpp
Remove invalid test free_adapter_err0. The test case was dependent on dlclose() behaving nicely when a dl handle was double-freed. This depedency proved false during nightly regression, where it caused a seg fault.
> pluginmgr: remove invalid test case

- tests/opae-c/test_pluginmgr_c.cpp
Remove invalid test free_adapter_err0. The test case was dependent on dlclose() behaving nicely when a dl handle was double-freed. This depedency proved false during nightly regression, where it caused a seg fault.
> (cherry-pick) pluginmgr: remove invalid test case (#2749)

- libraries/libopae-c/pluginmgr.c
- tests/opae-c/test_pluginmgr_c.cpp
opae_plugin_mgr_alloc_adapter() was saving the value of its lib_path parameter directly in the adapter. This could lead to problems if, for example opae_plugin_mgr_register_plugin() were to pass through a stack-based path. The fix involves using strdup() and free() in the alloc and free adapter calls.
With the string fix in place, we add a check to
opae_plugin_mgr_register_adapter() to prevent duplicate entries in the list. This could happen when, eg ASE loads via
opae_plugin_mgr_register_plugin() but is also present in the configuration file passed to fpgaInitialize(). Duplicate adapter entries would mean duplicate tokens during enumeration. The uniqueness check guarantees that we won't duplicate any tokens.
Add unit tests for opae_plugin_mgr_register_plugin().
Signed-off-by: Tim …
> opae-c: avoid stack-based strings / add tests

- libraries/libopae-c/pluginmgr.c
- tests/opae-c/test_pluginmgr_c.cpp
opae_plugin_mgr_alloc_adapter() was saving the value of its lib_path parameter directly in the adapter. This could lead to problems if, for example opae_plugin_mgr_register_plugin() were to pass through a stack-based path. The fix involves using strdup() and free() in the alloc and free adapter calls.
With the string fix in place, we add a check to
opae_plugin_mgr_register_adapter() to prevent duplicate entries in the list. This could happen when, eg ASE loads via
opae_plugin_mgr_register_plugin() but is also present in the configuration file passed to fpgaInitialize(). Duplicate adapter entries would mean duplicate tokens during enumeration. The uniqueness check guarantees that we won't duplicate any tokens.
Add unit tests for opae_plugin_mgr_register_plugin().
Signed-off-by: Tim …
> (cherry-pick) opae-c: avoid stack-based strings / add tests (#2754)

- tests/opae-c/test_sdl_c.cpp
These test cases were erroneously calling functions without a prior call to opae_ioctl_initialize(). This resulted in a NULL check failure and a subsequent
FPGA_EXCEPTION.
> Cherry-pick: unit tests: address nightly unit test failures (#2746)

- packaging/opae/deb/control
- packaging/opae/deb/create
Remove explicit mentions of .so deps from the control file
and let ${shlibs:Depends} do its thing.
Verified using Ubuntu 22.04 LTS and Ubuntu 20.04 LTS.
Co-authored-by: Peter Colberg <Peter.Colberg@intel.com>
> deb packaging: add support for Ubuntu 20.04

- samples/hssi/hssi_100g_cmd.h
Fixes a segfault observed when --port was missing from the command line.
> hssi 100g: default to port 0 when no option given

- samples/hssi/hssi_100g_cmd.h
Fixes a segfault observed when --port was missing from the command line.
> (cherry pick) hssi 100g: default to port 0 when no option given (#2761)

- include/opae/types_enum.h
- libraries/libopae-c/pluginmgr.c
- libraries/pyopae/opae.cpp
- tests/opae-c/test_props_c.cpp
- tests/xfpga/test_enum_c.cpp
* ase: add VF device when WITH_ASE present.
Michael mentioned some ASE test cases that require the DID to be 0x0a5e. We'll change the DID of the VF0 back to 0x0a5e, and we'll make the subsystem device id 0x0a5f for the VF0.
> (cherry-pick) sim: changes to support ASE for OpenCL MMD. (#2751)

- libraries/libboard/board_n6000/board_event_log.c
SW should use the information in block with magic number '0x53696CF0' to derive power on event time stamp, and not the timestamp field of magic number '  0x53696C12'. Power on status is logged immediately after power on.  Time of the day information is written by SW into a BMC register. This write will take some time after power on and hence with Power on log there is no timestamp value available. Because of this reason, second block 'time of the day offset' (block with magic number '0x53696CF0' ) is provided from BMC. BMC internally keeps track of time lapse after the power on and first ToD write by Host and provides the correct value by reverse calculation.  Please use this information to print the power on status time
> Fix fpgainfo events power on time stamp

- libraries/afu-test/afu_test.h
The afu_test C++ infrastructure, used by host_exerciser, was logging both to the console and to a separate log file. Leaving files in the working directory every time host_exerciser is run is messy. Stop generating the files. When a log is needed, users can pipe output to a file or use tee.
> Stop generating files with logs from host_exerciser

- CMakeLists.txt
Linux mandates a limit on the length of a command that may appear in
the "shebang" line of a script. In our internal environments, this
limit has been exceeded, causing ill-behaved builds.
Fail the build if the length of CMAKE_INSTALL_PREFIX exceeds the
127 character limit.
> build: add CMAKE_INSTALL_PREFIX length check

- .github/workflows/no-python-analysis.yml
- .github/workflows/pacsign.yml
- .github/workflows/python-static-analysis.yml
- Remove Python 3.6, 3.7  and add 3.10,3.11 to versions to use for static analysis.
Signed-off-by: lab <ananda.ravuri@intel.com>
> ci: update python versions

- scripts/test-codingstyle-all.sh
Use --dry-run so that no code is changed, -Werror so that the process exit code is non-zero when a style violation is detected. Check the process exit code to determine pass/fail.
> C++ style: don't change code in the working tree

- binaries/ofs.uio/uio/ofs_uio.py
- fix uiox regular expression
- update error strings
- ofs.uio error shows message if finds Multiple FPGAs and feature ids
> Fix ofs.uio error message for Multiple FPGAs and duplicate  feature ids

- .github/workflows/ccpp-tests.yml
Use lychee instead of peter-evans/link-checker, which is deprecated.
> ci: update to lycheeverse/lychee-action@v1

- libraries/libboard/board_n6000/board_event_log.c
- libraries/libboard/board_n6000/board_n6000.c
fpgainfo events -s --bits
For example:
Power On Code FPGA				: 0x2
Power On Code CVL				: 0x2
Improved display.
Power On Code FPGA				: Success (0x2)
Power On Code CVL				: Success (0x2)
Rename Boot0  to Current Boot
Boot Index      : Power-ON Timestamp        : Power-OFF Timestamp
------------------------------------------------------------------
Current Boot    - Wed Jan  4 01:25:35 2023  - N/A
Boot 1              - Mon Jan  2 20:19:55 2023  - Wed Jan  4 01:25:24 2023
Boot 2             - Mon Jan  2 20:19:04 2023  - Mon Jan  2 20:19:43 2023
> fpgainfo events description to be user friendly and display format

- CMakeLists.txt
- cmake/modules/OPAETest.cmake
- tests/opae-c/CMakeLists.txt
* Force the gtest build to produce shared objects.
* Add include paths for static test libs and for dummy_plugin.so.
> cmake: gtest .so and include paths fix

- opae.spec.fedora
- opae.spec.rhel
Error: opae-devel.x86_64: E: non-executable-script /usr/lib/opae-2.2.0/modules/OPAEGit.cmake 644 /usr/bin/cmake -P Add execute permissions to  .cmake
> fix rpmlint non-executable-script errors

- opae.spec.fedora
- opae.spec.rhel
* fix rpmlint non-executable-script errors
Error: opae-devel.x86_64: E: non-executable-script /usr/lib/opae-2.2.0/modules/OPAEGit.cmake 644 /usr/bin/cmake -P Add execute permissions to  .cmake
> (Cherry-pick) fix rpmlint non-executable-script errors (#2810)

- include/ofs/ofs_primitives.h
- tests/libofs/test_libofs.cpp
From time to time, CI has been failing with one of these two error signatures:
libofs.wait_for_eq
/home/runner/work/opae-sdk/opae-sdk/tests/libofs/test_libofs.cpp:105: Failure Expected equality of these values:
status
Which is: 1
0
/home/runner/work/opae-sdk/opae-sdk/tests/libofs/test_libofs.cpp:136: Failure Expected: (delta_usec) < (timeout_usec), actual: 1508 vs 1500
[ RUN      ] libofs.wait_for_eq
/home/tswhison/persist/opae-sdk/tests/libofs/test_libofs.cpp:105: Failure
Expected equality of these values:
status
Which is: 1
0
/home/tswhison/persist/opae-sdk/tests/libofs/test_libofs.cpp:132: Failure
Expected: (delta_usec) < (timeout_usec), actual: 2104 vs 1500
These failures were reproduced using --gtest_shuffle and --gtest_repeat. The failures occurred on the order of 1 in 1000 test …
> libofs: correct unit test failures

- .github/workflows/ccpp-tests.yml
- CMakeLists.txt
- binaries/fpgad/api/CMakeLists.txt
- binaries/fpgad/plugins/fpgad-xfpga/CMakeLists.txt
- binaries/opae.io/CMakeLists.txt
- cmake/modules/OPAECompiler.cmake
- cmake/modules/OPAETest.cmake
- libraries/libbitstream/CMakeLists.txt
- libraries/libopaecxx/CMakeLists.txt
- libraries/plugins/xfpga/metrics/bmc/bmcdata.c
- libraries/plugins/xfpga/metrics/bmc/bmcinfo.c
- scripts/cover.sh
Add the necessary dependencies so that parallel builds work again. Here are some observed data points. There seems to be a point of diminishing returns around -j 8:
cmake .. -DCMAKE_BUILD_TYPE=Debug -DOPAE_BUILD_TESTS=ON -DOPAE_ENABLE_MOCK=ON -DOPAE_BUILD_LEGACY=ON
make -j 4  5m5.137s
make -j 8  4m21.589s
make -j 12 5m35.980s
make -j 16 6m11.187s
Ah, `nproc` reports 8 cpu's. That explains it.
> build: re-enable parallel builds

- python/opae.admin/opae/admin/tools/fpgasupdate.py
Add a check for status.value != 'idle' to the transferring loop. This allows the script to break from the transferring loop when the cancel sysfs node is written externally.
> fpgasupdate: break from transferring on error

- python/opae.admin/setup.py
When creating .deb and .rpm packages in CI, pretty_version() was observed to return the version string '1.4.3-'. This was causing setuptools to error out. Just use the hard-coded version to ensure that it's valid.
> opae.admin: don't use pretty_version() for version

- CMakeLists.txt
- tests/framework/CMakeLists.txt
Add the necessary dependencies between libtest_system.so and the gtest libraries in order to support parallel builds.
> build: add deps on gtest imported libraries

- libraries/plugins/vfio/opae_vfio.c
> opae-v: fix lock issue found by static analysis.

- doc/sphinx/requirements.txt
- upgrade certifi to version 2022.12.7 or higher.
- Add  certifi==2022.12.7 to requirements.txt.
> fix snyk scan error

- binaries/opae.io/main.h
Declare the copy constructor as private but declare no actual member function for it so that the object becomes uncopyable. If an instance of the class were to be copied, then both instances would attempt to free the same pointer in close().
> opae.io: fix issues identified by static analysis

- binaries/fpgadiag/opae/diag/fvlbypass.py
- binaries/opae.io/opae/io/utils.py
- scripts/opae-clean.py
fvlbypass: uninitialized variable.
opae.io: use of wrong, invalid parameter.
opae-clean: anchoring of regex.
> python: fix errors found by static analysis

- libraries/libboard/board_c6100/board_event_log.c
- tests/board/test_board_c6100.cpp
SW should use the information in block with magic number '0x53696CF0' to derive power on event time stamp, and not the timestamp field of magic number '  0x53696C12'.
Power on status is logged immediately after power on.  Time of the day information is written by SW into a BMC register. This write will take some time after power on and hence with Power on log there is no timestamp value available. Because of this reason, second block 'time of the day offset' (block with magic number '0x53696CF0' ) is provided from BMC. BMC internally keeps track of time lapse after the power on and first ToD write by Host and provides the correct value by reverse calculation.  Please use this information to print the power on status time
> Fix C6100 fpgainfo events power on time stamp

- python/pacsign/pacsign/hsm_managers/openssl/openssl.py
The check for openssl version is relaxed to allow all versions of libcrypto.so.3 Ubuntu 22.04 uses 3.0.2, RHEL 9.0 and 9.1 uses 3.0.1. Several higher versions already exists.
> Fix PACSign fails on RHEL9 because of OpenSSL version 3.0.1 #2841

- opae.cfg
The program also works for N501x cards. The pcie option walks the DFL. The bmc option shows the regmaps defined. The other options just do not find anything.
> fpgareg: Enable the program for N501x cards in opae.cfg

- libraries/libboard/board_n5010/board_n5010.c
> fpgainfo: for N501x add show board info read from BMC

- include/opae/hash_map.h
- include/opae/vfio.h
- libraries/libopaemem/CMakeLists.txt
- libraries/libopaemem/hash_map.c
- libraries/libopaevfio/opaevfio.c
- libraries/plugins/vfio/opae_vfio.c
- libraries/plugins/vfio/opae_vfio.h
- libraries/plugins/vfio/plugin.c
Add a hash map implementation to libopaemem. The hash map implementation
is modeled after the implementation found in xfpga, but is a more general
implementation, operating on void pointers instead of buffer structs.
Use the hash map to replace the list-based buffer tracking in
libopaevfio to increase performance.
Removes the linked-list tracking for the buffer info and instead stashes
the pointer to libopaevfio's underlying buffer info struct in the wsid
output parameter. This eliminates a list walk in the buffer alloc/free
paths.
> vfio: changes in support of OpenCL MMD for gzip workload

- libraries/plugins/xfpga/usrclk/fpga_user_clk.c
These error paths were previously returning FPGA_OK, which led to a seg fault in one code path. Return FPGA_EXCEPTION so that the buffer pointers in question are not de-referenced.
> userclk: fix return code for error paths

- .github/workflows/ccpp-tests.yml
- packaging/opae.admin/rpm/opae.admin.spec
Also updates CI so that ubuntu-latest successfully upgrades. Package grub-efi-amd64-signed was failing to configure during `apt upgrade`.  Had success with a solution proposed online.
> packaging/opae.admin/rpm: fix spec issue

- python/opae.admin/opae/admin/fpga.py
- python/opae.admin/opae/admin/tools/rsu.py
On some servers e.g. Dell R750 and XR12 even DPC is supported, hardware error occurs and server may crash, when running the rsu command on Arrow Creek or Lightning Creek cards. Disabling AER even DPC is supported can workaround these issues. This extension allows that by using the --force option.
There is an ongoing validation by Dell of the Arrow Creek card. Intel, Dell and Silicom are working together on this. This issue has been investigated for some time without finding the root cause. It would thus be good to have this option as a workaround.
> rsu: extend --force to also force disabling AER even DPC is supported

- libraries/afu-test/afu_test.h
- samples/hssi/hssi.cpp
- samples/hssi/hssi_100g_cmd.h
- samples/hssi/hssi_10g_cmd.h
- samples/hssi/hssi_cmd.h
Refactor the timeout mechanism, placing the running_ flag in the afu_test::command class, so that afu_test::afu can stop an in- progress command on timeout. Remove the old mechanism from the hssi_cmd class.
> hssi/afu_test: refactor timeout mechanism

- binaries/opae.io/opae/io/run.py
Add a hacky, yet functional back-end implementation for the Grafana
SimpleJson plugin, to track the N3000 sensors using sensors -j.
> opae.io: flask server: add Grafana SimpleJson api

- libraries/libopaevfio/opaevfiotest.c
Segmentation fault1: opaevfiotest  0000:3b:00.1 dfh
PF1 and PF2 doesn’t support Bar 2 , opae_vfio_region_get() function ignores function return code  causes Segmentation fault
Fix: print_dfh() function exits gracefully  if opae_vfio_region_get() fails.
Segmentation fault2: opaevfiotest  0000:3b:00.0 nlb0
opae_vfio_region_get() and opae_vfio_buffer_allocate() functions ignores function return code  causes Segmentation fault
Fix: nlb0 () function exits gracefully   if opae_vfio_region_get() and opae_vfio_buffer_allocate() fails.
> fix opaevfiotest Segmentation fault

- binaries/ofs.uio/uio/ofs_uio.py
issue: ofs.uio  mailbox writes fails  because of mailbox-write() first sets write bit and command address  and then writes data into CSR.
fix: mailbox-write() function writes data into CSR  and  set write bit and command address into mailbox CMD CSR, Swap order.
> fix ofs.uio first write mailbox data CSR and write command CSR.

- binaries/opae.io/opae/io/config.py
- libraries/libopae-c/cfg-file.c
- opae.cfg
- python/opae.admin/opae/admin/config.py
- tests/opae.admin/test_config.py
- tests/opae.io/test_config.py
* rename C6100 platform name to Intel IPU Platform F2000X-PL
rename C6100 platform name to  in opae.cfg
> (Cherry-pick) rename C6100 platform name to Intel IPU Platform F2000X-PL (#2910)

- binaries/ofs.uio/uio/ofs_uio.py
issue: ofs.uio  mailbox writes fails  because of mailbox-write() first sets write bit and command address  and then writes data into CSR.
fix: mailbox-write() function writes data into CSR  and  set write bit and command address into mailbox CMD CSR, Swap order.
> (Cherry-pick) fix ofs.uio first write mailbox data CSR and write command CSR. (#2904)

- libraries/libboard/board_c6100/board_c6100.c
- libraries/libboard/board_common/board_common.c
- libraries/libboard/board_common/board_common.h
- libraries/libboard/board_n6000/board_n6000.c
* add QSFP cable status to fpgainfo phy
fpgainfo phy reads QSFP cable  status and prints connected or not connected
QSFP0                            : Not Connected
QSFP1                            : Not Connected
* fix qsfp not supported case
---------
> (Cherry-pick) add QSFP cable status to fpgainfo phy (#2916)

- samples/host_exerciser/host_exerciser_cmd.h
host_exerciser assumed read and write traffic were identical when computing lpbk and trput bandwidth. Use the actual count of reads and writes instead of just doubling writes.
> host_exerciser computed sum of reads+writes incorrectly

- python/opae.admin/opae/admin/tools/pci_device.py
In support of fpga designs with an hps, add unplug and plug subcommands to pci_device. These are used to disconnect/reconnect an fpga device from the host processor perspective.
> pci_device: add unplug and plug subcommands

- python/opae.admin/opae/admin/fpga.py
- python/opae.admin/opae/admin/tools/pci_device.py
- python/opae.admin/opae/admin/tools/rsu.py
When programming the factory image, the number of PFs can be reduced. These orphaned PF objects from the prior enumeration can cause following setpci calls to fail. Check the output from the failed setpci() call before proceeding.  Perform enumeration again, after the bus rescan to resolve the issue.
> rsu, pci_device: fix rescan path

- libraries/plugins/xfpga/reconf.c
- tests/xfpga/test_reconf_c.cpp
Tokens must not be destroyed until their associated handle is closed.
> xfpga: fix a long-standing bug in the PR path

- packaging/opae/rpm/create
When given 'rhel' or 'fedora', the create script would check for the presence of certain prerequisite packages before calling rpmbuild. The RPM spec file would also require certain packages in the 'BuildRequires: ' clauses. This posed a problem for certain distros that renamed their packages to be other than the standard package names. eg python3-pybind11 became python39-pybind11 in one instance.
This change adds a new 'unrestricted' mode to the create script which 1) skips the checking of prerequisite packages by the create script and 2) removes the 'BuildRequires: ' clauses from the RPM spec. When using 'unrestricted', it is the user's responsibility to ensure that the SDK will build correctly so that the RPM can be created.
> rpm build: add unrestricted build mode

- binaries/opae.io/opae/io/utils.py
If the pickle file becomes corrupt, for example by being empty, opae.io init failed silently and printed a prompt without opening the device. The update gives up on the unreadable state and overwrites the pickle file.
> Get opae.io out of a pickle

- .github/workflows/build-debs.yml
- .github/workflows/build-rpms.yml
The current build-debs and build-rpms workflows do not upload the built artifacts, because they are trying to upload from the wrong directory.
This change corrects the directory, so the artifacts are uploaded.
> Fix GitHub Actions build-debs and build-rpms

- binaries/opae.io/opae/io/utils.py
If the pickle file becomes corrupt, for example by being empty, opae.io init failed silently and printed a prompt without opening the device. The update gives up on the unreadable state and overwrites the pickle file.
> (Cherry-pick) Get opae.io out of a pickle

- libraries/libboard/board_c6100/board_event_log.c
- libraries/libboard/board_c6100/board_event_log.h
- tests/board/test_board_c6100.cpp
support  new PCIe Persistent error to fpgainfo events for N6000 and enabled in BMC version 11.5 version
0x0924 Magic Num- PCIE Errors (Updated) 0x53696D12 in process context in main cycle PCIe error log 0x0928 Time stamp low Low timestamp 1
0x092C Time stamp high High timestamp 2
0x0930 PCIe Link Status PCIE Link Status
0x0934 PCIE Uncorrectable Err Status PCIE Uncorrectable Err Status 0x093C PCIE Uncorrectable Err Mask PCIE Uncorrectable Err Mask 0x0940 PCIE Uncorrectable Err Severity PCIE Uncorrectable Err Severity 0x0944 PCIE Correctable Err Status PCIE Correctable Err Status 0x0948 PCIE Correctable Err Mask PCIE Correctable Err Mask 0x094C PCIE Cap And Ctrl PCIE Cap And Ctrl
0x0950 PCIE Header Log DW 1 PCIE Header Log DW 1
0x0954 PCIE Header Log DW 2 PCIE Header Log DW 2
0x0958 PCIE …
> add new PCIe Persistent error logging to fpgainfo events (

- libraries/libboard/board_c6100/board_event_log.c
- libraries/libboard/board_c6100/board_event_log.h
- tests/board/test_board_c6100.cpp
* add new PCIe Persistent error logging to fpgainfo events (
support  new PCIe Persistent error to fpgainfo events for N6000 and enabled in BMC version 11.5 version
0x0924 Magic Num- PCIE Errors (Updated) 0x53696D12 in process context in main cycle PCIe error log 0x0928 Time stamp low Low timestamp 1
0x092C Time stamp high High timestamp 2
0x0930 PCIe Link Status PCIE Link Status
0x0934 PCIE Uncorrectable Err Status PCIE Uncorrectable Err Status 0x093C PCIE Uncorrectable Err Mask PCIE Uncorrectable Err Mask 0x0940 PCIE Uncorrectable Err Severity PCIE Uncorrectable Err Severity 0x0944 PCIE Correctable Err Status PCIE Correctable Err Status 0x0948 PCIE Correctable Err Mask PCIE Correctable Err Mask 0x094C PCIE Cap And Ctrl PCIE Cap And Ctrl
0x0950 PCIE Header Log DW 1 PCIE Header Log DW 1 …
> (Cherry-pick) add new PCIe Persistent error logging to fpgainfo events ( (#2970)

- libraries/libopaeuio/opaeuio.c
Add calls to flock() in the open and close paths so that no more than one process may access the uio device at a time.
> libopaeuio.so: use flock for exclusive access

- binaries/ofs.uio/uio/ofs_uio.py
Add support for a pause_daemon which is a SW work around to the RX pause configuration registers being initialized improperly in the E-tile. Since these registers can only be written when the ethernet link is established, the daemon tries to run forever, periodically writing the registers.
> ofs_uio.py: add pause_daemon support

- binaries/ofs.uio/uio/ofs_uio.py
Add support for a pause_daemon which is a SW work around to the RX pause configuration registers being initialized improperly in the E-tile. Since these registers can only be written when the ethernet link is established, the daemon tries to run forever, periodically writing the registers.
> (cherry-pick) ofs_uio.py: add pause_daemon support

- docker/ubuntu22/Dockerfile
- libraries/libboard/board_n6000/board_event_log.h
- scripts/test-codingstyle-all.sh
These packages are required, but were missing from the Dockerfile for the CI job that builds and tests .deb packages.
> ci: add spdlog and cli11 to ubuntu22.04

- docker/ubuntu22/Dockerfile
- scripts/test-codingstyle-all.sh
* ci: add spdlog and cli11 to ubuntu22.04 These packages are required, but were missing from the Dockerfile for the CI job that builds and tests .deb packages.
* Add python3-pybind11
checkpatch.pl was complaining about the size 1 array definition.
* coding style: lock checkpatch.pl version
Recent changes to checkpatch.pl have enforced C99 "flexible arrays" checks for kernel code. This breaks a recent submission to the SDK in libraries/libboard/board_n6000/board_event_log.h.
Lock the checkpatch.pl version to the version prior to the introduction of the flexible array checks.
> (cherry-pick) ci: add spdlog and cli11 to ubuntu22.04 (#2978)

- samples/mem_tg/mem_tg.h
- samples/mem_tg/tg_test.h
- Added multi-channel capability to mem_tg test, specified in "-m, --mem-channel" argument, allowing bandwidth to be measured for several channels communicating in parallel.
- User can specify a list of integers representing the 0 indexed channels to be run, or 'all' to run on all channels enumerated in MEM_TG_CTRL register.
- Each channel gets a thread spawned for it that runs the preexistent configuration and run routines.
- The results of each thread are logged in the same format as the previous version.
> multi-channel mem_tg test 

- binaries/opae.io/main.h
- binaries/opae.io/pymain.h
- binaries/opae.io/vfiobindings.cpp
Add the vf_token subcommand to set the PCI Virtual Function (VF) token when the vfio-pci driver is bound to the Physical Function (PF).
> opae.io: add vf_token subcommand

- doc/src/fpga_tools/mem_tg/mem_tg.md
- samples/mem_tg/mem_tg.h
- samples/mem_tg/tg_test.h
- Added documentation/instructions for #2983 
- Adjusted tg_test.h do the starting write to each channel around the same time when multiple channels are used.
- Fixed bug where summary statements could collide after tests completed.
> mem_tg test channel synchronization and documentation

- tests/framework/mock/opae_std.h
Fixes a compile issue encountered internally.
> mock: make sure that stdio.h appears after __USE_GNU

- platforms/scripts/platmgr/tools/afu_synth_setup.py
It was accidentally replicating files and directories instead of just replicating soft links.
> Copy soft links in afu_synth_setup

- libraries/plugins/uio/opae_uio.c
- tests/opae-u/test_opae_uio_c.cpp
Rename pci_device_supported in the UIO plugin to be uio_pci_device_supported to avoid name collision with that routine in the VFIO plugin. This manifested as a segfault when running the utl's on hardware on some systems.
> opae-u: rename pci_device_supported

- libraries/libboard/board_n6000/board_event_log.c
- tests/board/test_board_n6000.cpp
The host writes the 'time of the day' to BMC registers (offset 0x178, 0x17C) periodically (every minute). BMC uses this value as the timestamp for error and event logging. In the scenario where 'PCI error status time' is incorrect, PCIe error is received before the host writes the 'time of the day' value to BMC registers. Therefore, BMC records the timestamp as approx epoch time (which is all 0's). 
power on event error displays the valid timestamp even though the timestamp in flash is recorded prior to the writing of 'time of day'
> fix fpga events PCIe Error status time

- binaries/fpgadiag/src/nlb0_main.cpp
- binaries/fpgadiag/src/nlb3_main.cpp
- binaries/fpgadiag/src/nlb7_main.cpp
In the case of some invalid command-line input, exceptions were being thrown. The fix catches these exceptions and prints an error message rather than aborting.
> fpgadiag: fix issues found during fuzz testing

- tests/fuzzing/fuzz-bist_app.sh
- tests/fuzzing/fuzz-dummy_afu.sh
- tests/fuzzing/fuzz-fpga_dma_N3000_test.sh
- tests/fuzzing/fuzz-fpga_dma_test.sh
- tests/fuzzing/fuzz-fpgabist.sh
- tests/fuzzing/fuzz-fpgaconf.sh
- tests/fuzzing/fuzz-fpgad.sh
- tests/fuzzing/fuzz-fpgadiag.sh
- tests/fuzzing/fuzz-fpgainfo.sh
- tests/fuzzing/fuzz-fpgametrics.sh
- tests/fuzzing/fuzz-hello_cxxcore.sh
- tests/fuzzing/fuzz-hello_events.sh
- tests/fuzzing/fuzz-hello_fpga.sh
- tests/fuzzing/fuzz-host_exerciser.sh
- tests/fuzzing/fuzz-hps.sh
- tests/fuzzing/fuzz-hssi.sh
- tests/fuzzing/fuzz-mem_tg.sh
- tests/fuzzing/fuzz-mmlink.sh
- tests/fuzzing/fuzz-n5010-ctl.sh
- tests/fuzzing/fuzz-n5010-test.sh
- tests/fuzzing/fuzz-nlb0.sh
- tests/fuzzing/fuzz-nlb3.sh
- tests/fuzzing/fuzz-nlb7.sh
- tests/fuzzing/fuzz-object_api.sh
- tests/fuzzing/fuzz-opae.io.sh
- tests/fuzzing/fuzz-opaeuiotest.sh
- tests/fuzzing/fuzz-opaevfiotest.sh
- tests/fuzzing/fuzz-userclk.sh
- tests/fuzzing/main.sh
Adds a -q option to filter out the radamsa output. This is desirable when creating verification reports. To use this, run the tests like:
$ ./main.sh 3 -q 2>/dev/null
> fuzz tests: add quiet option for report generation

- binaries/userclk/main.c
- libraries/plugins/xfpga/usrclk/fpga_user_clk.c
- Agilex slow clock was limited to 600MHz instead of 800MHz because the wrong parameters were tested.
- Write a new setting even if the clock is not locked. This makes it possible to recover from a previous failure.
- Extreme frequency changes sometimes result in configuration failures. Program an intermediate frequency before setting the actual target.
> Fix several user clock configuration bugs

- libraries/plugins/xfpga/usrclk/fpga_user_clk.c
- Increase delay before measuring user clock after changing frequency. The previous delay was a bit short, leading to measurement errors.
- Correct naming of DELAY time macro units from ms to us.
> Increase user clock measurement delay

- CMakeLists.txt
- binaries/fpgadiag/CMakeLists.txt
- binaries/hssi/CMakeLists.txt
- binaries/ofs.uio/CMakeLists.txt
- binaries/opae.io/CMakeLists.txt
- cmake/modules/OFS.cmake
- cmake/modules/OPAEPackaging.cmake
- libraries/pyopae/CMakeLists.txt
- libraries/pyopaeuio/CMakeLists.txt
- python/CMakeLists.txt
- python/opae.admin/CMakeLists.txt
- tests/pyopae/CMakeLists.txt
https://cmake.org/cmake/help/latest/policy/CMP0148.html
FindPythonInterp and FindPythonLibs are deprecated as of cmake 3.12. Recent cmake versions remove these altogether. The fix involves using
find_package(Python3 COMPONENTS Interpreter Development)
instead of find_package(PythonInterp and find_package(PythonLibs.
The following variable names are also updated, reflecting our dependency on Python 3:
PYTHON_EXECUTABLE   -> Python3_EXECUTABLE
PYTHON_INCLUDE_DIRS -> Python3_INCLUDE_DIRS
PYTHON_LIBRARIES    -> Python3_LIBRARIES
N/A
Build with OPAE_BUILD_TESTS=ON, Ubuntu 22.04.
Build with OPAE_BUILD_TESTS=ON, Fedora 36.
Build with OPAE_BUILD_TESTS=ON, Rocky Linux 9.
Build with OPAE_BUILD_TESTS=ON, OpenSUSE Tumbleweed.
> fix: address cmake policy 148

- binaries/opae.io/opae/io/utils.py
- include/opae/buffer.h
- libraries/libopae-c/adapter.h
- libraries/libopae-c/api-shell.c
- libraries/plugins/vfio/CMakeLists.txt
- libraries/plugins/vfio/opae_vfio.c
- libraries/plugins/vfio/opae_vfio.h
- libraries/plugins/vfio/plugin.c
- libraries/plugins/xfpga/fpga-dfl.h
- tests/opae-c/dummy_plugin.c
Add fpgaBindSVA() to allocate and bind PASIDs to FPGA ports. Shared virtual addressing requires hardware support, both in the CPU and on the FPGA.
fpgaBindSVA() depends on /dev/dfl-pci-sva from the dfl-pci driver. IOVA-based pinned DMA remains available with older drivers and hardware that does not support PASID.
OPAE behavior is unchanged when fpgaBindSVA() is not called.
> Feature: add a method for binding shared virtual addressing

- tests/opae-u/test_opae_uio_c.cpp
- tests/opae-v/test_opae_vfio_c.cpp
Fix for tests that were causing file descriptor 0 to be closed.
vfio and uio plugin ULT's.
> Fix: vfio/uio test case bug

- include/opae/cxx/core/handle.h
- libraries/libopaecxx/src/handle.cpp
- tests/opae-cxx/test_handle_cxx_core.cpp
Adds C++ member function handle::bind_sva() which calls fpgaBindSVA() to perform the magic and retrieve the pasid.
N/A
C Programming Guide
handle_cxx_core.bind_sva
CI
> Feature: add fpgaBindSVA() support to C++ bindings

- python/opae.admin/opae/admin/sysfs.py
- python/opae.admin/opae/admin/tools/pci_device.py
- python/opae.admin/opae/admin/version.py
- python/opae.admin/pyproject.toml
- python/opae.admin/setup.py
Previously, pci_device used parser.parse_known_args() after adding custom parsers in each command class.
These parsers were disjoint from the parser declared and referenced in main.  The main parser, however, was
responsible for creating the command help.  The result was that the commands' options were not reflected
in the help output.
Moving to argparse subparsers corrects the problem, so that all options are visible from the main parser's
help printout.
Here's an example:
\# pci_device 0000:dc:00.0 aer mask --help
usage: pci_device device-filter aer mask [-h] [-o OUTPUT] [-i INPUT] [values ...]
positional arguments:
values                show, print, all, off, \<int\> \<int\>
optional arguments:
-h, --help            show this help message and exit
-o OUTPUT, --output OUTPUT
file to …
> Update: use argparse subparsers in pci_device

- binaries/opae.io/main.cpp
- binaries/opae.io/pymain.h
- binaries/opae.io/pyproject.toml
- binaries/opae.io/scripts/walk.py
- binaries/opae.io/setup.py
Use argparse subparsers instead of parse_known_args(), so
that the help information for sub-options can be auto-generated.
Bump revision to 1.0.0 - in order to run a script, the new 'script'
sub-option is required:
Before the change: opae.io do_something.py a b c
As of the change: opae.io script do_something.py a b c
The change is required due to the nature of argparse subparsers.
fpga_tools/opae.io/opae.io.md
Manual verification of all opae.io commands.
> Update: use argparse subparsers in opae.io

- python/opae.admin/opae/admin/sysfs.py
- python/opae.admin/opae/admin/tools/pci_device.py
- python/opae.admin/opae/admin/version.py
- python/opae.admin/pyproject.toml
- python/opae.admin/setup.py
In a hw design utilizing two PFs, the unplug command must provide an option to preserve
the PF that provides the PR capability; otherwise, PR will not function.
Manual verification of --exclude functionality.
> Update: add --exclude option to pci_device unplug

- libraries/plugins/xfpga/fpga-dfl.h
- samples/cxl_host_exerciser/cxl_he_cache_cmd.h
- samples/cxl_host_exerciser/cxl_he_cmd.h
- samples/cxl_host_exerciser/cxl_host_exerciser.h
- samples/cxl_host_exerciser/he_cache_test.h
-Remove numa node from dfl ioctl
- Fix bugs
-Add HE-CACHE csr function to print csr.
> fix:update fpga dfl ioctl changes and bug fixes

- binaries/opae.io/opae/io/utils.py
opae.io init unbinds the target device from its driver and writes
a breadcrumb out to file so that the driver can be restored during
opae.io release. Previously, we were using the pickle module to do
this.
This github issue #3024 was filed, noting that pickle is prone to
code execution injection issues.  The proposal was to use json
instead.
#3024
Manual verification using opae.io init followed by opae.io release.
> Update: use json to save opae.io driver state

- samples/cxl_host_exerciser/cxl_he_cache_cmd.h
- samples/cxl_host_exerciser/cxl_he_cmd.h
- samples/cxl_host_exerciser/cxl_host_exerciser.h
- samples/cxl_host_exerciser/he_cache_test.h
-Change HE Cache  bias command line to –bias host or device 
-Change scenario  setup message  to “Pretest scenario started..”  and  actual test message Test started ......"
-Change Fails to allocate 2MB huge page: Invalid argument to “Failed to allocate 2MB huge page: Invalid argument”
-Fix  output message “number of nodes on system”
-Set Stride value only if user passes command line  --stride value.
> Fix: Update HE Cache  bias command line input

- binaries/fpgadiag/CMakeLists.txt
- binaries/hssi/CMakeLists.txt
- binaries/ofs.uio/CMakeLists.txt
- cmake/modules/OPAEPackaging.cmake
On certain older Python3 installations, this option is not supported; and when it is encountered, it causes pip to error out.
Its only use is to suppress a warning message.  Removing it will allow older pip's to do the right thing, and newer pip's will show the warning.
CI
> Fix: remove problematic pip option --no-warn-script-location

- samples/cxl_host_exerciser/cxl_he_cmd.h
The CXL host exerciser read latency output string has been modified with the "Total transaction time  nanoseconds".
> Fix:CXL Host exerciser calculations and output string

- samples/cxl_host_exerciser/cxl_he_cache_cmd.h
- samples/cxl_host_exerciser/cxl_he_cmd.h
- samples/cxl_host_exerciser/cxl_host_exerciser.h
- samples/cxl_host_exerciser/he_cache_test.h
- CXL host exerciser Remove latency iterations tests from write cache hit/miss scenario
- Remove Bandwidth calculation and output in Read cache hit/miss scenario
> Fix: Remove latency iterations from write cache hit/miss scenario tests

- binaries/opae.io/main.h
Static analysis complained that although a destructor had been defined in class vfio_device, there was not a corresponding copy ctor nor assignment operator. The variable is treated as a Singleton in the application, so no copying occurs.  Implementing the constructor and assignment operator as deleted solves the issue.
CI
> Fix: correct issue pointed out by static analysis

- binaries/opae.io/main.h
Removes multiple declaration of copy ctor from class vfio_device.
> Fix: correct opae.io build issue

- binaries/fpgabist/dma/fpga_dma.cpp
Uninitialized variable errors were encountered on RHEL 8.6 with g++ 8.5.0.
CI
> Fix: fpgabist uninitialized variable errors

- libraries/plugins/xfpga/fpga-dfl.h
- samples/cxl_host_exerciser/cxl_he_cmd.h
- samples/cxl_host_exerciser/he_cache_test.h
- Set Host and FPGA buffer map  Writable for Host BIAS mode targeting Host address and Host BIAS mode targeting HDM  (Device) address
- Set FPGA buffer map read-only for device BIAS mode targeting HDM (Device) address
CXL Driver IOCTL  buffer map by default Read-only flag value is 0,
Set buffer map flag to  DFL_CXL_BUFFER_MAP for Read/write buffers
struct dfl_cxl_cache_buffer_map {
__u32 argsz;
#define DFL_CXL_BUFFER_MAP_WRITABLE 1
__u32 flags;
__u64 user_addr;
__u64 length;
}
*PR Title should start with one of the following tags: [Fix]/[Feature]/[Style]/[Update]*
*[Fix]- Bug Fix*
*[Feature]- for new feature*
*[Style]- Grammar or branding fix*
*[Update]-For an update to an existing feature*
------------- *Keep everything below this line* -------------------------
*Describe the issue, …
> fix: set FPGA buffer read only for bias mode device bias.

- libraries/plugins/uio/dfl.c
- libraries/plugins/vfio/dfl.c
A recent checkin began relying on sys/pci.h for its definition of PCI_STD_NUM_BARS.
It seems that some distributions don't have a version of that file that defines PCI_STD_NUM_BARS.
This change defines it to 6 when not found.
CI
> Fix: define PCI_STD_NUM_BARS when not found

- samples/cxl_host_exerciser/cxl_he_cache_cmd.h
- samples/cxl_host_exerciser/cxl_host_exerciser.h
- Host reads and write miss tests are same as FPGA reads and write miss, so remove from CXL host exerciser.
- Changes Host read cache hit opcode to RD_LINE_I
> fix: remove Host reads and write miss tests

- samples/cxl_host_exerciser/he_cache_test.h
-CXL host exerciser segmentation fault occurs in non-root user mode,
exit application if clx device open fails.
> fix: CXL host exerciser  segmentation fault non-root user mode

- samples/cxl_host_exerciser/cxl_he_cache_cmd.h
-CXL host exerciser running pointer tests show wrong "data ping pong tests".
Change to "Running pointer test started ......"
> fix: CXL host exerciser running pointer test output wrong  string

- samples/cxl_host_exerciser/he_cache_test.h
-CXL host exerciser segmentation fault occurs in non-root user mode,
exit application if clx device open fails.
> fix: (Cherry-pick) CXL host exerciser  segmentation fault non-root user mode (#3067)

- include/opae/access.h
- libraries/libopae-c/CMakeLists.txt
- libraries/libopae-c/adapter.h
- libraries/libopae-c/api-shell.c
- libraries/libopae-c/multi-port-afu.c
- libraries/libopae-c/multi-port-afu.h
- libraries/libopae-c/opae_int.h
Multi-ported AFUs have a parent AFU that names child AFUs by GUID, encoded in the first entry of a v1 AFU feature list.
- Detect AFUs with children in fpgaOpen() and open all children, associating all open ports with the returned handle.
- When a buffer is pinned in the parent, also pin the buffer at the same IOVA in all children.
- Add fpgaGetChildren() in order to expose child handles for MMIO and interrupts.
host_exerciser on HW, ASE tests
> [Feature] - Add parent/child AFU management to the libopae-c shell

- python/opae.admin/opae/admin/fpga.py
When using the rsu --force option on systems without AER support the clearing of correctable/uncorrectable errors fails and setpci command returns exit code 1. Fix this by checking the root port for AER support before clearing errors.
------------- *Keep everything below this line* -------------------------
*Describe the issue, update, change or fix and **why***
> [Fix] Only clear AER errors when AER is available

- libraries/libopae-c/api-shell.c
Mistaken pointer dereference. buf_addr is allowed to be NULL when testing the fpgaPrepareBuffer() capabilities.
Resolves a regression introduced in commit 4d757b6d.
> [Fix] SEGV when passing NULL buf_addr to fpgaPrepareBuffer()

- binaries/fpgametrics/fpgametrics.c
- libraries/plugins/xfpga/metrics/metrics_max10.c
- update fpga metrics index numbered from 1-42 (instead of 0-41)
- improve fpgametrics  output readability
- group power and thermal sensor strings and values
> fix:improve fpgametrics output readability and

- binaries/opae.io/opae/io/utils.py
- binaries/opae.io/pymain.h
- doc/sphinx/requirements.txt
- include/opae/cxx/core/shared_buffer.h
- include/opae/metrics.h
- include/opae/vfio.h
Add --force and --enable-sriov options to the subparser for opae.io init. The --force option enables controlling the force parameter to vfio_init() that was previously hard-coded to False.
The --enable-sriov option, when given, causes opae.io init to write 'Y' to /sys/module/vfio_pci/parameters/enable_sriov.
The default value for both options is False.
*PR Title should start with one of the following tags: [Fix]/[Feature]/[Style]/[Update]*
*[Fix]- Bug Fix*
*[Feature]- for new feature*
*[Style]- Grammar or branding fix*
*[Update]-For an update to an existing feature*
------------- *Keep everything below this line* -------------------------
*Describe the issue, update, change or fix and **why***
> Feature: add --force, --enable-sriov to opae.io

- samples/cxl_mem_tg/cxl_mem_tg.h
- samples/cxl_mem_tg/cxl_tg_test.h
* fix:update cxl_mem_tg test completion timeout value
-update cxl_mem_tg test completion timeout value to 0.5 seconds. -user can pass timeout value as command line argument –timeout in milliseconds, cxl_mem_tg sets test completion timeout to input value.
- exits application( return error)  if user pass read and write values and Read count exceeds Read count exceeds Write count
> fix: (Cherry-pick) update cxl_mem_tg test completion timeout value (#3081)

- include/opae/access.h
- include/opae/mem_alloc.h
- include/opae/types_enum.h
- include/opae/vfio.h
- libraries/libopae-c/api-shell.c
- libraries/libopae-c/multi-port-afu.c
- libraries/libopaemem/mem_alloc.c
- libraries/libopaevfio/opaevfio.c
- libraries/plugins/vfio/opae_vfio.c
- libraries/plugins/vfio/opae_vfio.h
- libraries/plugins/vfio/plugin.c
Multi-port AFUs connect to more than one device from a single process, sharing IOVA space across all devices.
> [Feature] - Add support for multi-port AFUs in OPAE vfio plugin

- samples/cxl_host_exerciser/cxl_he_cache_cmd.h
- samples/cxl_host_exerciser/cxl_he_cmd.h
-CXL Host exerciser latency calculations  equation by consider the penalty start i.e.
B asically consider total clock cycles – penalty clock cycles for calculation instead of total cycles that comes in DSM.
Latency nano seconds  =  (number of ticks – penalty start ticks ) * 2.5
> fix: update CXL Host exerciser latency calculations

- samples/cxl_host_exerciser/cxl_he_cache_cmd.h
- samples/cxl_host_exerciser/cxl_he_cmd.h
-CXL Host exerciser latency calculations  equation by consider the penalty start i.e.
B asically consider total clock cycles – penalty clock cycles for calculation instead of total cycles that comes in DSM.
Latency nano seconds  =  (number of ticks – penalty start ticks ) * 2.5
> fix: (Cherry-pick) update CXL Host exerciser latency calculations (#3088)

- include/opae/vfio.h
- libraries/libopaevfio/opaevfio.c
- libraries/plugins/vfio/opae_vfio.c
- Use results of earlier device walks instead of reopening devices.
- Add a lightweight check for busy devices.
> Improve VFIO device enumeration performance

- python/pacsign/pacsign/hsm_managers/openssl/openssl.py
The openssl hsm_manager looks for a list of possible versions for libcrypto. Hide a misleading "failed" message when one of the versions is not found by making it a debug message rather than an warning message.
*PR Title should start with one of the following tags: [Fix]/[Feature]/[Style]/[Update]*
*[Fix]- Bug Fix*
*[Feature]- for new feature*
*[Style]- Grammar or branding fix*
*[Update]-For an update to an existing feature*
------------- *Keep everything below this line* -------------------------
*Describe the issue, update, change or fix and **why***
> pacsign: hide confusing log message

- include/opae/cxx/core.h
- libraries/afu-test/afu_test.h
- samples/host_exerciser/host_exerciser.h
- samples/host_exerciser/host_exerciser_cmd.h
This change addresses [this ](https://hsdes.intel.com/appstore/article/#/14019997425) bug/case.
The bug is that the host_exerciser utility (which pushes traffic between the host and FPGA-attached DDR) would fail non-gracefully if the DDR calibration had failed. Fortunately the calibration status is reported by the dfl-emif driver via sysfs entries (one per mem channel). This change simply errors-out gracefully, with a useful error message, after reading the sysfs entries.
The host_exerciser utility is built on top of the afu_test framework. The corresponding AFU is exposed as a PCIe Virtual Function (VF). As described in the [docs](https://ofs.github.io/ofs-2023.2/hw/n6001/user_guides/ug_qs_ofs_n6001/ug_qs_ofs_n6001/#447-host-exercisor-modules), the user must first bind the VF endpoint to …
> [Fix] - Check memory calibration status before running host_exerciser

- binaries/opae.io/opae/io/utils.py
The 'opae.io init' command can fail to bind the vfio-pci driver when the IOMMU is disabled, leaving the system seemingly unable to bind another driver. The fix is to check if the IOMMU is enabled before even attempting to bind the vfio-pci driver.
> opae.io: Fix error handling when binding the vfio-pci driver fails

- libraries/libboard/board_cmc/board_cmc.c
The CMC platform does not support SDM PR and SR key hashes/cancel keys; therefore, remove them from the CMC board module 
Update the security key enumeration and read sysfs attribute logic into table format.
> fpgainfo: Remove the sdm hash and cancel keys from CMC fpgainfo security

- samples/host_exerciser/host_exerciser_cmd.h
Cherry-pick of changes in d005f448c18a70cbd95fc1b19649168ef136c5e9
> [Update] Add improved error message for buffer allocation failure in HE-MEM (#3096)

- python/opae.admin/opae/admin/utils/progress.py
fpgasupdate progress bars display 200% or 300% for root key hash and cancel key programming, which exceeds 100%.
set the progress bar maximum to 100% if the computations exceed 100.
> fpgasupdate:set the progress bar's maximum value to 100% if it exceeds

- samples/host_exerciser/host_exerciser.h
- samples/host_exerciser/host_exerciser_cmd.h
New API version exported by HW includes a CSR with the bus width.
HE LB
> [Update] - Add support to host_exerciser for varying HE LB data bus widths

- libraries/afu-test/afu_test.h
- samples/host_exerciser/host_exerciser.h
- samples/host_exerciser/host_exerciser_cmd.h
* host_exerciser:support no FPGA mgmt PF instances
Issue: The host exerciser fails to execute on Devkits if it does not support FPGA management PF. The host exerciser enumerates FME and quits the program if the bitstream does not support it.
The I series-DK and F series-DK have multiple host exerciser AFUs on separate PCIe bus, device functions.
fix: If the bitstream does not support FME, perform the host exerciser tests and print message.
host_exerciser --pci-address 0000:03:00.2 lpbk
host_exerciser --pci-address 0000:04:00.2 lpbk
opae.io ls
[0000:03:00.0] (0x8086:0xbcce 0x8086:0x1771) Intel Acceleration Development Platform N6001 (Driver: dfl-pci) [0000:04:00.7] (0x8086:0xbccf 0x8086:0x1771) Intel Acceleration Development Platform N6001 (Driver: None) [0000:04:00.5] (0x8086:0xbccf …
> (Cherry-pick) host_exerciser:support no FPGA mgmt PF instances (#3108)

- samples/host_exerciser/host_exerciser_cmd.h
Don't check EMIF calibration when running in ASE. The required access token is not available.
> host_exerciser: fix ASE simulation

- samples/host_exerciser/host_exerciser_cmd.h
Reference FIMs pass only a single bank of local memory to HE MEM. Instead of building a size matcher for what is supposed to be a simple test, HE MEM accepts the loss of wide host data flowing through narrow local memory.
HE MEM version 4 exposes the local memory width in a CSR.
New HW on n6001, iseries-dk_x16
> host_exerciser: correct handling of local memory width

- platforms/platmgr/tools/afu_platform_config.py
Due to the order that SystemVerilog header files are processed, setting a macro in an AFU's sources file may not affect the FIM's afu_main(). Add support for writing macros to the PIM interface header file that afu_main() includes explicity.
> platform: add a mechanism for AFU's to set platform macros

- samples/host_exerciser/host_exerciser_cmd.h
Buffer comparison varies by FPGA configuration. Stop calling direct memory comparison in interrupt test mode. The caller of he_interrupt() already does the proper test.
Gen5x16 FPGA
> host_exerciser: fix buffer comparison in interrupt test mode

- binaries/hssi/ethernet/hssistats.py
The "port_index" used while collecting HSSI statistics is actually an index into a row in the list of statistics counters. Changed to "stat_index".
> hssistats: fix variable name

- python/opae.admin/opae/admin/sysfs.py
- python/opae.admin/opae/admin/tools/pci_device.py
- python/opae.admin/opae/admin/utils/process.py
Hot unplug/plug alone does not trigger a reset. Add warm reset as a side effect of unplugging a card after it has been removed.
> pci_device: Add bridge reset when a device is unplugged

- python/opae.admin/opae/admin/sysfs.py
- python/opae.admin/opae/admin/tools/pci_device.py
- Wait for data link active after triggering a bridge's secondary device reset.
- Move reset to a separate command that unloads drivers, then devices, triggers warm reset on FPGAs, and finally rescans and clears errors.
Fixes: c97c3f2863f0 ("pci_device: Add bridge reset when a device is unplugged (#3143)")
Tested designs with and without VFs, confirmed that warm reset is raised using SignalTap.
> pci_device: improved reset sequence

- libraries/plugins/xfpga/usrclk/fpga_user_clk.c
The CSR interface for changing the user clock frequency relies on sequence numbers to detect the next command. In normal operation, a command stream ends by forcing the hardware sequence counter to zero. If the command stream is interrupted, the sequence number may be left non-zero. Update the command stream to start counting from the current sequence number in hardware.
Forced non-zero starting seq on HW, confirmed that commands were detected with Signal Tap.
> opae: fix user clock configuration sequence numbers

- libraries/plugins/xfpga/CMakeLists.txt
- libraries/plugins/xfpga/usrclk/fpga_user_clk.c
- libraries/plugins/xfpga/usrclk/fpga_user_clk_int.h
- libraries/plugins/xfpga/usrclk/fpga_user_clk_type1.c
- libraries/plugins/xfpga/usrclk/fpga_user_clk_type2.c
- tests/xfpga/CMakeLists.txt
Agilex 5 uses a new masked read-modify-write interface in hardware. OFS defines a new general interface (type 2) that allows software to set the address, value and mask for an IOPLL register to update. At the moment it is used only by Agilex 5.
The M, N, C0 and C1 values for Agilex 5 and 7 are the same.
> userclk: add support for Agilex 5 configuration

- packaging/opae/deb/opae-devel.install
- packaging/opae/deb/opae-extra-tools.install
- packaging/opae/deb/opae.install
Deb package: Changed dots to underscores in debian install files
Take a look at PEP 427 [https://peps.python.org/pep-0427/].which specifies that dots in the project name are normalized to underscores in the wheel filename for compatibility and to avoid issues with filesystems and tooling.
> [Fix]- Ubuntu 24.04 debian package build issue

- libraries/plugins/xfpga/usrclk/fpga_user_clk.c
Agilex 5 user clock reset was unreliable with the previous timeout.
> [Fix] userclk: increase the reset delay

- tests/pyopae/test_sysobject.py
Replaced function assertEquals with assertEqual as it deprecated.
> [Fix] : opae-unit test failing in ubuntu 24.04 for use of deprecated function
