- common/include/opae/access.h
> doc: add note about freeing shared resources

- ase/api/src/buffer.c
- ase/api/src/common.c
- ase/api/src/common_int.h
- ase/api/src/enum.c
- ase/api/src/event.c
- ase/api/src/mmio.c
- ase/api/src/reconf.c
- ase/api/src/token.h
- ase/api/src/umsg.c
- ase/sw/app_backend.c
- ase/sw/ase_common.h
- ase/sw/ase_ops.c
- ase/sw/protocol_backend.c
- Fix warnings with UNUSED_PARAM for unused arguments
- Fix warnings in protocol_backend
> ASE: Fix Warnings seen during ASE build

- samples/hello_events.c
Use poll() instead of select() to listen for events
Unset the inject error register after triggering FME event
> Refactor hello_events sample

- libopae/src/event.c
libopae-c: add NULL pointer check in event.c
> libopae-c: add NULL pointer check in event.c

- samples/hello_events.c
- Add goto statement so that inject error thread executes the appropriate cleanup statements
> Update hello_events for appropriate cleanup

- doc/opae-c++/opaecxx.md
Update documentation  and uml diagrams to reflect some of the latest changes in C++ API.
> c++: Update documentation

- libopae/src/mmio.c
Changes:
-Add mmap mmio region address to workspace list
> OPAE: Fix mmap mmio region

- tools/hssi/config_app.cpp
Becasue the `register_command_handler` uses the minimum number of
arguments and because the command processor checks this, it isn't
required in the command handler functions. This removes checks for
arguments size in the command handler functions.
> hssi: Remove args.size check in command functions

- README.md
* Change the README to markdown
* Add a badge to travis build to indicate build status
> Change README to md and add travis badge

- libopae++/include/opaec++/dma_buffer.h
- libopae++/include/opaec++/handle.h
- libopae++/include/opaec++/properties.h
- libopae++/include/opaec++/pvalue.h
- libopae++/include/opaec++/token.h
- libopae++/src/dma_buffer.cpp
- libopae++/src/handle.cpp
- libopae++/src/properties.cpp
- libopae++/src/token.cpp
Adds logging and exceptions for the current error paths.
> libopae++: add logging and exceptions

- tools/packager/afu_json_mgr.py
Includes the requested user clock frequencies.
> Emit more state as C/Verilog headers from AFU JSON

- ase/scripts/generate_ase_environment.py
- platforms/scripts/afu_synth_setup_std
- stdout may not be connected in some batch environments.
> Don't use sys.stdout.encoding for default encoding on byte strings

- tools/mmlink/main.cpp
Prior to this change, mmlink had the following errors in its
command-line parsing.
* The program did not respond to -h nor --help
* The names of the long options, eg --tcpport, did not match those
appearing in the help message.
* The IP address field stored in the command params did not support a
true string IP address. This meant that the IP address was required to
be input as an integer value, accounting for the correct byte
host/network ordering.
This change addresses these issues.
> mmlink: fix command line options (#154)

- libopae++/CMakeLists.txt
- libopae++/samples/hello_fpga-1.cpp
Add hello_cxxcore which is a C++ version of hello_fpga using the opaecxx-core layer.
> opaecxx: Add hello_fpga version using opaecxx-core

- common/include/opae/cxx/handle.h
- libopae++/src/handle.cpp
This adds a reset function to the handle class.
> opaecxx: Add reset function to handle class

- libopae++/samples/hello_fpga-2.cpp
This implements hello_fpga using a hypothetical c++ API - This will not build
> opaec++: Add second hello_fpga that uses a second c++ API

- tools/coreidle/coreidle.c
- tools/ras/main.c
- tools/userclk/main.c
Changes:
- Replace strlen() with strlen_s()
- Replace snprintf () with snprintf_s_X ()
> tools: Replace string functions with secure safe string

- tools/fpgabist/dma/fpga_dma_test.c
Cherry picking changes from afu repo for the use of clock_gettime in the fpga_dma_test
For more accurate DMA bandwidth timing.
> Cherry-pick: Use clock_gettime for measuring time (#294)

- cmake/modules/test_config.cmake
- tests/CMakeLists.txt
Refactor tests/CMakeLists.txt
Create cmake/module/test_config.cmake file to contain tests releated
CMake functions and macros.
> Refactor tests/CMakeLists.txt

- cmake/modules/packaging.cmake
- platforms/CMakeLists.txt
- platforms/scripts/CMakeLists.txt
- platforms/scripts/afu_platform_config
- platforms/scripts/platmgr/__init__.py
- platforms/scripts/platmgr/emitcfg.py
- platforms/scripts/platmgr/jsondb.py
- One module for loading JSON dbs
- One module for emitting configuration files
- Teach Python zipper to handle sources that are updated by CMake
> Break afu_platform_config into multiple modules

- common/include/opae/cxx/accelerator.h
- libopae++/samples/hello_fpga-2.cpp
- libopae++/src/accelerator.cpp
- tests/CMakeLists.txt
- tests/unit/gtCxxReset.cpp
* Add accelerator::reset function
* Add API tests
* Enable usage of C++  APIs  in hello_fpga-2.cpp
> opae++: add accelerator::reset fn

- ase/rtl/device_models/dcp_emif_model_basic/emif_ddr4.v
Signed-off-by: Deepak Unnikrishnan <deepak.unnikrishnan@intel.com>
> Fix byteenable in the basic memory model

- cmake/modules/test_config.cmake
- tests/function/gtOpenClose.cpp
Enable Open and Close tests with MOCK driver
> Enable Open and Close tests with MOCK driver

- cmake/modules/test_config.cmake
- tests/CMakeLists.txt
- tests/unit/gtCxxMMIO.cpp
Add tests for class handle's MMIO API.
> libopae++: add MMIO tests

- tools/base/fpgainfo/CMakeLists.txt
- tools/base/fpgainfo/fpgainfo.py
This will install one file (fpgainfo) which is a zipped file containing the required modules.
> fpgainfo: Change fpgainfo to be zipped

- doc/doxygen/Doxyfile.in
Remove obsolete variables HTML_ALIGN_MEMBERS & USE_INLINE_TREES
> Remove obsolete variables HTML_ALIGN_MEMBERS & USE_INLINE_TREES

- scripts/index_generator.py
* Beautify the landing page
* Sort the version number links
> Modify documentation landing page

- scripts/index_generator.py
* Beautify the landing page
* Sort the version number links
> Modify documentation landing page (#347)

- common/include/opae/cxx/core/handle.h
- libopae++/src/handle.cpp
Also cleanup some doxygen markup comments
> c++core: Make handle::close a public function

- tools/extra/hssi/mdio.cpp
This is a workaround to account for lack of synchronization in mdio controller.
> hssi: add delay in mdio

- doc/src/install_guide/installation_guide.md
Update FIM version for release products.
> Update FIM version for release products

- libopae/src/bitstream.c
- tools/extra/ras/main.c
> libopae: fix issues identified by checkers

- cmake/modules/create_python_dist.cmake
TODO: Add macro/function to add submodules in the package
> add cmake create_python_dist function

- tests/function/gtCxxExcept.cpp
Add test for src_location's copy-assignment operator.
> libopae-cxx-core: add test for src_location

- cmake/modules/test_config.cmake
- tests/unit/gtsysfs.cpp
changes:
- add sysfs enum test cases to improve code coverage
> tests: add sysfs test case to increase code coverage numbers

- libopae/src/buffer.c
- tests/function/gtBuffer.cpp
Changes:
Check NULL bufffer
Check zero buffer length
> libopae: fpgaPrepareBuffer input paramater validate

- tests/mock.c
Fix build warnings regarding unused result of write().
> mock: fix build warnings

- ase/sw/app_backend.c
- ase/sw/ase_common.h
- ase/sw/ase_strings.c
- ase/sw/protocol_backend.c
ASE: cherry pick git commit 3b27826 from master for secure implementation of scanf in ase.
> ASE: implemented secure version of scanf in ase (#548)

- ase/sw/protocol_backend.c
> ASE: klocwork fix for ASE

- ase/sw/protocol_backend.c
ASE: added null pointer checking for received message
> ASE: added null pointer checking for received message

- ase/sw/protocol_backend.c
ASE: cherry pick fix from release/1.1 branch
> ASE: added null pointer checking for received message (#573)

- ase/rtl/ase_svfifo.sv
- ase/rtl/ccip_checker.sv
- ase/rtl/ccip_emulator.sv
Improved ccip_emulator.sv code readability by correcting the indentation and removing tabs.
> ASE: coding style improvement

- libopae/src/sysfs.c
- libopae/src/sysfs_int.h
- tests/unit/gtsysfs.cpp
add sysfs_write_u32 function that writes a hex string of the 32-bit
number
> add 32-bit of sysfs write fn

- common/include/opae/sysobject.h
- libopae/CMakeLists.txt
- libopae/src/sysobject.c
- tests/CMakeLists.txt
- tests/unit/gtsys.cpp
* Rename sys.h and sys.c to sysobject.h and sysobject.c
* Implement fpgaWriteObjectBytes, and fpgaReadObjectBytes functions
* Also change fn signature of fpgaWriteObjectBytes to use len output
param
* Rename gtunit in CMake to gtunit-sysobject
> Rename sys file, implement RW Bytes ops

- tests/common_test.cpp
- tests/common_test.h
- Fix the unused parameter errors
> OPAE: Fix the line endings and unused parameter error

- tests/function/gtEnumerate.cpp
Re-enabled gtest that's working.
> Enabled gtest LibopaecEnumFCommonALL.DISABLED_enum_drv_021

- ase/sw/ase_common.h
- ase/sw/ase_ops.c
- ase/sw/ase_strings.c
- ase/sw/mem_model.c
- ase/sw/randomness_control.c
Clean up the unused functions in ASE
ASE Regression tests passed.
> ASE: removed unused functions

- samples/hello_events.c
Fixed the error case where fpga_events fails fpgaOpen() and segfaults closing the unassigned handle.
> Fixed fpgaOpen() error case goto.

- ase/sw/app_backend.c
- ase/sw/ase_common.h
- ase/sw/ase_ops.c
- ase/sw/error_report.c
- ase/sw/mem_model.c
- ase/sw/protocol_backend.c
- This it part 1 of the ASE code coverage improvement
> ASE: coverage improvement for ASE client and server

- scripts/cover.sh
- testing/CMakeLists.txt
- testing/unit/events_test.cpp
* add new executable, munit-opae-c-events which compiles in some files
from the events api and fpgad
* add basic events unit test (parameterized) fixture that controls fpgad
server_thread thread
> add events unit tests

- tools/base/fpgaconf/CMakeLists.txt
- tools/base/fpgaconf/bitstream-tools.h
- tools/base/fpgaconf/fpgaconf.c
Changes:
- Removed dependency bitstream.c
> tools: fpgaconf supports new plug-in architecture

- scripts/cover.sh
- testing/CMakeLists.txt
- testing/unit/munit-metadata-c.cpp
Validate tests by sending in invalid bitstream guids.
> Add in metadata unit tests

- libopae/CMakeLists.txt
- samples/CMakeLists.txt
- samples/hello_afu/sw/CMakeLists.txt
- samples/hello_mpf_afu/sw/CMakeLists.txt
- tests/sys/CMakeLists.txt
- tools/base/fpgaconf/CMakeLists.txt
- tools/base/fpgad/CMakeLists.txt
- tools/extra/c++utils/CMakeLists.txt
- tools/extra/coreidle/CMakeLists.txt
- tools/extra/fpgadiag/CMakeLists.txt
- tools/extra/pac/fpgabist/bist/CMakeLists.txt
- tools/extra/pac/fpgabist/dma/CMakeLists.txt
- tools/extra/ras/CMakeLists.txt
Conflicts:
libopae/CMakeLists.txt
> Fixes for local build of libjson-c

- testing/xfpga/test_object_c.cpp
Added a few test cases to test_object_c.
> Added sysobject test cases.

- libopae/api-shell.c
- libopae/plugins/xfpga/userclk.c
- testing/CMakeLists.txt
- testing/opae-c/test_usrclk_c.cpp
Fix bugs in fpgaSetUserClock and fpgaGetUserClock. Add opae-c level
test coverage.
> tests: add opae-c layer tests for usrclk

- cmake/config/config.h.in
- libopae/init.c
- testing/CMakeLists.txt
- testing/opae-c/test_init_c.cpp
Add -DSTATIC mechanism for tests.
> tests: add opae-c tests for init.c

- testing/xfpga/test_wsid_list_c.cpp
Include random head for default_random_engine generator declaration.
> Include random header

- testing/xfpga/test_reconf_c.cpp
Added a few test cases to xfpga reconf tests.
> Added xfpga reconf test cases.

- testing/xfpga/test_token_list_c.cpp
Added test cases for token_list.c for the failed to lock mutex cases.
> Added test cases for token list.

- pyopae/README.md
Added DSM_STATUS constant and set it to value currently used by NLB.
This is also the same offset used in hello_fpga.c
> Update README.md for correct DSM offset

- tools/extra/pac/fpgabist/bist_common.py
- tools/extra/pac/fpgabist/fpgabist
Improved BDF parsing to fix issue when trying to find fpga on different platforms.
> fix bdf parsing fpgabist

- scripts/cover.sh
- testing/CMakeLists.txt
- testing/fpgaconf/test_fpgaconf_c.cpp
- testing/fpgad/test_errtable_c.cpp
- testing/fpgad/test_fpgad_c.cpp
- tools/base/fpgaconf/bitstream-tools.h
- tools/base/fpgaconf/fpgaconf.c
Re-enable problematic fpgad test.
> tests: add fpgaconf unit tests

- platforms/platform_if/rtl/platform_if_macros.vh
- platforms/platform_if/rtl/platform_shims/platform_shim_ccip_std_afu.sv
- platforms/scripts/afu_platform_config
- platforms/scripts/platmgr/emitcfg.py
- platforms/scripts/platmgr/jsondb.py
- New preprocessor macro indicating whether a port is a vector.
- Improved error checking for platform/AFU vector mismatch.
- Improved reporting when encountering JSON formatting errors.
> Improved support for platform interface ports that are vectors.

- .travis.yml
- scripts/build-pypi.sh
Generate python source distribution package with each build and
upload it to PyPi whenever a new tag is created.
> CI: Automate python source dist upload to PyPi

- libopae/plugins/xfpga/sysfs.c
- testing/xfpga/test_sysfs_c.cpp
Add a replacement to strdup which uses safestring strcpy version
> Add a strdup replacement

- common/include/opae/init.h
- libopae/api-shell.c
- libopae/init.c
Performs OPAE instance destruction. (counterpart to fpgaInitialize)
> opae-c: add fpgaFinalize API

- common/include/opae/enum.h
- common/include/opae/event.h
- common/include/opae/properties.h
- common/include/opae/sysobject.h
Add a note to *Destroy doxygen regarding passing an invalid pointer.
> doxygen: update *Destroy docs

- testing/xfpga/test_properties_c.cpp
Updated the xfpga properties tests to enumerate based on the current platform's device id.
> Updated xfpga properties tests to work on hw.

- testing/xfpga/test_reconf_c.cpp
Updated the xfpga reconf tests to enumerate based on device id.
Separated the mock only tests.
> Updated xfpga reconf tests to work on hw.

- samples/hello_events.c
- testing/hello_events/test_hello_events_c.cpp
- tools/base/fpgad/errtable.c
Fix bug in fpgad. The fme.x/errors/fatal_errors was renamed to
fme.x/errors/catfatal_errors in the driver.
> tests: update hello_events tests for hw

- doc/src/fpga_api/plug_guide/readme.md
(cherry-pick from feature/plugin-api)
> doc: add plugin developer's guide (#830)

- testing/xfpga/test_reconf_c.cpp
Updated the test expectations with the expected hw platform behavior.
Updated the have_powermgmt check to be specific to the device that we are running on.
Same changes from PR #839.
> Updated xfpga reconf tests with expected hw platform behavior.

- testing/xfpga/test_mock_errinj_c.cpp
> Verify and separate xfpga mock errinj tests for hw vs mock

- testing/xfpga/test_umsg_c.cpp
> Verify and separate umsg tests for hw and mock

- testing/opae-c/test_buffer_c.cpp
> Verify opae-c buffer test works on hw

- testing/opae-c/test_props_c.cpp
> Verify opae-c properties tests work on hw

- testing/opae-c/test_reset_c.cpp
> Verify opae-c reset tests for hw

- scripts/cover.sh
- testing/opae-c/test_mmio_c.cpp
> Verify opae-c mmio tests work for hw

- testing/opae-c/test_hostif_c.cpp
> Separate opae-c hostif test for mock only

- testing/opae-c/test_usrclk_c.cpp
> Verify opae-c usrclk tests work on hw

- testing/opae-c/test_umsg_c.cpp
> Verify opae-c umsg tests work on hw

- testing/opae-c/test_open_c.cpp
> Modify invalid opae-c tests for mock only

- testing/opae-c/test_error_c.cpp
> Verify opae-c error tests work on hw

- testing/opae-c/test_object_c.cpp
> Verify opae-c object tests work on hw

- ase/Makefile
- ase/scripts/generate_ase_environment.py
- Pick the right libraries for the target platform automatically.
- Add support for VHDL that needs megafunctions, etc.
> ASE now invokes Quartus to choose megafunction and tech. libraries

- ase/sw/ase_host_memory.c
This solves a regression when simulating on BDX (HARP systems).
> Mask the ASE PA/VA XOR mask one bit smaller

- testing/xfpga/test_afu_metrics_c.cpp
- testing/xfpga/test_metrics_c.cpp
- testing/xfpga/test_metrics_utils_c.cpp
Please enter the commit message for your changes. Lines starting
> tests: fix metric test cases errors

- tools/extra/pac/fpgaflash/CMakeLists.txt
- tools/extra/pac/fpgaflash/fpgaflash
Currently the rebase from external to internal is stopped because of conflicts that arose in fpgaflash. This PR when merged in master and the rebased in master-x should be able to resolve those conflicts. Please review this PR ASAP as this blocks anything from master to go into master-x.
> Attempt to fix merge confilcts with master-x

- ase/scripts/generate_ase_environment.py
- ase/sw/app_backend.c
- ase/sw/ase_common.h
- ase/sw/ase_ops.c
1. Fix mmio pkt structure if statement being flagged as not-properly indented.
2. Add stat code to check if directory is valid before opening.
3. Remove double 'import subprocess' on generate_environment.py and apply Python linter
> Fixes for SDL

- testing/CMakeLists.txt
- testing/coreidle/test_main_c.cpp
- testing/fpgaconf/test_fpgaconf_c.cpp
- testing/fpgad/test_fpgad_c.cpp
- testing/fpgainfo/test_fpgainfo_c.cpp
- testing/ras/test_main_c.cpp
- testing/userclk/test_userclk_c.cpp
Examined all the tools tests in the new testing infrastructure. Validate returned results from parsecmd/main functions with invalid params.
> Added additional tests for tools to meet SDL req.

- libopae/plugins/xfpga/sysfs.c
This is a cherry-pick from a fix that went into release/1.2
> xfpga: fix potential memory leaks in sysfs.c

- libopae/plugins/xfpga/sysfs.c
- tools/base/fpgad/fpgad.c
> analysis: fix issues identified by scanners

- tools/base/fpgad/fpgad.c
* fpgad: expand $HOME directory before validating
Use canonicalize_file_name to expand homedir.
If the directory does not exist, result will be null.
If it does exist, used the canonical name when checking if it's rooted
at /home.
This is a cherry-pick from #969
> fpgad: expand $HOME directory before validating 

- tools/base/argsfilter/argsfilter.c
cherry pick the fix from master branch.
> fix KW issues

- libopae/plugins/xfpga/metrics/bmc/bmc.c
- libopae/plugins/xfpga/metrics/metrics_metadata.h
- libopae/plugins/xfpga/metrics/metrics_utils.c
merge changes from release branch 1.1.2 to master
> libopae:fix metrics static code analysis

- samples/object_api.c
> add a check for null after calling calloc (#973)

- doc/src/fpga_api/fpga_api.rst
- doc/src/fpga_api/fpga_cxx_api.rst
- doc/src/fpga_api/fpga_python_api.rst
This updates the sphinx .rst files used to point to objects used to
generate documentation for sysobject and errors C++ API
> docs: Update sphinx rst files for new APIs

- testing/xfpga/test_afu_metrics_c.cpp
- testing/xfpga/test_bmc_c.cpp
- testing/xfpga/test_metrics_c.cpp
- testing/xfpga/test_metrics_utils_c.cpp
- testing/xfpga/test_metrics_vector_c.cpp
Ran clang format, spell check, remove copy/paste duplicates
> Clang format in testing/xfpga

- common/include/opae/dma.h
- common/include/opae/feature.h
- common/include/opae/types.h
- common/include/opae/types_enum.h
- libopae/adapter.h
- libopae/api-shell.c
- libopae/opae_int.h
- libopae/plugins/CMakeLists.txt
- libopae/plugins/xfpga/feature_plugins/dma_sav/intel-dma/plugin.c
- libopae/plugins/xfpga/feature_plugins/feature_adapter.h
- libopae/plugins/xfpga/feature_plugins/feature_api.c
- libopae/plugins/xfpga/feature_plugins/feature_int.h
- libopae/plugins/xfpga/feature_plugins/feature_pluginmgr.c
- libopae/plugins/xfpga/feature_plugins/feature_pluginmgr.h
- libopae/plugins/xfpga/feature_plugins/feature_token_list.c
- libopae/plugins/xfpga/feature_plugins/feature_token_list_int.h
- libopae/plugins/xfpga/plugin.c
- libopae/plugins/xfpga/xfpga.h
- scripts/cover.sh
- testing/CMakeLists.txt
- testing/xfpga/test_feature_enum_c.cpp
- testing/xfpga/test_feature_open_c.cpp
- testing/xfpga/test_feature_pluginmgr_c.cpp
- testing/xfpga/test_feature_token_list_c.cpp
All the code changes for feature branches need to create a PR for reviewing: 
-- memory leaks
-- dead lock 
-- variable naming convention
-- other fixes
> Made some fixes from code review feedbacks

- testing/coreidle/test_main_c.cpp
- testing/fpgaconf/test_fpgaconf_c.cpp
- tools/extra/coreidle/main.c
Broke up commits from PR #1000
> Added nullbyte tests for coreidle and fpgaconf

- libopae/plugins/xfpga/enum.c
- libopae/plugins/xfpga/reconf.c
- libopae/plugins/xfpga/sysfs.c
- libopae/plugins/xfpga/sysfs_int.h
- libopae/plugins/xfpga/usrclk/user_clk_pgm_uclock.c
- libopae/plugins/xfpga/usrclk/user_clk_pgm_uclock.h
- tests/sys/utils/common_pr.cpp
- tests/sys/utils/common_sys.h
- tests/sys/utils/common_sysfs.cpp
This touches various files but the only changes is the spelling from
syfs to sysfs.
> fix spelling of syfs to sysfs

- testing/xfpga/test_reconf_c.cpp
Separate out positive test case
> Resolve reconf leak

- .github/CODEOWNERS
This is a cherry-pick from release/1.3.0 to master
> Add RPM specfile under the ownership of ci team (#1107)

- libopae/pluginmgr.c
- testing/opae-c/test_pluginmgr_c.cpp
* Switch to using $HOME instead of ~ in config file paths
* Add `resolve_file_name` that will resolve paths with environment
variables
* Add test for finding a config file in one of the pre-determined paths
> opae-c: fix finding of cfg files

- testing/fpgad/test_command_line_c.cpp
- testing/fpgad/test_fpgad_c.cpp
- tools/base/fpgad/command_line.c
Update command_line.c unit tests after adding configuration file
support.
> fpgad: update unit tests for command line

- common/include/opae/types.h
- libopae/plugins/xfpga/CMakeLists.txt
- libopae/plugins/xfpga/metrics/afu_metrics.c
- libopae/plugins/xfpga/metrics/max10_metadata.h
- libopae/plugins/xfpga/metrics/mcp_metadata.h
- libopae/plugins/xfpga/metrics/metrics.c
- libopae/plugins/xfpga/metrics/metrics_int.h
- libopae/plugins/xfpga/metrics/metrics_max10.c
- libopae/plugins/xfpga/metrics/metrics_max10.h
- libopae/plugins/xfpga/metrics/metrics_utils.c
- libopae/plugins/xfpga/metrics/vector.c
- libopae/plugins/xfpga/metrics/vector.h
- testing/CMakeLists.txt
- tools/base/fpgametrics/fpgametrics.c
> xfpga: cherry-pick Metrics api supports dcp cards

- tests/common_test.h
Fix the ASE test build error on trunk for running the ASE regression tests.
> ASE: fix the compilation error for gtase test

- testing/CMakeLists.txt
- testing/fpgaconf/test_fpgaconf_c.cpp
- tools/base/fpgaconf/CMakeLists.txt
- tools/base/fpgaconf/fpgaconf.c
Remove local implementations of functions now provided by libbitstream.
> fpgaconf: switch to libbitstream

- libopae/plugins/xfpga/metrics/threshold.c
Signed-off-by: Chip Bilbrey <chip.bilbrey@intel.com>
> Remove deceptive indentation

- opae.spec.in
Add bist files to address internal build issues.
> Add Bist missing files

- scripts/cover.sh
* Fixed some cover.sh to add back some coverage data.
> Fixed the cover.sh

- opae.spec.in
This reverts commit c9424415a83591e5c1f60ef7d563354561b354ed.
> Revert "Add Bist missing files"

- tools/base/fpgad/plugins/fpgad-vc/fpgad-vc.c
Pull the high/low temperature trip points down/up by 5 degrees.
Pull the high/low power trip points down/up by 5%.
This is done to enable catching overages before the BMC takes action.
> fpgad-vc: adjust sensor trip points

- testing/CMakeLists.txt
- testing/board/test_board_rc.cpp
- tools/base/libboard/board_rc/CMakeLists.txt
- tools/base/libboard/board_rc/board_rc.c
- tools/base/libboard/board_rc/board_rc.h
- Reads BMC version
- Read power down root cause
- Read reset root cause
- Prints board specific information
> Tools: add board specific information lib for tools

- tools/base/fpgad/plugins/fpgad-vc/fpgad-vc.c
Update the method used to remove the device driver to that of super-rsu:
* Write 1 to the device's reset node.
* Write 1 to the remove node of the root bridge's child. (removes
all VC devices)
When rescanning,
* Write "on" to the power/control node of the root bridge's child.
* Write 1 to the rescan node of the root bridge's child.
> fpgad-vc: graceful shutdown models super-rsu flow

- tools/base/fpgad/plugins/fpgad-vc/fpgad-vc.c
fpgad-vc: graceful shutdown models super-rsu flow
> Cherry-pick from master to feature branch 73ef562

- tools/base/fpgad/plugins/fpgad-vc/fpgad-vc.c
Remove the code that was writing 1 to the root bridge device's
reset sysfsnode.
Fix the tripped sensor counter so that it correctly measures for
each device.
Remove extraneous cool down lock.
> fpgad-vc: don't write device reset node

- testing/hello_fpga/test_hello_fpga_c.cpp
Added missing changes from vista-creek branch that omitted the hello_fpga tests from running on VC hw.
> Fixed missing testcase changes for VC.

- opae.spec.in
- tools/extra/pac/fpgaflash/CMakeLists.txt
- tools/extra/pac/fpgaflash/fpgaflash
- tools/extra/pac/fpgaflash/rsu.json
- tools/extra/pac/fpgaflash/super-rsu
- tools/extra/pac/fpgaflash/super-rsu-tests.md
Comments:
- VC branch flash tool works on RC,VC & DC fpga cards.
> tools: cherry-pick fpgaflash changes from vc

- doc/src/fpga_tools/fpgainfo/fpgainfo.md
- opae.spec.in
- merge fpgainfo doc changes
- merge opaespec changes
> opae: merge doc and rpm spec changes from internal to feature branch

- libopae/plugins/ase/api/src/buffer.c
The hardware version of fpgaPrepareBuffer() rounds up requests to huge pages.
The ASE equivalent tried to do this, but ultimately failed when inserting
non-page-size buffers in the simulated page table.
> Match the fpgaPrepareBuffer() huge page model better in ASE.

- samples/hello_fpga.c
- Don't time out quickly.
- Wait for activity to complete before releasing memory.
> Make hello_fpga behave better in ASE.

- common/include/opae/cxx/core/handle.h
- common/include/opae/mmio.h
- libopae/adapter.h
- libopae/api-shell.c
- libopae/plugins/ase/api/src/ase.h
- libopae/plugins/ase/api/src/mmio.c
- libopae/plugins/ase/api/src/plugin.c
- libopae/plugins/ase/rtl/ase_pkg.sv
- libopae/plugins/ase/rtl/ccip_emulator.sv
- libopae/plugins/ase/sw/app_backend.c
- libopae/plugins/ase/sw/ase_common.h
- libopae/plugins/xfpga/common_int.h
- libopae/plugins/xfpga/mmio.c
- libopae/plugins/xfpga/open.c
- libopae/plugins/xfpga/plugin.c
- libopae/plugins/xfpga/types_int.h
- libopae/plugins/xfpga/xfpga.h
- libopaecxx/src/handle.cpp
- testing/CMakeLists.txt
- testing/argsfilter/test_argsfilter_c.cpp
- testing/ase/test_mmio_c_ase.cpp
- testing/ase/test_sw_c_ase.cpp
- testing/fpgainfo/test_board_c.cpp
- testing/fpgainfo/test_fpgainfo_c.cpp
- testing/opae-c/dummy_plugin.c
- testing/opae-c/test_mmio_c.cpp
- testing/xfpga/test_mmio_c.cpp
- tools/base/argsfilter/argsfilter.c
- tools/base/fpgainfo/errors.c
Merge master into feature/upstream_drv_patchset2 to consume all the test changes from master in order to check tests and test coverage.
> Merge master into feature upstream drv patchset2

- doc/sphinx/index.rst.in
- libopae/plugins/xfpga/metrics/metrics_int.h
- libopae/plugins/xfpga/metrics/metrics_max10.c
- libopae/plugins/xfpga/metrics/metrics_max10.h
- libopae/plugins/xfpga/metrics/metrics_utils.c
- testing/xfpga/test_metrics_max10_c.cpp
- tools/base/fpgad/api/logging.c
-Doc changes
-Metrics changes for Max10
-KW issues
Cherry pick  VC metrics changes from VC release
https://github.intel.com/OPAE/opae-sdk-x/blob/release/rc-1.2.1/tools/libs/bmc/bmc.c
>  opae: cherry pick release 1.3.2 changes to master

- doc/src/drv_arch/drv_arch.md
Update driver architecture doc to reflect upstream driver patchset 2.
> doc: update driver arch. doc

- CMakeLists.txt
- python/CMakeLists.txt
- python/opae.admin/CMakeLists.txt
* Remove unneeded file substitutions.
* Remove unneeded git process stuff.
> cmake: plug python directory into build

- python/opae.admin/opae/admin/fpga.py
- python/opae.admin/opae/admin/tools/fpgaport.py
Update the fme class's release_port and assign_port to use the new
dfl driver IOCTL format.
> fpgaport: updates for dfl drivers

- opae-libs/plugins/xfpga/sysfs.c
> Revert "Fix possible buffer overflow"

- tests/board/test_board_d5005.cpp
- tools/libboard/board_common/board_common.c
bmc_root__hash to bmc_root_entry_hash
pr_root__hash to pr_root_entry_hash
sr_root__hash to sr_root_entry_hash
> tools: rename max10 hash keys

- python/opae.admin/opae/admin/utils/verifier.py
Result of WR request to have a more easily parse-able value printed for key cancellation and root entry hash programming bitstreams.
> Adding printing of programmed values

- tools/libboard/board_common/board_common.c
- tools/libboard/board_d5005/board_d5005.c
- tools/libboard/board_n3000/board_n3000.c
- tools/libboard/board_n3000/board_n3000.h
-Buffer Overflow - Array Index Out of Bounds
> tools: Static code analysis -  Buffer overflow

- tests/board/test_board_d5005.cpp
- tests/board/test_board_n3000.cpp
- tools/libboard/board_common/board_common.c
- tools/libboard/board_common/board_common.h
- tools/libboard/board_d5005/board_d5005.c
- tools/libboard/board_n3000/board_n3000.c
- BMC version syfs path changed in DFL driver
> tools: update board module with new sysfs path

- .github/workflows/python-static-analysis.yml
Signed-off-by: Asgard Marroquin <asgard.marroquin@intel.com>
> ci: create csv-formatted bandit log artifact

- python/opae.admin/opae/admin/fpga.py
* Change the sysfs paths for rsu to use ones that dfl driver will use.
* Add d5005 to supported devices.
> rsu: update sysfs paths, add support for d5005, 

- tests/dummy_afu/CMakeLists.txt
- tests/dummy_afu/test_dummy_afu.cpp
* Split up main tests for each subcommand
* Incorporate test fpgad for testing events
> dummy_afu: fixup dummy_afu tests

- opae.spec.in
Signed-off-by: Marroquin, Asgard <asgard.marroquin@intel.com>
> Add hssi tool to opae-devel rpm el7 package

- samples/dummy_afu/test_afu.h
- tests/dummy_afu/test_dummy_afu.cpp
* Add count argument that runs the test command given number of times
* Add timeout argument that waits up to given timeout (msec) for test
command
> dummy_afu: add count and timeout args

- samples/dummy_afu/test_afu.h
> test_afu: fix AFU ID printout

- doc/sphinx/index.rst.in
- doc/src/fpga_api/quick_start/readme.md
- doc/src/install_guide/installation_guide.md
> docs: scrub quick start and installation guides

- doc/src/fpga_tools/fpgad/fpgad.md
> docs: update the fpgad doc

- samples/dummy_afu/dummy_afu.h
Do not return a value from a void function.
> fix issues seen in static analysis

- tools/extra/fpgabist/dma_N3000/fpga_dma_test.c
> Fix issue identified by checkers.

- scripts/cover.sh
> coverage: remove -j to avoid SIGPIPE

- doc/src/fpga_api/quick_start/readme.md
- samples/hello_fpga/hello_fpga.c
1. support N3000 for hello_fpga
add a new argument to support N3000 for hello_fpga.
2. update quick start guide.
> update quick start guide

- CMakeLists.txt
- opae-libs/CMakeLists.txt
> Revert "Tswhison/fix vars"

- tools/extra/mmlink/remote_dbg/streaming/CMakeLists.txt
- tools/extra/mmlink/remote_dbg/streaming/common.c
- tools/extra/mmlink/remote_dbg/streaming/packet.c
- tools/extra/mmlink/remote_dbg/streaming/server.c
- tools/extra/mmlink/remote_dbg/streaming/sockets.c
- tools/extra/mmlink/remote_dbg/streaming/st_dbg_ip_driver.c
> Revert "mmlink: address el7 compile issues"

- .github/workflows/build-rpms.yml
- docker/fedora31/Dockerfile
Signed-off-by: Marroquin, Asgard <asgard.marroquin@intel.com>
> ci: build Fedora31 rpm packages

- .github/workflows/update-repo.yml
change input to reviewers a comma seperated list of users
> ci: fix use of auto pull request action

- cmake/FindSphinx.cmake
Change FindSphinx to find  python 3
> doc: change default python version for sphinx to 3

- docker/docs/Dockerfile
* add libedit-dev to list of packages
* use apt instead of apt-get
> ci: update docker file

- python/opae.admin/opae/admin/tools/opaevfio.py
> opaevfio.py: pass enable_sriov=1 to modprobe for vfio-pci

- doc/src/fpga_tools/fpgainfo/fpgainfo.md
- tools/fpgainfo/board.c
- tools/fpgainfo/main.c
- tools/libboard/board_common/board_common.c
> fix fpgainfo security help and update doc

- doc/sphinx/conf.py.in
- doc/src/fpga_tools/host_exerciser/host_exerciser.md
> doc: add documentation for host exerciser sample

- samples/host_exerciser/host_exerciser_lpbk.h
- samples/host_exerciser/host_exerciser_mem.h
HE-LB 56e203e9-864f-49a7-b94b-12284c31e02b
HE-MEM 8568ab4e-6ba5-4616-bb65-2a578330a8eb
> update new guid for host exerciser lpbk and mem

- plugins/vfio/opae_vfio.c
* Add code to unlock a mutex in fpgaGetIOAddress implmentation.
> vfio-plugin: unlock mutexes

- .github/workflows/build-rpms.yml
- docker/centos7.6/Dockerfile
- docker/fedora31/Dockerfile
- docker/fedora32/Dockerfile
- scripts/test-rpms.sh
* Add missing packages in docker files used for building images
* Add github actions step to test RPMs by running a new script,
test-rpms.sh which does:
* Installing all RPMs in CWD
* Running executables (with help option) to test that they are
installed
> ci: update RPM build/tests

- tools/libboard/board_n3000/board_n3000.c
Signed-off-by: Martin Hundebøll <mhu@silicom.dk>
> tools: libboard: n3000: update interface glob to linux-dfl-5.11

- samples/hssi/hssi_10g_cmd.h
> hssi: add --eth-ifc to override eth ifc detection

- afu-test/afu_test.h
Use regex_t in a unique_ptr with a custom deleter that calls regree.
> afu_test: fix memory leak in regex_t struct

- doc/sphinx/requirements.txt
Update to latest versions of:
* requests
* sphinx
* breathe
> doc: update packages in requirements.txt

- python/opae.admin/opae/admin/utils/verifier.py
- python/pacsign/pacsign/pacsign.py
Updates bitstreaminfo for 384-bit hashes, new signing types.
PACSign - add verification check for slot number.
> bitstreaminfo, PACSign: update bitstreaminfo for 384

- doc/src/fpga_tools/pci_device/pci_device.md
- python/opae.admin/opae/admin/tools/pci_device.py
* Add error handling for `vfs` operation
* Update documentation to reflect latest CLI
> opae.admin: update pci_device and doc

- doc/sphinx/requirements.txt
cherry-pick changes to pin Jinja2 2.11.3 in requirements.txt
> cherry-pick changes to pin Jinja2 2.11.3

- opae.spec
- packaging/opae/rpm/create
- Update fedora patch number 2 in spec and create rpm
>  update fedora patch number in spec file

- cmake/modules/FindCLI11.cmake
- external/CMakeLists.txt
* Add CLI11 finder in cmake/modules
* Refactor external/CMakeLists.txt to only fetch CLI11 when it can't
find it.
> cmake: add FindCLI11.cmake

- samples/hssi/hssi_afu.h
The glob path used to discover the ethernet interface name
was updated by recent driver changes. Support both the old
and the new formats.
> hssi: support new glob format for upstreamed drivers

- samples/host_exerciser/host_exerciser_cmd.h
> samples: host exerciser initialize default variable

- afu-test/afu_test.h
> afu_test: add `handle` method

- samples/n5010-ddr-test/n5010-ddr-test.c
The sample test source received too little testing before being
upstreamed, so make up for it now.
Signed-off-by: Martin Hundebøll <mhu@silicom.dk>
> samples: n5010-ddr-test: fix tests

- docker/centos7.6/Dockerfile
- docker/fedora31/Dockerfile
- docker/fedora32/Dockerfile
> ci: add pyyaml to Python requirements

- doc/sphinx/requirements.txt
> doc: pin pygments,urllib3 to 2.7.4,1.26.3

- doc/sphinx/requirements.txt
> doc: pin urllib3 to 1.26.4

- samples/host_exerciser/host_exerciser_cmd.h
> opae-samples: fix he loopback number of cache lines

- tools/extra/fpgadiag/opae/diag/fpgalpbk.py
Signed-off-by: Tianfei zhang <tianfei.zhang@intel.com>
Signed-off-by: Ananda Ravuri <ananda.ravuri@intel.com>
> fix the fpgalpbk issue

- python/opae.admin/opae/admin/utils/database.py
to keep bitstream_info.py in sync with recent PACSign changes.
> opae.admin: update database.py..

- ofs/umd/cpeng/ofs_cpeng.yml
- tests/ofs_cpeng/test_ofs_cpeng.cpp
* Update register map
* Update api functions to use changed registers
> update ofs_cpeng umd interface

- ofs/umd/cpeng/ofs_cpeng.yml
> ofs_cpeng: add all registers for completeness

- ofs/umd/cpeng/ofs_cpeng.yml
> ofs_cpeng: add error log messages

- tools/extra/qpafilter/qpafilter.py
Add class blob_writer that implements a "with protocol".
Extend create_blob_from_qpa() to create the blob output.
Changes short option for --override-temp to -O.  Adds
option -o, --output to specify the output blob name.
> qpafilter: mock up blob output

- tools/extra/qpafilter/qpafilter.py
Implement class blob_reader. blob_reader implements the iteration
protocol to decode and return each item in the given blob file,
presenting the human-readable data.
> qpafilter: implement qpafilter dump qpafilter.blob

- tools/extra/qpafilter/qpafilter.py
Adds option -o,--output for naming the destination of the
qpafilter dump sub-command, setting the default value to
sys.stdout.
Adds option -F,--format that takes values csv (default),
json, or yaml.
> qpafilter: add csv, json, and yaml output

- .github/workflows/build-rpms.yml
- docker/fedora33/Dockerfile
> ci: add fedora33 to rpm builds

- tools/extra/qpafilter/qpafilter.md
> qpafilter.md: add C back to degrees C

- tools/extra/qpafilter/qpafilter.py
Update blob_writer and blob_reader -> blob_reader_v0 to
comprehend the version 0 blob header format, including
the length field and 2 CRC's.
Add function get_blob_reader which parses the blob header
to discover the version, returning the appropriate reader
object matching the blob version.
Co-authored-by: Rodrigo Rojo <rodrigo.rojo@intel.com>
> qpafilter: implement header version 0

- tools/extra/fpgabist/dma_N3000/fpga_dma_test.c
> fpgabist: initialize dma_h to NULL

- tools/libboard/board_n3000/board_n3000.c
issues
- Result of function that may return NULL will be dereferenced
- Resource leak
> fix static code analyze tool issues.

- tools/extra/qpafilter/qpafilter.py
Instead of requiring the user to pass the sensor label as the lhs
of -O, allow passing the sensor ID instead. Perform the conversion
to int and the necessary dict lookup in read_qpa().
> qpafilter: allow -O option to specify sensor ID

- docker/fedora31/Dockerfile
- docker/fedora32/Dockerfile
- docker/fedora33/Dockerfile
Add jsonschema to list of python packages installed in docker file.
> ci: add jsonshema to docker image files

- docker/centos7.6/Dockerfile
> ci: add jsonschema to centos7.6 docker img

- tools/libboard/board_n6010/board_n6010.c
> opae-tools: fix static code analysis issue

- doc/sphinx/requirements.txt
> doc: pin babel version to 2.9.1

- tools/extra/qpafilter/qpafilter.md
- tools/extra/qpafilter/qpafilter.py
qpafilter show creates human-readable output for the input sensors
map file.
> qpafilter: add show command

- doc/sphinx/requirements.txt
> doc: pin babel version to 2.9.1 (#2037)

- doc/src/fpga_api/quick_start/readme.md
- command to enable virtual fpga functions
- bind pci-vfio to virtual functions
- command to run Host Exerciser Loopback tool
> doc: add iofs release1 install and setup

- ofs/apps/cpeng/hps.cpp
Round the image buffer to the nearest cacheline size (64).
> cpeng: round up img size to nearest cacheline

- tools/extra/opae.io/opae/io/utils.py
Signed-off-by: Sivaramakrishnan, VenkataramananX <venkataramananx.sivaramakrishnan@intel.com>
> Added device ids (af00, af01) in fpga_devices

- tools/extra/opae.io/opae/io/utils.py
Added device id (bcce) in fpga_devices.
Signed-off-by: Sivaramakrishnan, VenkataramananX <venkataramananx.sivaramakrishnan@intel.com>
> Added device id (bcce) in fpga_devices.

- tools/extra/qpafilter/qpafilter.py
The header ordering was previously incorrect - the version and
payload length fields had been swapped. This change corrects the
order.
Add function abstraction around CRC32 calculation - allows for
easily switching between packages/algorithms.
> qpafilter: fix header ordering

- opae.spec
- opae.spec.in
> packaging: remove opaememtest

- tools/extra/opae.io/pymain.h
> opae.io: print raw value in dfh walk

- samples/host_exerciser/host_exerciser.h
- samples/host_exerciser/host_exerciser_cmd.h
> host_exerciser: changes required for IRQ bringup

- tools/fpgainfo/fpgainfo.c
- tools/fpgainfo/portinfo.c
> fpgainfo: silence errors when afu_id not found

- tools/libboard/board_n5010/board_n5010.c
> tools: update recursive bmc and max10 version sysfs path for n5010

- samples/host_exerciser/host_exerciser.h
> tools:fix host exerciser command line interrupt default value

- ofs/apps/cpeng/hps.cpp
- ofs/umd/cpeng/ofs_cpeng.yml
- samples/host_exerciser/host_exerciser.h
- samples/host_exerciser/host_exerciser_cmd.h
> Merge latest master into release/2.0.4-1

- samples/host_exerciser/host_exerciser.h
- samples/host_exerciser/host_exerciser_cmd.h
> host_exerciser: register requested interrupt vector

- opae.spec.in
> cpeng: add hps/ofs* libraries for cpeng in rpm

- ofs/umd/cpeng/CMakeLists.txt
> cpeng: add cpeng driver to install components

- ofs/umd/cpeng/CMakeLists.txt
> cpeng: fix (again) install directive

- tests/fpgainfo/test_fpgainfo_c.cpp
- tests/fpgametrics/test_fpgametrics_c.cpp
- remove mock d5005 metrics tests
> test: update opae metrics tests

- samples/host_exerciser/host_exerciser_cmd.h
> host_exerciser: don't poll in IRQ mode

- ofs/apps/cpeng/hps.cpp
> cpeng: fix round-up of padding sz

- tests/board/test_board_n6010.cpp
- tools/libboard/board_common/board_common.c
- tools/libboard/board_n6010/board_n6010.c
- tools/libboard/board_n6010/board_n6010.h
- add list of profiles supported in N6010 ethernet
- fix port profile offset
> tools: fix fpgainfo phy command for N6010 card

- tools/libboard/board_common/board_common.c
> tools: fix static code analysis

- ofs/apps/cpeng/hps.cpp
* Move getting logger into the run function as that named logger won't
exist when the class is created but will exist when the run function is
called in afu_test.
* refactor chunking of the image data
* set default chunk size to page size (4096)
* change the chunking algorithm so that the file is read into the same
chunk instead of reading it into one large buffer and then chunking.
By doing this, we read the file into the same buffer each time but
we increment the destination offset by chunk size each iteration.
We also have to call ofs_cpeng_copy_chunk instead
ofs_cpeng_copy_image.
Main benefit of this is that we dont' have to use hugepages if the
chunk size is < 4k.
> cpeng: fix log, refactor chunking

- ofs/apps/cpeng/hps.cpp
Add more informative log information like when it is about to start,
chunk size, and number of chunks. Also add dmastatus_err function to
read dmastatus register and log debug registers if error is reported.
This follows the intended flow.
> cpeng: enhance error handling/logging

- tools/extra/hssi/ethernet/hssicommon.py
- change  hssi mailbox register poll interval to  1 micro seconds
- change  hssi mailbox register poll timeout to  1 seconds
> tools: update hssi mailbox register poll timeout

- ofs/apps/cpeng/hps.cpp
> cpeng: change chunking to align with chunk size

- ofs/apps/cpeng/hps.cpp
> cpeng: change to not add padding

- ofs/apps/cpeng/readme.md
Update documentation to reflect CLI changes to hps command.
> cpeng: update doc for latest changes

- ofs/apps/cpeng/hps.cpp
> cpeng: log when boot stages are verified

- tools/libboard/board_n6010/board_n6010.c
> Tools: fix static code analysis issue in board N6010 module.

- python/opae.admin/opae/admin/fpga.py
> opae.admin: paths updates for n6010

- tools/extra/opae.io/opae/io/utils.py
> opae.io: correct platform names

- tools/extra/opae.io/opae/io/utils.py
> Cherry pick 50b047e to release/2.0.7-1

- python/pacsign/pacsign-tests.sh
- python/pacsign/pacsign/hsm_managers/openssl/key_manager.py
> PACSign: add regression tests

- python/opae.admin/opae/admin/tools/rsu.py
> rsu: fix bug in error path

- scripts/unit-tests.sh
- tests/board/CMakeLists.txt
- tests/board/test_board_n6010.cpp
- tests/fpgainfo/CMakeLists.txt
- tests/fpgainfo/test_fpgainfo_c.cpp
- tools/fpgainfo/CMakeLists.txt
- tools/fpgainfo/board.c
- tools/fpgainfo/events.c
- tools/fpgainfo/events.h
- tools/fpgainfo/main.c
- tools/libboard/board_n6010/CMakeLists.txt
- tools/libboard/board_n6010/board_event_log.c
- tools/libboard/board_n6010/board_event_log.h
- tools/libboard/board_n6010/board_n6010.c
- tools/libboard/board_n6010/board_n6010.h
Example short output:
```
$ sudo fpgainfo events -b3
Boot 3
Power On Status Time                               : Thu Jan  1 01:23:04 1970
Status                                           : 0x22000000
Power On Code FPGA                             : 0x2
Power On Code CVL                              : 0x2
FPGA_Status                                      : 0x02ca9029
FPGA Page                                      : 0x1
FPGA Configued Page                            : 1
FPGA Config Timeline                           : 0
Flow Done                                      : 1
FSM State                                      : 0x9
FPGA_Config Status                               : 0x0007e412
Config Status                                  : 0x2
Config FW Seq Fail                             : 1 …
```
> n6010 event log

- samples/host_exerciser/host_exerciser.h
- samples/host_exerciser/host_exerciser_cmd.h
> samples: rename Device Status Memory structure

- python/opae.admin/opae/admin/tools/rsu.py
> (cherry-pick) rsu: fix bug in error path (#2231)

- opae-libs/include/opae/types.h
- opae-libs/libopae-c/api-shell.c
- opae-libs/plugins/vfio/dfl.c
- opae-libs/plugins/vfio/opae_vfio.c
- opae-libs/plugins/vfio/opae_vfio.h
- opae-libs/plugins/xfpga/bitstream.c
- opae-libs/plugins/xfpga/enum.c
- opae-libs/plugins/xfpga/error.c
- opae-libs/plugins/xfpga/event.c
- opae-libs/plugins/xfpga/metrics/bmc/bmc.c
- opae-libs/plugins/xfpga/open.c
- opae-libs/plugins/xfpga/properties.c
- opae-libs/plugins/xfpga/types_int.h
- opae-libs/tests/xfpga/test_bmc_c.cpp
- opae-libs/tests/xfpga/test_error_c.cpp
- opae-libs/tests/xfpga/test_events_c.cpp
- opae-libs/tests/xfpga/test_metadata_c.cpp
- opae-libs/tests/xfpga/test_open_close_c.cpp
- opae-libs/tests/xfpga/test_properties_c.cpp
525b0e75 opae-c: common header for internal token types (#248)
git-subtree-split: 525b0e750510a9a889ba86a87db3afa2db1440c7
> (cherry-pick) Squashed 'opae-libs/' changes from 5117a9b8..525b0e75

- samples/host_exerciser/host_exerciser.h
- samples/host_exerciser/host_exerciser_cmd.h
> samples: (Cherry-pick) rename Device Status Memory structure 

- python/opae.admin/opae/admin/tools/rsu.py
> Cherry-pick rsu: fix bug in error path 

- opae.spec.rhel
Package the following sample/tool source in the opae-devel RPM:
afu-test
hello_fpga
hello_events
object_api
n5010-test
dummy_afu
host_exerciser
hssi
opae.io
> rhel rpm: package sample/tool source

- tools/extra/hssi/ethernet/hssicommon.py
- Clear Read, Write ACK bits in HSSI Command Status and IGNORE ERROR bit filed.
- Ignore error bit and resubmit the SAL command
HSSI Command/Status CSR:
4:4:RO:Error Bit
1'b1 - Indicate SAL command timeout after 10ms and not completed successfully. User can resubmit the SAL command after root causing the error.
1'b0 - Indicate SAL command execute successfully without error
Valid when ACK_TRANS is asserted
3:3:RO: Busy Bit
1'b1 - Indicate SAL is in the middle of processing a command. Software should not send in new command when this bit is asserted.
1'b0 - Indicate SAL is free to accept new command.
2:2: RW: ACK_TRANS: Bit gets asserted when transaction is complete. Must be cleared when asserted.
1:1 : WO : Write Command
0:0 : WO : Read Command
Signed-off-by: anandaravuri …
> Tools: Clear HSSI Command Status RW and WO bits fields

- python/opae.admin/opae/admin/fpga.py
Search in all possible locations to identify the correct paths.
> rsu: fix location of available_images/image_load

- python/opae.admin/opae/admin/fpga.py
Search in all possible locations to identify the correct paths.
> (cherry-pick) rsu: fix location of available_images/image_load (#2324)

- tools/extra/hssi/ethernet/hssimac.py
- add port number   as command line argument
- fix bugs
- fix python indentation
> tools: add  command line argument  port number  to hssimac

- tools/extra/hssi/ethernet/hssimac.py
* tools: add  command line argument  port number  to hssimac
- add port number   as command line argument
- fix bugs
- fix python indentation
> tools: CP add  command line argument  port number  to hssimac

- tools/fpgainfo/board.c
- tools/libboard/board_common/board_common.c
- add fpgaDestroyProperties to free Properties object
Signed-off-by: lab <lab@psera2-dell21.ra.intel.com>
> Tools: fix fpgainfo memory leak

- tests/board/test_board_n6000.cpp
- tools/libboard/board_n6000/board_n6000.c
Signed-off-by: Esa Leskinen <ele@silicom.dk>
> libboard: n6000:  CP add BOM Critical Components specific unit test

- opae-libs/plugins/vfio/opae_vfio.c
92c8df6a libopae-v.so: filter for supported devices (#261)
git-subtree-split: 92c8df6a58b8bfd370097b8e27d9224dc3875a96
> (cherry-pick) Squashed 'opae-libs/' changes from 4e7cd3b6..92c8df6a

- tests/board/test_board_n6000.cpp
- tools/libboard/board_n6000/board_n6000.c
- Add 2 new BOM Critical Components unit test cases
- Improved robustness of BOM info reformatting
> tools: N6000 BOM info reformatting & add test cases

- doc/src/fpga_api/quick_start/readme.md
> docs: fix straggling instance of N6010

- external/CMakeLists.txt
> CLI11: update to version 2.1.2

- python/pacsign/pacsign/hsm_managers/openssl/openssl.py
When the openssl hsm_manager fails to find libcrypto.so, output a
message describing the packages required to install the library.
> PACSign: output more info when libcrypto not found

- python/pacsign/pacsign/hsm_managers/openssl/openssl.py
When the openssl hsm_manager fails to find libcrypto.so, output a
message describing the packages required to install the library.
> PACSign: CP output more info when libcrypto not found

- doc/src/fpga_api/quick_start/readme.md
> docs: CP fix straggling instance of N6010 

- tools/extra/mmlink/remote_dbg/streaming/st_dbg_ip_driver.c
* tools: fix mmlink Quartus 21.3 loopback reset
> tools: CP fix mmlink Quartus 21.3 loopback reset (#2390)

- CMakeLists.txt
> opae: change to RC 2.0.9-5

- docker/centos7.6/Dockerfile
- scripts/build-rpms.sh
Install package openssl11-devel to provide the necessary libcrypto.so
file for PACSign.
> CI: install PACSign deps for CentOS 7.6

- scripts/cover.sh
> cover.sh: bring coverage back to reality

- scripts/test-codingstyle-all.sh
> CI: fix test-codingstyle-all.sh

- opae.spec.fedora
- opae.spec.rhel
- packaging/opae/rpm/create
> opae-sdk: remove ase rpm from spec file

- doc/src/install_guide/installation_guide.md
> docs: update RPM creation process in install guide

- libraries/libboard/board_n6000/board_n6000.c
> Opae-sdk: fix fpgainfo events sysfs path

- doc/src/install_guide/installation_guide.md
> docs: (cherry-pick) update RPM creation process in install guide (#2519)

- CMakeLists.txt
- external/CMakeLists.txt
- libraries/libopae-c/CMakeLists.txt
- opae.spec.in
- samples/CMakeLists.txt
- scripts/cover.sh
- scripts/unit-tests.sh
* opae-sdk: remove ase sim build flag
* opae-sdk: remove OPAE_BUILD_SIM from sh files
> opae-sdk: (cherry-pick) remove ase sim build flag (#2516)

- opae.spec.fedora
- opae.spec.rhel
- packaging/opae/rpm/create
* opae-sdk: remove ase rpm from spec file
> opae-sdk: (cherry-pick) remove ase rpm from spec file (#2509)

- opae.spec.fedora
- opae.spec.rhel
- packaging/opae/rpm/create
> opae-sdk: fix rhel spec file build errors

- opae.spec.rhel
> packaging: rhel: package libofs_cpeng.so.*

- doc/src/fpga_tools/hssi/hssi.md
> hssi: update markdown docs for new test modes

- doc/src/install_guide/installation_guide.md
- opae.spec.rhel
- packaging/opae/rpm/create
- setup/centos.sh
- setup/fedora.sh
- setup/ubuntu.sh
Recent RPM and DEB package build changes have added/removed
packages. Update the installation guide and setup scripts to
match.
> docs: updates based on recent packaging changes

- python/opae.admin/opae/admin/tools/rsu.py
Add:
fpga_user1 fpga_user2
fpga_user2 fpga_user1
fpga_user1 fpga_user2 fpga_factory
fpga_user2 fpga_user1 fpga_factory
> rsu: update valid boot sequences

- libraries/pyopae/opae.cpp
- libraries/pyopae/pyproperties.cpp
- libraries/pyopae/pyproperties.h
- libraries/pyopae/test_pyopae.py
> python bindings: add subsystem_vendor/device ID

- binaries/fpgainfo/fpgainfo.c
> opae-sdk: add sub vendor id and sub device id to fpgainfo

- opae.spec.rhel
Update opae.spec.rhel for RHEL9 Beta.
> packaging: spec file updates for RHEL9

- cmake/modules/OPAECompiler.cmake
- opae.spec.fedora
- opae.spec.rhel
- packaging/opae/deb/opae-devel.install
> packaging: add libopae-c-archive to packages

- opae.spec.rhel
Packaging: rpm: Add support to create rpm on RHEL8.2
> Packaging: rpm: Add support to create rpm on RHEL8.2

- libraries/plugins/vfio/opae_vfio.c
- libraries/plugins/vfio/opae_vfio.h
- tests/opae-c/test_buffer_c.cpp
- tests/opae-c/test_enum_c.cpp
- tests/opae-c/test_mmio_c.cpp
- tests/opae-cxx/test_errors_cxx_core.cpp
- tests/opae-cxx/test_handle_cxx_core.cpp
- tests/pyopae/test_sysobject.py
- tests/xfpga/test_enum_c.cpp
- tests/xfpga/test_events_c.cpp
- tests/xfpga/test_mmio_c.cpp
- tests/xfpga/test_open_close_c.cpp
- tests/xfpga/test_properties_c.cpp
- tests/xfpga/test_sysfs_c.cpp
> tests: enable unit tests on n6000 SKU1 hardware

- libraries/plugins/vfio/opae_vfio.c
* Clear the valid_fields upon entry. Handles the case when
an fpga_properties object is being recycled.
* Set bbs_version.patch (bbs_version.major was being set twice).
* Add num_interrupts and state.
> vfio plugin: fix bugs and add properties

- packaging/opae/deb/control
- python/pacsign/pacsign/hsm_managers/openssl/openssl.py
> PACSign: enable PACSign on Ubuntu 22.04

- binaries/opae.io/opae/io/utils.py
> opae.io: fix reference to fn in pci.py

- binaries/opae.io/opae/io/utils.py
> opae.io: fix walk to use bitfield

- libraries/libboard/board_common/board_common.c
- libraries/libopae-c/init.c
- libraries/libopaeuio/opaeuio.c
- libraries/plugins/xfpga/metrics/vector.c
- libraries/plugins/xfpga/sysfs.c
- libraries/plugins/xfpga/usrclk/fpga_user_clk.c
- libraries/pyopae/opae.cpp
- tests/fpgad/test_config_file_c.cpp
- tests/framework/mock/opae_fixtures.h
- tests/framework/mock/test_system.cpp
- tests/framework/mock/test_system.h
- tests/opae-c/test_pluginmgr_c.cpp
- tests/pyopae/test_properties.py
- tests/pyopae/test_shared_buffers.py
- tests/pyopae/test_sysobject.py
- tests/xfpga/test_error_c.cpp
- tests/xfpga/test_metrics_c.cpp
Implement resource tracking for open file descriptors,
file and directory objects, globs, and memory allocations.
> test framework: implement resource tracking

- opae.spec.fedora
- opae.spec.rhel
- packaging/opae/deb/opae.install
> packaging: fix RPM/DEB packaging breakage.

- binaries/opae.io/MANIFEST.in
- binaries/opae.io/opae/io/run.py
- binaries/opae.io/opae/io/static/index.html
- binaries/opae.io/opae/io/static/script.js
- binaries/opae.io/pymain.h
- binaries/opae.io/setup.py
> opae.io: save progress on uservices demo

- doc/src/install_guide/installation_guide.md
> opae-sdk: update OPAE Installation Guide

- packaging/opae/rpm/create
> opae-sdk: fix cmake 3.11.4  build error

- doc/src/install_guide/installation_guide.md
* opae-sdk: update OPAE Installation Guide
* opae-sdk: fix review comments
* opae-sdk: fix opae remove command
* opae-sdk: fix code review comments
> opae-sdk: update OPAE Installation Guide (#2624)

- packaging/opae/rpm/create
> opae-sdk: Cherry-pick fix cmake 3.11.4  build error (#2625)

- binaries/opae.io/opae/io/utils.py
- binaries/opae.io/pymain.h
* add stdout stream to LOG
* change print messages to LOG
* log message when binding/new_id fails
> opae.io: enhance logging

- opae.spec.fedora
- opae.spec.rhel
- packaging/opae/deb/opae-devel.install
> packaging: add opae_std.h to fix RPM/DEB creation

- opae.spec.fedora
> packaging: enable full build for RHEL9

- doc/src/install_guide/installation_guide.md
> opae-sdk:update installation guide

- doc/src/install_guide/installation_guide.md
> opae-sdk: (CP) update installation guide (#2650)

- samples/n5010-test/n5010-test.c
> samples: n5010-test: fix error handling in QDR and eSRAM tests

- external/CMakeLists.txt
> pybind11: bump version to 2.10.0

- external/CMakeLists.txt
> (cherry-pick) pybind11: bump version to 2.10.0 (#2661)

- .github/CODEOWNERS
> CODEOWNERS: update per the current repo structure

- docker/centos7.6/Dockerfile
- docker/fedora32/Dockerfile
- docker/fedora33/Dockerfile
- docker/fedora35/Dockerfile
> opae-sdk: remove pkcs11 from docker file

- binaries/fpgainfo/board.c
- libraries/libboard/board_n6000/board_n6000.c
> opae-sdk: change  phy info OPAE  ERROR output  to MSG

- .github/CODEOWNERS
- opae.cfg
> config: add opae.cfg

- opae.cfg
> opae.cfg: touch up config file for d5005

- doc/sphinx/conf.py.in
- doc/sphinx/index.rst.in
> opae-sdk: add memory traffic generator doc to build

- doc/sphinx/conf.py.in
- doc/sphinx/index.rst.in
> opae-sdk: (cherry-pick) add memory traffic generator doc to build (#2691)

- CMakeLists.txt
- opae.spec.fedora
- opae.spec.in
- opae.spec.rhel
> opae.cfg: add config file to packaging

- binaries/vabtool/vabtool
These changes to vabtool add support for sr_cancel and pr_cancel , pr_status, pr_status, sr_cancel_status, pr_cancel_status commands and fix several issues. The SR and PR provisioning have been validated with these changes, although the cancel operations have not been fully validated yet.
> Updates to vabtool

- libraries/libopae-c/cfg-file.c
- tests/opae-c/test_cfg_file_c.cpp
Add a check for LIBOPAE_CFGFILE as the first possibility in opae_find_cfg_file() in support of non-standard environments.
> config file: try env var LIBOPAE_CFGFILE first

- opae.cfg
- python/opae.admin/opae/admin/config.py
- python/opae.admin/opae/admin/fpga.py
- python/opae.admin/opae/admin/sysfs.py
- python/opae.admin/opae/admin/tools/fpgareg.py
- python/opae.admin/opae/admin/tools/rsu.py
- tests/opae.admin/test_config.py
Implement new opae.admin.config module which loads and parses
configuration data for rsu.py and fpgareg.py at module load
time.
> config: one cfg file integration for rsu,fpgareg

- packaging/opae/deb/opae.install
> packaging: add opae.cfg to DEB package

- packaging/opae/deb/opae.install
> packaging: (Cherry-pick) add opae.cfg to DEB package (#2731)

- libraries/libopae-c/pluginmgr.c
> opae-c: add back opae_plugin_mgr_register_plugin()

- libraries/libopae-c/pluginmgr.c
> (cherry pick) opae-c: add back opae_plugin_mgr_register_plugin() (#2752)

- libraries/plugins/xfpga/usrclk/fpga_user_clk.c
> user clk: read user clock dfh revision from uio driver

- opae.spec.rhel
> packaging: rhel: fix RHEL rpm creation

- doc/src/fpga_tools/vabtool/vabtool.md
> vabtool: add markdown document

- doc/sphinx/conf.py.in
- doc/sphinx/index.rst.in
> docs: add vabtool to docs build

- libraries/libboard/board_n6000/board_event_log.c
* Fix fpgainfo events power on time stamp
SW should use the information in block with magic number '0x53696CF0' to derive power on event time stamp, and not the timestamp field of magic number '  0x53696C12'. Power on status is logged immediately after power on.  Time of the day information is written by SW into a BMC register. This write will take some time after power on and hence with Power on log there is no timestamp value available. Because of this reason, second block 'time of the day offset' (block with magic number '0x53696CF0' ) is provided from BMC. BMC internally keeps track of time lapse after the power on and first ToD write by Host and provides the correct value by reverse calculation.  Please use this information to print the power on status time
Signed-off-by: …
> (Cherry-pick) Fix fpgainfo events power on time stamp (#2771)

- libraries/libboard/board_n6000/board_event_log.c
SW should use the information in block with magic number '0x53696CF0' to derive power on event time stamp, and not the timestamp field of magic number '  0x53696C12'. Power on status is logged immediately after power on.  Time of the day information is written by SW into a BMC register. This write will take some time after power on and hence with Power on log there is no timestamp value available. Because of this reason, second block 'time of the day offset' (block with magic number '0x53696CF0' ) is provided from BMC. BMC internally keeps track of time lapse after the power on and first ToD write by Host and provides the correct value by reverse calculation.  Please use this information to print the power on status time
> Fix fpgainfo events time span power on time stamp

- libraries/libboard/board_n6000/board_event_log.c
SW should use the information in block with magic number '0x53696CF0' to derive power on event time stamp, and not the timestamp field of magic number '  0x53696C12'. Power on status is logged immediately after power on.  Time of the day information is written by SW into a BMC register. This write will take some time after power on and hence with Power on log there is no timestamp value available. Because of this reason, second block 'time of the day offset' (block with magic number '0x53696CF0' ) is provided from BMC. BMC internally keeps track of time lapse after the power on and first ToD write by Host and provides the correct value by reverse calculation.  Please use this information to print the power on status time
Signed-off-by: …
> (Cherry-pick) Fix fpgainfo events time span power on time stamp (#2779)

- libraries/libopaeuio/opaeuio.c
- tests/board/test_board_c6100.cpp
- tests/board/test_board_n6000.cpp
> libopaeuio: fix issue id'd by static analysis

- .github/workflows/build-rpms.yml
- docker/fedora35/Dockerfile
- docker/fedora36/Dockerfile
- scripts/build-rpms-new.sh
> Updating fedora35 build to create new RPMs

- .github/workflows/build-debs.yml
- docker/ubuntu22/Dockerfile
- scripts/build-debs.sh
- scripts/test-debs.sh
> ci: add .deb build job

- binaries/CMakeLists.txt
> fix rhel package create errors

- libraries/libopaeuio/opaeuio.c
> fix static code analysis issue

- binaries/CMakeLists.txt
> (Cherry-pick) fix rhel package create errors (#2800)

- libraries/libopaeuio/opaeuio.c
> (Cherry-pick) fix static code analysis issue (#2802)

- libraries/plugins/vfio/opae_vfio.c
> opae-v: fix issue found by static analysis

- binaries/fpgadiag/src/eth_group.h
> fix static code analysis - Uninitialized Variable in Constructor

- libraries/plugins/vfio/opae_vfio.c
> opae vfio : fix static code analysis issue - Memory Leak

- libraries/plugins/vfio/dfl.c
-Result of function that may return NULL will be dereferenced
> fix static code analysis - NULL will be dereferenced

- binaries/opae.io/main.cpp
> opae.io: fix static code analysis issue

- CONTRIBUTING.md
- README.md
> README: update mailing list info

- libraries/pyopaeuio/CMakeLists.txt
- libraries/pyopaeuio/setup.py
- opae.spec.fedora
- packaging/opae/deb/rules
Signed-off-by: anandaravuri <ananda.ravuri@intel>
> fix pybin11 build error

- libraries/pyopae/opae/fpga/__init__.py
- libraries/pyopae/pyproperties.cpp
- libraries/pyopae/test_pyopae.py
> pyopae: Fix definition of fpga_interface enum

- libraries/plugins/vfio/dfl.c
* fix static code analysis - NULL will be dereferenced -Result of function that may return NULL will be dereferenced
> (Cherry-pick) fix static code analysis - NULL will be dereferenced (#2820)

- libraries/plugins/vfio/opae_vfio.c
* opae vfio : fix static code analysis issue - Memory Leak
> opae vfio :  (Cherry-pick) fix static code analysis issue - Memory Leak (#2826)

- libraries/pyopaeuio/CMakeLists.txt
- libraries/pyopaeuio/setup.py
- opae.spec.fedora
- packaging/opae/deb/rules
> (Cherry-pick) fix pybin11 build error (#2836)

- binaries/opae.io/opae/io/config.py
- libraries/libopae-c/cfg-file.c
- opae.cfg
- python/opae.admin/opae/admin/config.py
- tests/opae.admin/test_config.py
- tests/opae.io/test_config.py
rename C6100 platform name to  in opae.cfg
> rename C6100 platform name to Intel IPU Platform F2000X-PL

- libraries/libboard/board_c6100/board_c6100.c
- libraries/libboard/board_common/board_common.c
- libraries/libboard/board_common/board_common.h
- libraries/libboard/board_n6000/board_n6000.c
fpgainfo phy reads QSFP cable  status and prints connected or not connected
QSFP0                            : Not Connected
QSFP1                            : Not Connected
> add QSFP cable status to fpgainfo phy

- binaries/opae.io/opae/io/utils.py
* Improved error reporting when IOMMU is disabled
(cherry picked from commit 2ae85fa053cd32a0dc5db313ce843299515d54c4)
> Improved error reporting when IOMMU is disabled (#2922)

- python/opae.admin/opae/admin/fpga.py
After waiting, then rescanning PCI devices, touch up the root port and endpoints by clearing device status, uncorrectable, and correctable errors.  Preserve MaxReadReq size of 4096.
> rsu: clear errors after rescan

- python/opae.admin/opae/admin/tools/rsu.py
fpga.enum returns a list, using a for loop to handle 0 or more elements.
> rsu, pci_device: fix fpga.enum returns a list

- binaries/ofs.uio/uio/msix.json
- binaries/ofs.uio/uio/ofs_uio.py
-add mailbox-json input command , json file contains array of mailbox reg  name, address, and value
Example: msix.json
[
{
"reg-name": "pf0",
"address": "0x20000",
"value": "0x22"
},
{
"reg-name": "pf1",
"address": "0x20004",
"value": "0x23"
},
{
"reg-name": "pf2",
"address": "0x20008",
"value": "0x24"
}
]
> ofs.uio add mailbox json input command to write multiple mailbox values.

- platforms/scripts/platmgr/tools/rtl_src_config.py
Because Verilog and VHDL simulation is handled by two separate compilations, the rtl_src_config -sim switch now supports --sim-vlog and --sim-vhdl to generate source lists. For backward compatibility, Verilog is the default.
> Add separate Verilog and VHDL source management to rtl_src_config

- SECURITY.md
* SDL Include security.md file in open source repos
---------
> (Cherry-pick) SDL Include security.md file in open source repos (#2959)

- binaries/ofs.uio/uio/ofs_uio.py
peek-dump Command-line arguments
--peek-dump address size
Peek CSR start address size (e.g.--peek-dump 0x0 0x20).
log level  Command-line arguments
--log-level {verbose,info}
log level to use
> ofs.uio:add peek dump and log level Command-line arguments

- samples/hello_afu/README.md
> Update QUARTUS_HOME references to QUARTUS_ROOTDIR

- libraries/libboard/board_n6000/board_event_log.c
error in bel_power_regulator_info of N6000 Board
https://github.com/OFS/opae-sdk/issues/2996
> fix fpgainfo events n6000  bel_power_regulator_info

- samples/cxl_host_exerciser/cxl_he_cache_cmd.h
- samples/cxl_host_exerciser/cxl_host_exerciser.h
- samples/cxl_host_exerciser/he_cache_test.h
- add loop count  command line input and set read /write config
- set FPGA / host  read and write cache miss opcode to  RD_LINE_I /WR_LINE_I
> Feature:add loop count command line input to CXL host exerciser

- binaries/fpgametrics/fpgametrics.c
- libraries/plugins/xfpga/metrics/metrics_max10.c
- update fpga metrics index numbered from 1-42 (instead of 0-41)
- improve fpgametrics  output readability
- group power and thermal sensor strings and values
> fix: (Cherry-pick) improve fpgametrics output readability and (#3075)
